### ISSUE TITLE
If a class is marked Serializable ConfuserEx won't even rename static fields (and option to rename serializable types)

### ISSUE THREAD

**Issue by MulleDK19** [mkaring/ConfuserEx#101]
If a type is marked serializable, all the static fields won't be renamed either even though those are never serialized.

It would also be nice with an option to rename fields of types marked Serializable. I have a rather large project that makes heavy use of remoting cross app domains, which internally uses serialization, so it doesn't matter if the fields are obfuscated, it has no side effect. But it currently means that ConfuserEx won't rename a substantial part of the application because so many types are marked Serializable for the remoting.

**Comment by mkaring** [comment]
Obfuscating serializable assemblies is a choice, ConfuserEx can't make, because it may break the application.
You can enforce the obfuscation of serializable classes. Find the example [here in the wiki](https://github.com/mkaring/ConfuserEx/wiki/Name-Protection#example)
