### ISSUE TITLE
Protected variables are being renamed, but shouldn't

### ISSUE THREAD

**Issue by horacioj** [mkaring/ConfuserEx#103]
I was using version 1.0.0 without issues. In this version, public or protected members aren't renamed.

Using the latest v1.3.1 in this fork, the program fails because protected members are being renamed.
It is a web forms app. In a .ascx some protected members are referenced (defined in its code-behind file.

**Comment by mkaring** [comment]
Can you provide an minimal example to reproduce this?
It shouldn't rename `protected` members, unless the class is `internal`.

**Comment by horacioj** [comment]
Sure! Please find a small project attached. Removed from the ZIP, under \ConfuserEx it should be the content of https://github.com/mkaring/ConfuserEx/releases/download/v1.3.1/ConfuserEx.zip

Build it and run  .\Install\Confuse.bat

Then run the app and it will crash:
 
--
Line 6:  <script type="text/javascript"> Line 7:   Line 8:          var qsFileId = "<%=QsFileId %>"; Line 9:          var qsModuleId = "<%=QsModuleId %>"; Line 10:

Decompiling the DLL you can see the renamed variables:

using System;
using System.Web.UI;

namespace ConfuserExTest
{
    public class View : UserControl
    {
        protected string LYXQNat0i55RPHN$F8SXgoE
        {
            get
            {
                return 444.ToString();
            }
        }

        protected string UX5z5L2ukAZ2X49e1$VZgH0
        {
            get
            {
                return 555.ToString();
            }
        }

        public View()
        {
        }
    }
}
[ConfuserExTest.zip](https://github.com/mkaring/ConfuserEx/files/3776286/ConfuserExTest.zip)

They are protected strings defined within a public partial class 

Thanks!

**Comment by mkaring** [comment]
Thank you for the example. I tracked the issue back. It was introduced by the changes for yck1509#462. I implemented the required changes. Please verify that the build you can download [from the buildserver][0] works for your actual project.

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/28578749/artifacts

**Comment by horacioj** [comment]
It works! Thank you for the quick fix.
