### ISSUE TITLE
wpf .net core 3.0 Could not resolve type: System.Runtime.CompilerServices.IAsyncStateMachine

### ISSUE THREAD

**Issue by AR1ES** [mkaring/ConfuserEx#106]
Confuser version: 2.0.0-alpha+8ad42fe229
I tried to configure ConfuserEx on a desktop .net core 3.0 DLL , but I get an error:
```Failed to resolve a type, check if all dependencies are present in the correct version.
dnlib.DotNet.TypeResolveException: Could not resolve type: System.Runtime.CompilerServices.IAsyncStateMachine (System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at dnlib.DotNet.TypeRef.ResolveThrow(ModuleDef sourceModule)
   at Confuser.Renamer.VTableStorage.GetVTable(ITypeDefOrRef type) in C:\projects\confuserex\Confuser.Renamer\VTable.cs:line 388
   at Confuser.Renamer.VTable.ConstructVTable(TypeDef typeDef, VTableStorage storage) in C:\projects\confuserex\Confuser.Renamer\VTable.cs:line 164
...
```

**Comment by mkaring** [comment]
The support for .NET Core is currently very limited. You have to add the dependency assemblies of .NET Core manually as references to your project.

See also: #74 #72 #58 #40

These issues are basically about the same thing.

**Comment by AR1ES** [comment]
Thanks for the answer.

I am also trying to user Confuser.MSBuild 2.0.0-alpha from Nuget, but I get this error without details:
```[CRITICAL] Failed to resolve a type, check if all dependencies are present in the correct version```

In fact the project does not have depency on System.Runtime, Version=4.2.1.0. Dependcies from deps.json refer to System.Runtime/4.3.0.

I am trying to set modul reference in .crproj to SystemRuntime.dll from nuget folder, from dotnet\shared\Microsoft.NETCore.App\3.0.0, but error always the same.

Maybe you have recommendations on how to determine the necessary references and paths?

**Comment by KvanTTT** [comment]
I have the same error under netcore3.1 and my app does not contain WPF.

**Comment by mkaring** [comment]
There is a test repository here:
https://github.com/mkaring/TestApp

It contains a .NET Core assembly for testing purposes, that works fine.

**Comment by dekenless** [comment]
> There is a test repository here:
> https://github.com/mkaring/TestApp
> 
> It contains a .NET Core assembly for testing purposes, that works fine.

It works fine, until you change the method in Class1 of TestApp.Lib to something like:

` public int GetARandomInt()
        {
            object o = null;
            var test = o?.GetType()?.Name;
            return new Random().Next();
        }
`


And if you change the target framework:
` <TargetFramework>netcoreapp3.1</TargetFramework>`

Then you will get the following exceptions when compiling:
`1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Failed to resolve a type, check if all dependencies are present in the correct version.
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Could not resolve type: System.Reflection.MemberInfo (System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : ---BEGIN DEBUG INFO---
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Installed Framework Versions:
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :     v4
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :     Client  4.8.04084
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :     Full  4.8.04084
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :     v4.0
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :     Client  4.0.0.0
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :     v4.5 528372
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : 
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Cached assemblies:
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :     TestApp.Lib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (W:\Temp\TestApp-master\TestApp.Lib\obj\Debug\netcoreapp3.1\TestApp.Lib.dll)
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :         System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :         System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error :         System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`

I

**Comment by kirsan31** [comment]
@mkaring 
> The support for .NET Core is currently very limited. You have to add the dependency assemblies of .NET Core manually as references to your project.

Any ETA on .net core support?

**Comment by Hidend** [comment]
> > There is a test repository here:
> > https://github.com/mkaring/TestApp
> > It contains a .NET Core assembly for testing purposes, that works fine.
> 
> It works fine, until you change the method in Class1 of TestApp.Lib to something like:
> 
> `public int GetARandomInt() { object o = null; var test = o?.GetType()?.Name; return new Random().Next(); }`
> 
> And if you change the target framework:
> ` <TargetFramework>netcoreapp3.1</TargetFramework>`
> 
> Then you will get the following exceptions when compiling:
> `1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Failed to resolve a type, check if all dependencies are present in the correct version. 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Could not resolve type: System.Reflection.MemberInfo (System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : ---BEGIN DEBUG INFO--- 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Installed Framework Versions: 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : v4 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Client 4.8.04084 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Full 4.8.04084 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : v4.0 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Client 4.0.0.0 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : v4.5 528372 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : Cached assemblies: 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : TestApp.Lib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (W:\Temp\TestApp-master\TestApp.Lib\obj\Debug\netcoreapp3.1\TestApp.Lib.dll) 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 1>W:\NugetPackages\confuser.msbuild\1.4.1\build\Confuser.MSBuild.targets(66,5): error : System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`
> 
> I

I do h ave the same problem, is there any ETA?

**Comment by mkaring** [comment]
As of right now: No.
Tracking and updating the state of support for the newer versions of .NET will be handled in this issue: #302
