### ISSUE TITLE
Cannot compile source code for the ConfuserEx 1.3.1 Release

### ISSUE THREAD

**Issue by glasgowrob** [mkaring/ConfuserEx#107]
Hello @mkaring,

**What steps must one take to compile source code for the ConfuserEx 1.3.1 Release?**

I've been trying all day to download and compile the source code for the ConfuserEx 1.3.1 Release in order to remove the ConfusedBy watermark by commenting out a foreach loop that starts beneath the line that reads "context.Logger.Debug("Watermarking...");" in the file "Confuser.Core\ConfuserEngine.cs".

Unfortunately, regarding the ConfuserEx 1.3.1 Release located at [https://github.com/mkaring/ConfuserEx/releases/tag/v1.3.1](https://github.com/mkaring/ConfuserEx/releases/tag/v1.3.1) , the  "Source code (zip)" zip file has an empty dnlib folder, so the Confuser2.sln Visual Studio solution file cannot compile.

When I download the dnlib project separately and copy and paste it into the dnlib directory, the Confuser2.sln solution still won't compile.

It would be really amazing for users of your ConfuserEx, and would save you time by cutting back on the Issues people keep keep posting to this Issues list, if the Confuser2.sln Visual Studio solution downloaded from the "Source code (zip)" zip file simply compiled without problems and without the user having to figure out where to get different pieces of the solution's code from.

Thanks in advance,

glasgowrob

**Comment by mkaring** [comment]
Hi,

The zip file you are talking about is generated automatically by github and to my best knowledge I don't have any way to get rid of it. These source archives can't get used to compile the project without getting some other sources and they are not meant to be used this way.

If you want to compile ConfuserEx yourself, you should clone the repository and fetch all the submodules. After doing so you will have all the sources required and the project is going to build out of the box.

Best regards,
Martin

**Comment by glasgowrob** [comment]
Hi Martin (@mkaring),

Thanks for helping me understand the issue with the automatic creation of the zip files from GitHub. I will stop downloading the source code from that location.

I was able to clone the repository and fetch all the submodules using the Git Gui with "Recursively clone submodules too", then I cleaned then re-built the Confuser2.sln solution in Release mode using Visual Studio 2019, and then I tested my Confuser.CLI.exe just compiled from the cloned source code using my normal build script, **but there is definitely a bug in it that does not exist in the pre-compiled ConfuserEx 1.3.1 release that can be downloaded from [https://github.com/mkaring/ConfuserEx/releases/tag/v1.3.1](https://github.com/mkaring/ConfuserEx/releases/tag/v1.3.1), which is that the pre-compiled ConfuserEx 1.3.1 release's "Confuser.CLI.exe" renames enum values, but the "Confuser.CLI.exe" that is created from recursively cloning the source code of ConfuserEx from [https://github.com/mkaring/ConfuserEx.git](https://github.com/mkaring/ConfuserEx.git) then compiling it in the manner described above does not rename enum values**.

I previously reported this bug in #62 ("Is there any way to force enum values to be renamed?") and then closed the issue when the bug wasn't present in the pre-compiled release.

I think that #62 should be reopened, since the bug still exists in the recursively cloned source code version of ConfuserEx.

**From where, or how, can I download a version of the the source code of ConfuserEx that can be compiled such that "Confuser.CLI.exe" renames enum values?**

Note: here is the "rename" protection tag I am using:

```
<protection id="rename">
	<argument name="mode" value="decodable" />
	<argument name="flatten" value="true" />
	<argument name="renameArgs" value="true" />
	<argument name="renPublic" value="true" />
	<argument name="renEnum" value="true" />
	<argument name="renXaml" value="true" />
	<argument name="renPdb" value="false" />
	<argument name="forceRen" value="false" />
</protection>
```

Thank you very much for your help as always. Hopefully I am helping you identify an actual bug instead of just taking up your time.

glasgowrob

**Comment by mkaring** [comment]
Hi,

I think you are working on the wrong branch. Make you are on the `master` branch and not on the `release/2.0` branch.
The `master` branch is the 1.3.1 version plus [these bugfixes][0]. In case you are on the wrong branch, make sure to switch it, update the submodules and clear out your local files, so Visual Studio does not get confused. Basically run these `git` commands while visual studio is **not** running:

```bash
git fetch
git checkout master
git submodule update --init --recursive
git clean -f -X -d
```

Once done, you can open the solution in Visual Studio and you'll be fine. If you want to use exactly version 1.3.1, you can do so as well, by calling:

```bash
git fetch --tags
git checkout v1.3.1
```

This has to be done instead of `git checkout master`.

I hope that gets you on the right track.

[0]: https://github.com/mkaring/ConfuserEx/milestone/6?closed=1

**Comment by glasgowrob** [comment]
Hi Martin (@mkaring),

Brilliant, thanks! I used the first set of instructions you provided to get the master branch instead of the release/2.0 branch, and the enum values are renamed beautifully.

I didn't understand that the release/2.0 branch wasn't the newest code, but your explanation made everything make sense.

Thank you very much!

glasgowrob

**Comment by mkaring** [comment]
Hi @glasgowrob 

The `release/2.0` branch is the preparation branch for the next major release of ConfuserEx. It is currently not ready for production and is in the middle of rewriting and restructuring how specific things work. That is the reason why it's currently behaving strangely at times 😉 

The `master` branch is the development branch for the 1.x releases of ConfuserEx and is the source of the current releases.

Best regards,
Martin

**Comment by glasgowrob** [comment]
Hi @mkaring,

Thanks for the explanation. I'll keep an eye out for ConfuserEx 2.0 and in the meantime will always use the master branch.

Best regards,
glasgowrob
