### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by LaraSQP** [mkaring/ConfuserEx#108]
First of all, thank you from the bottom of my heart for keeping this project going.

ConfuserEx supports plugins but I have yet to find any. My fault, no doubt.

Any leads would be most appreciated.

**Comment by mkaring** [comment]
As far as I am aware, there aren't any plugins that are publicly available.
I know of a few cases, where there users of ConfuserEx created custom plugins for their specific projects, but those are all private developments.

**Comment by ElektroKill** [comment]
Here is an example of a plugin: https://github.com/HoLLy-HaCKeR/Confuser.Protections.HoLLy
It cannot be loaded by the 2.0 branch because the plugin system has changed.

**Comment by xHeaven** [comment]
Here's some more.
https://github.com/xHeaven/ConfuserEx-Additions
https://github.com/xHeaven/KoiVM-modded

Cheers

**Comment by LaraSQP** [comment]
Thank you, guys. Much appreciated.
