### ISSUE TITLE
feature requests/questions

### ISSUE THREAD

**Issue by thekjohn** [mkaring/ConfuserEx#112]
Hello!

I am asking for/about if these features are/will be available at some point in time:
- adding random properties/fields to classes
- randomly changing the order of properties/fields in classes
- simple, nuget-delivered API in a dll (like: new ConfuserEx().Confuse("x.dll", "y.dll", settings);

Regards,
John

**Comment by ElektroKill** [comment]
Hi, in my opinion, point number 1 makes no sense as it just adds weight to the module and doesn't make the protection any harder to crack. I also don't know what would point number 2 does to make this protection harder to crack. As for number 3, it already exists but not as a NuGet package, you have to add a reference to Confuser.Core.dll and call ConfuserEngine.Run(); with an instance of ConfuserParameters as the argument. That's at least how it is in the master branch from what I remember.

**Comment by thekjohn** [comment]
The first two helps agains memory reading attacks.
Thanks for the ConfuserEngine.Run() hint, I'll check it soon!

**Comment by FenixDan** [comment]
> The first two helps against memory reading attacks.
> Thanks for the ConfuserEngine.Run() hint, I'll check it soon!

It doesn't help at all, it just adds garbage fields which does nothing.

**Comment by thekjohn** [comment]
I rephrase: it helps against basic memory reading attacks againt my dynamically compiled plugins :)

**Comment by FenixDan** [comment]
> I rephrase: it helps against basic memory reading attacks againt my dynamically compiled plugins :)

Well, I don't consider such additions a real protection, but if you do, you could easily create a new Protection and add some random fields to your classes and so on.

Feel free to give us an example of what adding some random fields would prevent from memory reading.

**Comment by mkaring** [comment]
As it was already said adding random members and/or types will not help much. Any meaning full memory reading attack requires that the person or application reading the assembly at least understands the structure of a .NET assembly and in that case the attacker won't be distracted by dummy members.

If you are worried about those good old hacks like "change byte x to y to change a thing" (is anyone still doing that?), you can simply enable something like the constant protection. This will add additional methods and data blocks to the assembly. The data blocks are encrypted with a random key that is created by the seed you can set in ConfuserEx (if you don't set it the seed is random). Those data blocks are in addition encrypted. This all means that the sizes of the data blocks likely vary by some bytes if you run the same obfuscation on the same source assembly multiple times. This will cause the memory block containing the method bodies to shift by a few bytes anyway.

The API like you requested is as @ElektroKill said basically there, but there aren't any nuget packages that provide it. If you need something like this you can fork ConfuserEx and compile it yourself. You find a minimal example of how to execute the Engine of ConfuserEx in the MSBuild integration:
https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.MSBuild.Tasks/ConfuseTask.cs
