### ISSUE TITLE
Configuration should allow to remove watermark

### ISSUE THREAD

**Issue by griknok** [mkaring/ConfuserEx#115]
This seems to be an old issue that was ignored because "I don't see the need of doing so"
https://github.com/yck1509/ConfuserEx/issues/229

Surely removing the watermark would decrease the likelyhood that the suite of malware detection softwares out there could detect that someone used ConfuserEx? After all if you use ILSpy and it clearly states to you "[module: ConfusedBy("Confuser.Core 1.3.1+cf4240c129")]" then that isn't very obfuscated information 😉

**Comment by mkaring** [comment]
Well the goal is that you can revert the obfuscation even if you know that ConfuserEx was used to obfuscate it. The watermark is just there is brag about how good ConfuserEx is. 😉 

I'll look into adding a option, so you can remove the watermark if you choose to. 😢

**Comment by xHeaven** [comment]
Well, you could disable it with a simple flag, if you want to, or you could delete the whole watermarking procedure, here: **https://github.com/yck1509/ConfuserEx/blob/3e3e4ae8ef01e3a169591e9b7803408e38cce7ca/Confuser.Core/ConfuserEngine.cs#L303**

**Comment by mkaring** [comment]
Starting with the 1.4 release, The watermark will be applied as part of an additional "protection" that is implicitly enabled.
You'll be able to remove by adding a "watermark" protection with the "remove" flag to strip the watermark from some or all modules.

![image](https://user-images.githubusercontent.com/842566/73119648-3f08a780-3f65-11ea-8650-245202f80bc1.png)
