### ISSUE TITLE
Running a rename-only profile twice on an executable makes it un-executable

### ISSUE THREAD

**Issue by griknok** [mkaring/ConfuserEx#116]
To repro:
1. Create a simple winforms .exe
2. Obfuscate with only the following profile:
`<rule pattern="true" inherit="false">
        <protection id="rename">
            <argument name="mode" value="letters" />
            <argument name="flatten" value="false" />
        </protection>
    </rule>`
3. Re-obfuscate the output from (2).
4. The final executable will not run.

I wouldn't normally run obfuscation twice, but I thought I would test it because I suspected that running a profile that contained only _rename_ was actually doing other things, and it must be! Surely I could run rename 100 times and it would still work: it would be no more obfuscated than the first obfuscation, but because the exe no longer executes _something else is being modified_

**Comment by mkaring** [comment]
My guess without testing it, is that the reason for this is the watermark. It adds the attribute type without checking if it's already present.

**Comment by griknok** [comment]
Excellent! Another good reason to remove this fingerprint 😉

**Comment by mkaring** [comment]
My guess was correct. The issue is caused by the Watermark. The fix in #115 resolves the issue, even if the watermark is enabled for both protection passes.
