### ISSUE TITLE
Confused dll doesn't replace output

### ISSUE THREAD

**Issue by dormouses** [mkaring/ConfuserEx#117]
I set property `<ConfuserReplaceOutput>true</ConfuserReplaceOutput>`. But it doesn't work.

To fix it you can replase

```
  <Target Name="ConfuserEx"  DependsOnTargets="$(ConfuserExDependsOn)" BeforeTargets="PrepareForRun"/>
```

To

```
<PropertyGroup>
  <PrepareForRunDependsOn>
    ConfuserEx;
    $(PrepareForRunDependsOn) 
  </PrepareForRunDependsOn>
</PropertyGroup>  
<Target Name="ConfuserEx"  DependsOnTargets="$(ConfuserExDependsOn)" />
```

Because target `ConfuserEx` must be executed before` $(PrepareForRunDependsOn)` especially before `CopyFilesToOutputDirectory` target. But now it is executed after it.

https://docs.microsoft.com/en-us/visualstudio/msbuild/target-build-order?view=vs-2019

**Comment by mkaring** [comment]
This issue is already known and resolved for the next version by issue #110
