### ISSUE TITLE
Obfuscar ? hold ConfusexEx ?

### ISSUE THREAD

**Issue by panpansh** [mkaring/ConfuserEx#119]
Hi, 
Did you know obfuscar ?
https://github.com/obfuscar/obfuscar/blob/master/readme.md 
 
It say it use ConfuserEx. 
https://docs.obfuscar.com/tutorials/source.html
 
Whats the global diff please ? 
Regards

**Comment by ElektroKill** [comment]
Hi, Obfuscar used ConfuserEx’s BAML Reader and Writer for their renaming. Now they have switched to ILSpy BAML reader and writer.

**Comment by panpansh** [comment]
@ElektroKill thanks for your reply,
can i ask you which one you prefer to use and why technically please ?
Much thanks.

**Comment by ElektroKill** [comment]
Both are pretty much the same, the core(BamlDocument.cs, BamlRecords.cs, BamlReader.cs and BamlWriter.cs) is written by yck1509, the original author of ConfuserEx, ILSpy developers have adapted the dnSpy Baml decompiler which uses the ConfuserEx code. The ILSpy and dnSpy code feature mostly some adaptations and bug fixes compared to the ConfuserEx code.

**Comment by panpansh** [comment]
@ElektroKill thank you very much, 
 
Finally, I understood : 
ILspy itself uses ConfuserEx. 
Obfuscar uses ILspy. 
 
Obfuscar last published 19 Nov 2019.
Obfuscar use ILspy cf7deca7e17ca9c6437c06d92c99fb1d7429616c published 19 Jun 2019.
ConfuserEx is more active..

The main question would be what one does better than the other ?

**Comment by KvanTTT** [comment]
I did a small investigation on confusers last year. I found out that ConfuserEx has more features and more convenient for me. As I understand, Obfuscar has only renaming and constants protections. ConfuserEx has both these ones and [several others](https://github.com/mkaring/ConfuserEx/wiki/Protections). Also, I couldn't set up Obfuscar for my project.

This project is under development and the author fixes bugs, at least the most significant.

**Comment by panpansh** [comment]
I want to thank you both for this clarification.
I really appreciate.

**Comment by ElektroKill** [comment]
ConfuserEx features much more advanced protection features, better support, and much better renaming. ConfuserEx has very advanced renaming which has good support for WPF, Winforms, reflection, json, etc.. It could probably beat even some commercial protectors. With ConfuserEx you also have more possibilities because if you don’t have a feature you need you can make a plug-in!

**Comment by mkaring** [comment]
The question has been answered
