### ISSUE TITLE
Failed to resolve dependency for Obfuscating Assembly

### ISSUE THREAD

**Issue by dawoat** [mkaring/ConfuserEx#125]
**Failed to resolve Assembly for Obfuscating dll?**

.NetFramework: 4.7.2
Visual Studio 2019

### Assemblys:
![grafik](https://user-images.githubusercontent.com/61103316/74599777-d904d100-5087-11ea-9199-91549412d78a.png)

### Visual Studio output (Confuser.CLI):

[INFO] Confuser.Core 1.3.1+cf4240c129 Copyright © 2014 Ki, 2018 Martin Karing
[INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 32 bits
[DEBUG] Discovering plugins...
[INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
[INFO] Loading input modules...
[INFO] Loading 'Release\global.dll'...
[INFO] Initializing...
[DEBUG] Building pipeline...
[INFO] Resolving dependencies...
**[ERROR] Failed to resolve dependency of 'global.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: eonCOvbOAcmpjTVmCObeIACbngDac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=6079f2ec057cbec5
bei dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule)
bei Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context)**
Failed at 06:12, 0:00 elapsed.

### ConfuserEx Gui:

![grafik](https://user-images.githubusercontent.com/61103316/74599676-0f415100-5086-11ea-96fa-f9da17c4f1fa.png)

![grafik](https://user-images.githubusercontent.com/61103316/74599739-49f7b900-5087-11ea-9b82-476750fce190.png)

![grafik](https://user-images.githubusercontent.com/61103316/74599677-18cab900-5086-11ea-8008-c064dd98381b.png)

### crproj File:
```
<project outputDir="D:\SourceCode\hydra\Output\Confused" baseDir="D:\SourceCode\hydra\Output" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" inherit="false" />
  <module path="Release\global.dll" snKey="D:\SourceCode\hydra\global\PrivateKey.pfx" snKeyPass="SamplePassword">
    <rule pattern="true" preset="maximum" inherit="false" />
  </module>
</project>
```

How to fix this Problem!?

**Comment by mkaring** [comment]
There is something strange going on here. It crashes way before applying any kind of obfuscation. It looks like there is an assembly reference that is properly generated during compile time.
Is there anything "special" going on during the build of the `global.dll` that could lead to such an assembly being generated?

If you open your assembly in [dnSpy] or [ILSpy], can you see that additional reference?

[dnspy]: https://github.com/0xd4d/dnSpy
[ILSpy]: https://github.com/icsharpcode/ILSpy

**Comment by dawoat** [comment]
I have solved it today, use Visual Studio 2019 with latest update.
After i deactivate the Signing of the Dll in Visual Studio and only do it in ConfuserEx 2 it works.
Generates the dll with "Rebuild All".

But the choke is if you try to start the Release Application in Explorer... nothing happens.

Switch back to Studio and press STRG+F5 one or two times and if Programm opens it will run also when you start the executeable in Explorer.
