### ISSUE TITLE
being able to exclude specifics

### ISSUE THREAD

**Issue by mtnjustme** [mkaring/ConfuserEx#130]
it's possible in code, but impossible as far as i know in the program itself, would be cool to have options to exclude namespaces/etc in a confuser ex project itself, this way the project might be opened several times for several different c# projects that use those same namespaces and have them automatically having the specific settings.
more to that, being able to make options for specific namespaces/methods/etc instead of only files would be a thing either.
it's really annoying that options are set on the whole file and thats it.
for example, some resources are large, and encrypting them makes the program slow, but they're not important, and it doesn't matter if they're encrypted or not, on the other hand, there are 10 kb resources that store valuable data, or several of those, and it's impossible to select which to be encrypted or not.
on the other point, there can be namespaces that have their methods serialized, but events not. so deciding to rename only its events and avoid methods (but having other operations being placed in methods) would be cool too.

**Comment by mkaring** [comment]
Using the [`namespace()`][1] expression function you are already to change the configuration for specific namespaces using the ConfuserEx project file.

Take this rules configuration as an example:
```XML
<rule pattern="true">
  <protection id="rename" />
</rule>
<rule pattern="namespace('YourNamespaceHere')">
  <protection id="rename" action="remove" />
</rule>
```
It will enable the renaming in the entire assembly, unless the class is located in a Namespace called `YourNamespaceHere`. For a more complex selection of the namespace, the literal that is `YourNamespaceHere` in the example is treated as an regular expression.

The protections `anti tamper`, `anti debug`, `anti dump`, `anti ildasm`, `invalid metadata`, and `resources` work on a per-module level and can only be enabled or disabled for a entire assembly.

Not all the protections support enabling and disabling on a per-namespace base.

[1]: https://github.com/mkaring/ConfuserEx/wiki/Expression-Functions#namespacestring

**Comment by mkaring** [comment]
I'll close this for now. If there are any further questions, feel free to open the issue again or create a new one.

**Comment by cobbr** [comment]
@mkaring Is it possible to exclude specific classes/Types rather than whole namespaces?

**Comment by snq-** [comment]
@coobr :
```
<rule pattern="(namespace('YourNamespaceHere')) and (match-type-name('YourTypenameHere'))">
	<protection id="rename" action="remove" />
</rule>
```

see the [docs on expression functions](https://github.com/mkaring/ConfuserEx/wiki/Expression-Functions)

**Comment by KvanTTT** [comment]
@snq your rule can be rewritten without excess parentheses:

```
<rule pattern="namespace('YourNamespaceHere') and match-type-name('YourTypenameHere')">
	<protection id="rename" action="remove" />
</rule>
```
