### ISSUE TITLE
Exception: dnlib.DotNet.TypeResolveException 

### ISSUE THREAD

**Issue by devpikachu** [mkaring/ConfuserEx#133]
Upon trying to obfuscate a netstandard2.0 dll, I get the following error:

```
[ERROR] Failed to resolve a type, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: System.AppDomain (System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at dnlib.DotNet.TypeRef.ResolveThrow(ModuleDef sourceModule)
   at dnlib.DotNet.Extensions.ResolveTypeDefThrow(ITypeDefOrRef tdr)
   at Confuser.Renamer.Analyzers.InterReferenceAnalyzer.ProcessMemberRef(ConfuserContext context, INameService service, ModuleDefMD module, IMemberRef r)
   at Confuser.Renamer.Analyzers.InterReferenceAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def)
   at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer)
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
```

[Full stack trace and debug](https://pastebin.com/KeD1CHRB)

**Comment by mkaring** [comment]
The support for .NET Core/.NET Standard is currently very limited. You have to add the dependency assemblies of .NET Standard manually as references to your project.

See also: #40 #58 #74 #72 #106

These issues are basically about the same thing.

**Comment by devpikachu** [comment]
@mkaring 

I have added the dependency for `System.Runtime.Extensions.dll` as shown below in the crproj file, yet the error persists:

```
<project outputDir="D:\Development\Test\Confused" baseDir="D:\Development\Test" xmlns="http://confuser.codeplex.com">
  <module path="Core.dll">
    <rule pattern="true" preset="maximum" inherit="false" />
  </module>
  <module path="Newtonsoft.Json.dll" external="true" />
  <module path="C:\Program Files (x86)\Microsoft Visual Studio\Shared\Packages\System.Runtime.Extensions.4.1.0\lib\net462\System.Runtime.Extensions.dll" external="true" />
</project>
```

**Comment by mkaring** [comment]
Are you sure you got the correct reference to `System.Runtime.Extensions` ? You are referencing the one for .NET Framework 4.6.2, but you said you are compiling for .NET Standard 2.0. Also the version number does not match from what I can tell. Are your dependencies of the source project all good?

**Comment by devpikachu** [comment]
In my latter edit, I referenced the libraries contained in GAC, which are also the ones referenced by the project.

Please do note that in Visual Studio, under references, for a .NET Standard 2.0 project, it only seems to reference netstandard.dll, which has been added.

If you'd like, I'd be more than happy to provide you with the project to check yourself.

**Comment by mkaring** [comment]
You can send it over, I'll check out what is wrong.

**Comment by devpikachu** [comment]
Here's the [download link](https://we.tl/t-v9q9rFbpVX) (contains both the csproj and the crporj).

**Comment by mkaring** [comment]
Okay so there is something strange going on here.
If I build your project, it's properly referencing .NET Standard. Meaning ConfuserEx is able to obfuscate without hassle.

The assembly that was already precompiled in the zip archive references .NET Core 2.0. Thats a whole different deal. In that case you need to add the required assemblies as external references so ConfuserEx properly resolves them. In that case you need to reference the .NET core assemblies. You'll find the path to those assemblies by running `dotnet --list-runtimes` in your command line. That will give you lines such as:
```
Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
In that case you are going to find the assemblies you need to reference in
```
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3
```

**Comment by devpikachu** [comment]
Ah, indeed, must have gotten the file from the wrong output directory. ConfuserEx successfully processed the file at "Maximum" preset after correcting that.

Thank you very much for your help!

Before I go ahead and close this issue, do you have an approximate ETA on when .NET Core / Standard will be officially supported?

**Comment by mkaring** [comment]
There is currently no due date. I keep working on it, but there is still quite a way to go before it's done.
