### ISSUE TITLE
Apply rename and resources at same time will cause WPF can't find resource.

### ISSUE THREAD

**Issue by icortana** [mkaring/ConfuserEx#14]
How to reproduce : 
1: Create a empty WPF project and build.
![image](https://user-images.githubusercontent.com/25761337/50065181-15247380-01f0-11e9-8caf-578a69397d1d.png)
2: Add rename and resources protection, protect.
![image](https://user-images.githubusercontent.com/25761337/50065212-384f2300-01f0-11e9-9842-7c3d0ce42ba8.png)
3: Open confused exe, the program will not open. Debug in dnspy.
![image](https://user-images.githubusercontent.com/25761337/50065280-b7dcf200-01f0-11e9-806d-616c5df85a53.png)
![image](https://user-images.githubusercontent.com/25761337/50065283-c0cdc380-01f0-11e9-8c22-bc533161da12.png)

**Comment by icortana** [comment]
Analyse:
The problem is in App.InitializeComponent().
Without rename, the Uri is replaced with `base.StartupUri = new Uri("/WpfTest1;component/pwmbztdrlbpswnsxzxohviwimqpb.xaml", UriKind.Relative);`
After using rename, the Uri is `base.StartupUri = new Uri("MainWindow.xaml", UriKind.Relative);`

The reason is the regex :
ConfuserEx\Confuser.Renamer\Analyzers\WPFAnalyzer.cs Line 21
![image](https://user-images.githubusercontent.com/25761337/50067617-a3065b80-01fc-11e9-8e0c-ad039f18fe60.png)
ConfuserEx\Confuser.Renamer\Analyzers\WPFAnalyzer.cs Line 184
![image](https://user-images.githubusercontent.com/25761337/50067691-0d1f0080-01fd-11e9-920f-f13adc7cfd92.png)

**Comment by icortana** [comment]
Solution : 
ConfuserEx\Confuser.Renamer\BAML\BAMLAnalyzer.cs
![image](https://user-images.githubusercontent.com/25761337/50069033-32167200-0203-11e9-8bc8-a86d974f63ff.png)
ConfuserEx\Confuser.Renamer\Analyzers\WPFAnalyzer.cs
![image](https://user-images.githubusercontent.com/25761337/50069050-478b9c00-0203-11e9-894e-bbfc5b01aea6.png)

The resharper is pretty good :)
![image](https://user-images.githubusercontent.com/25761337/50069075-67bb5b00-0203-11e9-85c2-a6a7bf5b01ab.png)

**Comment by mkaring** [comment]
Thank you for your report. 👍 
I am also gladly accepting pull requests. :wink: Just saying.

Once the build is done the new binary will be here:
https://ci.appveyor.com/project/mkaring/confuserex/builds/21068736/artifacts

Please confirm that this fixes the problem.

**Comment by icortana** [comment]
Thank you, it worked very well. Any thought on KoiVM? https://github.com/Loksie/KoiVM-Virtualization

**Comment by mkaring** [comment]
I keep track of this repository, but as for right now I am not a big fan of it. It introduces a lot of incompatibilities and all kinds of performance problems. On the other hand it is relatively easy to remove again by an deobfuscator, if it recognises the KoiVM.

I'll keep an eye on the repository and see if and how the development continues.

**Comment by MurariAlex** [comment]
@mkaring Don´t forget to merge the branch with the fix to master,

**Comment by mkaring** [comment]
@MurariAlex No worries :wink:
https://github.com/mkaring/ConfuserEx/commit/3944af342129665ea5ed6a7b2b6ebcbe1352664e
