### ISSUE TITLE
ConfuserEx adds junk reference, making DLL unusable.

### ISSUE THREAD

**Issue by KatDevsGames** [mkaring/ConfuserEx#143]
Even with protections seemingly off, ConfuserEx adds a junk reference of random characters to a DLL. This mysterious unknown reference causes the DLL to be unusable (can't be resolved by the runtime). Removing the reference in dnSpy and resaving the assembly fixes the problem. I do not like having to manually remove the reference as a post-step. While this may be a "feature" to someone, the inability to disable it is most assuredly a BUG. Please fix.

**Comment by ElektroKill** [comment]
This might be the dll generated by the resource protection. From what I understand you just drag dropped the file to the ui and went to protect tab to process it without any rules. In that case this must be a bug that the reference is added.

**Comment by mkaring** [comment]
I can't reproduce the issue you are describing. When disabling all the protections, ConfuserEx just adds the watermark and is done.

Could you please attach the Confuser project file you are using and specify the exact version of ConfuserEx?

**Comment by KatDevsGames** [comment]
I actually think it may be something in the normal and not the minimum setting. The preset documentation is very sparse. This has something to do with the embedded resource obfuscation it seems? I have at minimum been finally able to disable it.

**Comment by KatDevsGames** [comment]
OK. So the DLL is post-strongnamed by another actor. The junk reference that gets added doesn't have a public key or strong name and makes it fail to load when the final assembly (with a strong name) loads this reference that has no public key.

**Comment by ElektroKill** [comment]
When you use presets ConfuserEx automatically adds protections for that preset. Resource protection is part of the normal preset. That’s why your dll is added. However I don’t know why it’s not properly signed.
