### ISSUE TITLE
Incorrect redirecting assembly to the GAC

### ISSUE THREAD

**Issue by GeorgeAlexandria** [mkaring/ConfuserEx#144]
Hello,

I'm try to use **ConfuserEx 1.3.1** and I found that it makes redirect to an assembly from the GAC, when the really used assembly is located in the one of `probPath`. In my case such behavior produce an error (because the assembly from the GAC doesn't contain a couple of types).

```
 [INFO] Confuser.Core 1.3.1+cf4240c129 Copyright © 2014 Ki, 2018 Martin Karing
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'TestConfuserEx.dll'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[ERROR] Failed to resolve a type, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: Microsoft.Build.Framework.IBuildEngine5 (Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at dnlib.DotNet.TypeRef.ResolveThrow(ModuleDef sourceModule)
   at Confuser.Renamer.VTableStorage.GetVTable(ITypeDefOrRef type)
   at Confuser.Renamer.VTable.ConstructVTable(TypeDef typeDef, VTableStorage storage)
   at Confuser.Renamer.VTableStorage.GetOrConstruct(TypeDef type)
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
[ERROR] ---BEGIN DEBUG INFO---
[ERROR] Installed Framework Versions:
[ERROR]     v4
[ERROR]     Client  4.8.03761
[ERROR]     Full  4.8.03761
[ERROR]     v4.0
[ERROR]     Client  4.0.0.0
[ERROR]     v4.5 528049
[ERROR] 
[ERROR] Cached assemblies:
[ERROR]     TestConfuserEx, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\GAlexandriya\source\repos\TestConfuserEx\TestConfuserEx\bin\Release\TestConfuserEx.dll)
[ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[ERROR]         Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[ERROR]     mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.NET\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll)
[ERROR]     Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.NET\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll)
[ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[ERROR]         System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[ERROR] ---END DEBUG INFO---
Failed at 3:43 PM, 0:00 elapsed.
``` 
Here you can see when redirection was applied in the dnlib: 
<details>
<summary>Click to expand pictures</summary>

![ConfuserEx_1](https://user-images.githubusercontent.com/13402478/82815086-148e1300-9ea1-11ea-950e-5825c569fb63.png)

![ConfuserEx_2](https://user-images.githubusercontent.com/13402478/82815085-13f57c80-9ea1-11ea-9e2e-4b6c0adbd2d7.png)

![image](https://user-images.githubusercontent.com/13402478/82815051-050eca00-9ea1-11ea-886c-f4926b61232f.png)

</details>

And [here](https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Core/ConfuserEngine.cs#L149) ConfuserEx creates `AssemblyResolver`.

It is a small project to reproduce: [TestConfuserEx.zip](https://github.com/mkaring/ConfuserEx/files/4677266/TestConfuserEx.zip)

I didn't find any params to avoid this behavior (cannot remove assemblies from the GAC) and to allow ConfuserEx gets assemblies from `probPath`. Did I miss them? If no, do you plan to add them or apply any other kind of patch?

**Comment by mkaring** [comment]
Hello,

resolving the assemblies acts up from time to time. I'll look into it, if that can be improved. In the meantime, you can force ConfuserEx to load a specific assembly, by adding it as external reference to your project file.

Changing your assembly to this should resolve your issue for now:
```xml
<project outputDir="Obfuscated" baseDir="TestConfuserEx\bin\Release" seed="789qwe" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" inherit="false">
    <protection id="anti ildasm" />
    <protection id="constants" />
    <protection id="invalid metadata" />
    <protection id="rename">
      <argument name="mode" value="decodable" />
      <!-- <argument name="renPublic" value="true" /> -->
    </protection>
  </rule>  
  <module path="TestConfuserEx.dll" />
  <module path="Microsoft.Build.Framework.dll" external="true" />
</project>
```

**Comment by GeorgeAlexandria** [comment]
Unfortunately, specifying `<module path="Microsoft.Build.Framework.dll" external="true" />` didn't change anything and redirect with error still persist.

**Comment by KvanTTT** [comment]
It seems like the similar issue exists in the original archived repository: https://github.com/yck1509/ConfuserEx/issues/521

**Comment by mkaring** [comment]
Thanks to the test created by @KvanTTT, I was able to work out of fix for the problem.

@GeorgeAlexandria: You can download a new version that fixes your issue [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/35464248/artifacts). 
Please let me know if this version works for you.

**Comment by GeorgeAlexandria** [comment]
@mkaring, sorry for the long response. Seems that the fixed version correctly handles the case in issue.
