### ISSUE TITLE
Clear up and simplify code

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#145]
* Remove unused `using` directives
* Remove unused methods and other members
* Remove unused getters and setters
* Remove unused locals and parameters
* Use expression bodies
* Make fields `readonly`
* Use var instead of full type names
* Inline out variables
* Change visibility to private/protected
* Merge cast with type check

I can do that with the help of Rider. Do you have any objections?

**Comment by mkaring** [comment]
Actually I have. Changing the code just for the sake of cleaning it up isn't really useful. In case the code is actually being worked on, cleaning the code should be done, but otherwise it shouldn't.

The reason is mainly that merging becomes much more difficult if the code is changed a lot.

**Comment by KvanTTT** [comment]
Clear.
