### ISSUE TITLE
Split release package into CLI and GUI packages

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#146]
Currently, I'm using only CLI version of ConfuserEx. That's why GUI app and related assemblies are useless for me (GalaSoft, Ookii.Dialogs, and other). Is it possible to publish the light version of Confuser together with the full package?

Also, I think description xmls (dnlib.xml, Ookii.Dialogs.Wpf.xml) can be removed as well. Because they are not needed for applications.

**Comment by mkaring** [comment]
The reason that why this is currently not done, is the minimal difference if the UI stuff is dropped. The release package is currently 1.54 MB. A build only for the CLI will be something around 1.2 MB.

Or am I missing something here?

**Comment by KvanTTT** [comment]
The size of the original unpacked package is 5.56 Mb. If .xml and .pbf files are removed then the size will be decreased to 2.62 Mb. If GUI files are removed then the size will be 2.01 Mb. So, at least xml and pdb files should be removed from the output package.

![image](https://user-images.githubusercontent.com/1150330/83403242-faa87f00-a410-11ea-88e4-9d6501bdf395.png)

But the main point is not size, but clarity. I don't like two apps in one package.

**Comment by wmjordan** [comment]
PDB and XML files are of no use for end-users.

Maybe it is possible to merge those GUI related libraries and the main GUI EXE into one EXE file with il-repack?
So the directory can be kept clean.

**Comment by mkaring** [comment]
I did setup 3 packages. GUI, CLI and the full package. The debug symbols and documentation files is stripped from all of them.

**Comment by KvanTTT** [comment]
Thanks a lot!

**Comment by wmjordan** [comment]
Oh, I did feel good after the package had been separated into two :)
...especially when the internet connection was slow. Thanks!
