### ISSUE TITLE
Detected as virus

### ISSUE THREAD

**Issue by dannythegreat** [mkaring/ConfuserEx#148]
I used this great tool, but when I scan the file with virustotal.com I have this score 5/66 (see the image link).
For me is a problem publish an app with this score. How I can solve it?

[Virustotal screenshot](https://ibb.co/Dw0JgTz)

**Comment by xHeaven** [comment]
Since it is an obfuscator, also often used to obfuscate malwares, surely some AVs will show false-positives. There is nothing you could do with it.
