### ISSUE TITLE
InvalidOperationException: Stack empty in MethodTrace.TraceArguments called by WinFormsAnalyzer

### ISSUE THREAD

**Issue by LukasTr** [mkaring/ConfuserEx#152]
I'm using Confuser.CLI version 1.3.1 on an existing application. This is the assembly-wide configuration:

`[assembly:Obfuscation(Exclude =false, Feature = "preset(normal);-ctrl flow;-ref proxy;+rename(mode=reversible,password=12345,flatten=false);")]`

This is the output I'm getting:

> >z:\tools\ConfuserEx\Confuser.CLI.exe application.exe -o=.
>  [INFO] Confuser.Core 1.3.1+cf4240c129 Copyright © 2014 Ki, 2018 Martin Karing
>  [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 32 bits
> [DEBUG] Discovering plugins...
>  [INFO] Discovered 10 protections, 1 packers.
> [DEBUG] Resolving component dependency...
>  [INFO] Loading input modules...
>  [INFO] Loading 'application.exe'...
>  [INFO] Initializing...
> [DEBUG] Building pipeline...
>  [INFO] Resolving dependencies...
> [DEBUG] Checking Strong Name...
> [DEBUG] Creating global .cctors...
> [DEBUG] Watermarking...
> [DEBUG] Executing 'Name analysis' phase...
> [DEBUG] Building VTables & identifier list...
> [DEBUG] Analyzing...
> [DEBUG] WinForms found, enabling compatibility.
> [DEBUG] Newtonsoft.Json found, enabling compatibility.
> [ERROR] Unknown error occurred.
> Exception: System.InvalidOperationException: Stack empty.
>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.Stack`1.Pop()
>    at Confuser.Core.Services.MethodTrace.TraceArguments(Instruction instr)
>    at Confuser.Renamer.Analyzers.WinFormsAnalyzer.AnalyzeMethod(ConfuserContext context, INameService service, MethodDef method)
>    at Confuser.Renamer.Analyzers.WinFormsAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def)
>    at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer)
>    at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters)
>    at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
>    at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
>    at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
> Failed at 12:53, 0:04 elapsed.

Is this a known problem? I will send the exe in a private e-mail.

**Comment by mkaring** [comment]
The issue looks familiar. Could be the one fixed by #127 
Could you please try to use the version from the buildserver for the next release?
Find the download [here][0].

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/32784369/artifacts

**Comment by LukasTr** [comment]
Thank you, I confirm this problem is fixed in the newer build you linked.
