### ISSUE TITLE
Control flow protection issue

### ISSUE THREAD

**Issue by ElektroKill** [mkaring/ConfuserEx#153]
Hello,
Before protection, the file shows OK in the console.
After protection, it gets stuck in an infinite loop and doesn't show OK.

I am using the latest release.

[test.zip](https://github.com/mkaring/ConfuserEx/files/4806004/test.zip)

**Comment by KvanTTT** [comment]
I think it's better to add the minimum sample of source code that depicts such a problem instead of exe.

**Comment by mkaring** [comment]
The test file is okay. I'm able to reproduce the issue and I got a fairly good idea what the problem is.

**Comment by mkaring** [comment]
@ElektroKill: I found and fixed the issue.
You can find the fixed build [here][0].

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/33649145/artifacts
