### ISSUE TITLE
How to avoid unpacker?

### ISSUE THREAD

**Issue by ryancheung** [mkaring/ConfuserEx#156]
I unpacked a ConfuserEx packed game client with:

https://www.youtube.com/watch?v=NZgpm3GmnBs

Is there any way to avoid it?

**Comment by ElektroKill** [comment]
Use 2.0 version of ConfuserEx with a different compression mode.

**Comment by ryancheung** [comment]
Got it, thanks! I'll test it and then give some feedback.

**Comment by JohnRanger** [comment]
Hi @ElektroKill ,

I have downloaded the newest master of ConfuserEx and compiled it (shows core 1.5.0-alpha). 

Used it with all options (the ones which do not produce a startable exe I left off).

Was no problem to un-confuse it with your newest version of the unpacker. I really would like to protect one of my specific apps against reverse engineering :-)

I also do only see 1 packer - the standard packer. But you mention above that we should use a different packer method.

Is there any newer version of ConfuserEx, which your unpacker cannot reverse-engineer - as of 2020-10-12? :-)

With kind regards,

John

**Comment by ElektroKill** [comment]
@JohnRanger I would suggest the following:
* if you want to remain on master branch 1.x, then I recommend you enable the hardening protection, also on the project file make sure to change the mode of protections to dynamic.
* if you would like to try and use the 2.0 branch I recommend changing the data compression option used by the compression service to sth different then lzma.

**Comment by mkaring** [comment]
Guess that question is answered.
