### ISSUE TITLE
Update projects framework version

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#159]
The version of the current net framework 4.6.1 was announced on 2015 year. It's an outdated framework. I suggest updating to the version 4.7.2 or 4.8. Maybe even consider netcore3.1?

**Comment by mkaring** [comment]
Is there any major advantage in compiling against a newer version of the .NET Framework? The application runs with the latest Framework version >= 4.6.1 that is installed on the system anyway.

**Comment by SlackingVeteran** [comment]
Honestly I still like to use 4.6.1 unless I need something specific from netcore 3.1.
However I'd love to see the support for .netcore 3.1. I think based on our testing few days ago it currently does not work with .net 3.1 (even 3.0)

**Comment by KvanTTT** [comment]
> However I'd love to see the support for .netcore 3.1. I think based on our testing few days ago it currently does not work with .net 3.1 (even 3.0)

There is a difference between runtime framework and projects that ConfuserEx can process.
