### ISSUE TITLE
Control flow obfuscation broken in 1.4

### ISSUE THREAD

**Issue by mkaring** [mkaring/ConfuserEx#162]
The control flow obfuscation appears to be broken in ConfuserEx 1.4.

**Comment by mkaring** [comment]
The issue is likely related to #153. The fix in this issue correctly resolved the issue that broke the control flow obfuscation in specific optimized loops. How ever it opened up many cases where the obfuscation was able to do relative jump instructions between the blocks.
Fixing this issue seems to have cleared the way for another issue that is somewhere in this protection.
The problem is that I don't have a unit test, an example or a clear idea of what is going wrong.

All I can do so far is restore the behavior of before #153 was fixed, excluding the bug that was actually fixed in this issue.

**Comment by mkaring** [comment]
There is a build now that should work around the issue. [Download it here][0]

[0]: https://ci.appveyor.com/project/mkaring/confuserex/builds/33980958/artifacts

**Comment by mkaring** [comment]
The issue is fixed with this change and the fix is confirmed by @wmjordan and @KvanTTT. The capabilities of the control flow obfuscation are severely limited due to this change. Fixing this properly needs to be done with the next release.

**Comment by wmjordan** [comment]
@mkaring  I suggest you post a beta thread like [this project run by me](https://github.com/wmjordan/Codist/issues/118), before public release. So, we can test the integrated application a little better.

**Comment by mkaring** [comment]
@wmjordan: Henceforth I'll create release candidates for the major releases, so the releases can get a wider test run.

**Comment by ElektroKill** [comment]
Is there a test file available to reproduce this issue? I would want to take a look at it.
