### ISSUE TITLE
Conditional control flow obfuscation?

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#165]
The control flow obfuscation works best when a method is complicated.
For short methods, it does not help protection but to slow down the application.

For instance, it is too easy to unobfuscate the following lines to `if (_A._B) { A_0._C(A_1); } ` without noticeable effort from a method having two arguments `A_0` and `A_1`:

````C#
if (_A._B)
{
	for (;;)
	{
		IL_07:
		uint num = 3043685623U;
		for (;;)
		{
			uint num2;
			switch ((num2 = (num ^ 2741728449U)) % 3U)
			{
			case 0U:
				goto IL_07;
			case 1U:
				A_0._C(A_1);
				num = (num2 * 2268335228U ^ 4268601416U);
				continue;
			}
			goto Block_1;
		}
	}
	Block_1:;
}
````

It is also too easy to manually unobfuscate the following pattern to `enumerator?.Dispose();` (so obviously it is at the end of a `foreach` statement)

````C#
if (enumerator != null)
{
	for (;;)
	{
		IL_102:
		uint num5 = 1459511321U;
		for (;;)
		{
			uint num3;
			switch ((num3 = (num5 ^ 1897414001U)) % 3U)
			{
			case 0U:
				goto IL_102;
			case 1U:
				enumerator.Dispose();
				num5 = (num3 * 3870471142U ^ 1357864364U);
				continue;
			}
			goto Block_8;
		}
	}
	Block_8:;
}
````

Thus I suggest skip the control flow obfuscation when a method is too small, or a pattern is too commonly used.

**Comment by mkaring** [comment]
I don't see any major advantage in disabling the obfuscation even for simple pattern. So what if you can read what is happening there?
#285 may give you some more control over this, once it's implemented. But disabling the the protection because it guesses that the pattern is too simple, won't be implemented.
