### ISSUE TITLE
DoubleClick to edit rule ou project item

### ISSUE THREAD

**Issue by digocesar** [mkaring/ConfuserEx#174]
Something that frustrates me about ConfuserEx is having to select the project or rule in the list and then click on "Edit". It would be much simpler to double-click on the list item to open it for editing.
I tried to contribute to the project by doing this implementation but I couldn't find a way to double click on XAML using the MVVM model. Sorry! :(

**Comment by mkaring** [comment]
That should be relatively easy to do. I'll include that in the next version.
