### ISSUE TITLE
v1.4.1 silent crash

### ISSUE THREAD

**Issue by d2k2-git** [mkaring/ConfuserEx#175]
some users of my application reported me that its crashing silently since i updated confuserEx from 1.4.0 to 1.4.1.  the process just exits without errors, which is unusual, since i catch all execeptions in running threads. so i suspect the packer/protector.

the exe is only compressed without any rules.

i switched back to 1.4.0 to monitor this problem. if its crashing again on 1.4.0 you can close this issue and i have to search for another cause. i will update this as soon i know more.

**Comment by mkaring** [comment]
Do you see the crash of the application in the event log of windows? If so you could enable WER to create a memory dump upon the crash. That may give some insight to the problem.

**Comment by d2k2-git** [comment]
thx for your fast answer. you can close this issue. the crash seem to be related to direct2d exceptions. still did not figure it out. but does not seem to be caused by ConfuserEx.
