### ISSUE TITLE
Memory issue when using ConfuserEx

### ISSUE THREAD

**Issue by leminhthanh1998** [mkaring/ConfuserEx#176]
Hi,
I'm using ConfuserEx to protect my source code and it was very good!
But it has problems about memory usage, without ConfuserEx, my app only takes about 100 MB of RAM, however, if used with ConfuserEx it takes up to 200 MB of RAM.
Is there any way to reduce RAM usage? I already add GC.Collect() at app.xaml.cs but it not works for me.
Best regards!

**Comment by xHeaven** [comment]
That is the cost of obfuscation. Anyway, +100MB RAM usage shouldn't be a problem in 2020.

**Comment by leminhthanh1998** [comment]
Thanks, I think I can close this issue 😄

**Comment by jkarpio** [comment]
100 MB es nothing ok modern computers, is the price of obfuscation
