### ISSUE TITLE
Bad Image

### ISSUE THREAD

**Issue by mPremraj** [mkaring/ConfuserEx#179]
Tried to Use with Dot Net core 3.1 i'm getting the following issue

 [INFO] Confuser.Core 1.4.1+5d92e25e43 Copyright © 2014 Ki, 2018 Martin Karing
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 12 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
[ERROR] Unknown error occurred.
Exception: System.BadImageFormatException: .NET data directory RVA is 0
   at dnlib.DotNet.MD.MetadataFactory.Create(IPEImage peImage, Boolean verify)
   at dnlib.DotNet.MD.MetadataFactory.Load(String fileName)
   at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
Failed at 01:43, 0:00 elapsed.

**Comment by mkaring** [comment]
This is the first time I have seen an error like this. Is there anything special with your assembly going on? Please do note that ConfuserEx is only working up to .NET Core 2.2. .NET Core 3.1 was not tested successfully yet.

**Comment by Smurf-IV** [comment]
The above is thrown on the **exe** that is generated from .NetCore3.x

**Comment by mkaring** [comment]
This error appears if the assembly referenced isn't a .NET assembly. Upcoming version of ConfuserEx will show a better error message for this case.

**Comment by codingdave** [comment]
Hi,

I can confirm that with `6442a62` an executable compiled with TargetFramework net5.0-windows leads to
    [ERROR] Failed to load "MyApplication.exe" - Assembly does not appear to be a .NET assembly.
    Failed at 12:18, 0:00 elapsed.

Running debug I can see ObfAttrMarker.cs:324 {".NET data directory RVA is 0"}, however this exception does not get logged due to ConfuserEngine.cs:200

https://github.com/mkaring/ConfuserEx/pull/300
