### ISSUE TITLE
[Question] Rename Assembly Variable is supported ?

### ISSUE THREAD

**Issue by graysuit** [mkaring/ConfuserEx#180]
I want to protect my code from reverse engineering,
You know d4dot can de compile confuser easily,
And also recover all things including variable name,
All coders know variable names help a lot in reverse engineering.

**Lets suppose my code is**
```
public static class Code
{
    public static void main()
    {
        string code;
        string assembly;
        string confuser;
        string renamer;
    }
}

```
**Now I want confuser to rename it as like**
```
public static class Code
{
    public static void main()
    {
        string a1;
        string b2;
        string c3;
        string d4;
    }
}

```
This type of variable renaming is also used by pro gaurd,
By using this renaming will make code to not recoverable,
As you know original author know everything about his code,
But it will make impossible to de confuse.

You can generate sequence based variable name using this class
```
using System;

public static class a
{
    public static void main()
    {
        while (true)
            Console.writeline(SequenceRandom());
    }

    private static int i = 0;
    private static int SelectedAlphabet = 0;
    private static string[] Alphabets = new[] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z" };


    private static string SequenceRandom()
    {
        if (i == 10)
        {
            i = 0;
            SelectedAlphabet += 1;
        }

        if (SelectedAlphabet >= Alphabets.count())
            SelectedAlphabet = 0;
        i += 1;
        return Alphabets[SelectedAlphabet] + i;
    }
}

```
See the line no ``` if (i == 10)``` 
This will result in something like
```
a1
a2
a3
a4
a5
a6
a7
a8
a9
a10
b1
b2
b3
b4
b5
b6
b7
b8
b9
b10

**Comment by mkaring** [comment]
Private variables are already renamed as part of the `rename` protection. That can't be reversed by de4dot. It will do some guess work names that are more easily readable (like `string1`  or something like this), but it can't restore the original names.

**Comment by graysuit** [comment]
great ! I tested it
You are right that confuser can rename private variables 
dnspy showing like  ```string_0, string_1, string_2``` 

Okay 1 more question
Where do I make confuser to rename variable names according to my choice?

**Comment by mkaring** [comment]
[This line][1] handles the renaming of fields and properties. You can check if the `def` is a `FieldDef` and modify the renaming as you see fit.

[1]: https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Renamer/RenamePhase.cs#L108

**Comment by graysuit** [comment]
Hi Thanks. It really helpful. But I have trouble while compiling. It has a lot of nuget dependencies. Isnt any minimal repo anyhwhere of confuser ?
