### ISSUE TITLE
Obfuscate project binaries with dlls from dependency (nuget package)

### ISSUE THREAD

**Issue by michalciolek** [mkaring/ConfuserEx#181]
I would like to obfuscate my project with dependent dlls files (from nuget) using Confuser MsBuild Target 1.4.1.

In crproj i add some dll from Nuget eg.:
```
<module path="Newtonsoft.Json.dll" />
```

But during build I get:
```
An IO error occurred, check if all input/output locations are readable/writable.
Could not open file C:\**\testproj\obj\Debug\Newtonsoft.Json.dll for reading. Error: 00000002"
```

When I use ConfuserEx from CLI/GUI everything works perfect.

**Comment by mkaring** [comment]
This is not going to work with the msbuild package right now. The obfuscation is triggered before the dependencies are copied to the output. You can only obfuscate the assembly that is created by the project you are building.
