### ISSUE TITLE
Wiki is missing information about the 'harden' protection, and watermark

### ISSUE THREAD

**Issue by griknok** [mkaring/ConfuserEx#183]
In the GUI there is "Protection Hardening" but I can't read the description text because only the first few words are visible before...

Adding the protection creates `<protection id="harden"/>` in the project, are there any additional arguments I can use? Wiki doesn't mention this protection.

Watermark is also missing from the Wiki

**Comment by mkaring** [comment]
I added the information for both protections to the wiki.
Does this clear things up?

**Comment by griknok** [comment]
Yes it's good that they are in the wiki's protections list now, because they appear in the GUI. The description for Hardening is still a bit vague, but I guess if it "enhances the runtime code" I will use it, because that sounds good 😅

**Comment by mkaring** [comment]
I may need to improve on that at a later time. The `harden` protection only works on the code that is added by ConfuserEx. Basically that is the code that handles the different `anti`-protections, the `constants` protection, and so on. These protection have to execute some code once the assembly is loaded, for .NET to execute the assembly properly. This code that is executed at the start is improved and made more difficult to modify by the `harden` protection.

The protection is safe to be enabled and as written in the documentation, part of the `minimal` preset.
