### ISSUE TITLE
Control flow type "jump" prevents winforms executable from launching

### ISSUE THREAD

**Issue by griknok** [mkaring/ConfuserEx#184]
ConfuserEx 1.4.1 with .NET 4.7.2 Winforms single executable.
Project only contains the control flow protection with type 'jump':
`<protection id="ctrl flow">
  <argument name="type" value="jump" />
</protection>`

But application will not launch

**Comment by mkaring** [comment]
The `jump` control flow obfuscation is covered by the same unit tests as the `switch` version. I am guessing this is a specific problem. Are you able to create a minimal working example you could provide, or provide the protected version of the affected assembly?

**Comment by griknok** [comment]
I spent hours trying to narrow down the cause! (typical programming problem I guess...) I could not reproduce this by creating a new project, but only by reducing an existing project to almost nothing and rebuilding the release each time. Anyway here is a working executable and after ConfuserEx 1.4.1 has run the "jump" control flow (project included in .7z) the obfucated exe doesn't launch.
[my weird broken exe](https://www.dropbox.com/s/4ne8wtc6ji07gae/ConfuserExExamples.7z?dl=1)

**Comment by griknok** [comment]
After several hours... I finally found it! [Here is the source](https://www.dropbox.com/s/a9pj8hogp8e3686/ConfuserExExamples2.7z?dl=1)

All you need to do to create a project which breaks control flow "jump":
1. Create a C# Winforms app with .NET 4.7.2
2. Put two buttons on the form
3. Create a Click event handler on the first button, i.e. `this.button1.Click += new System.EventHandler(this.button1_Click);`
4. Set the Click event handler for the second button to the same EventHandler, i.e. `this.button2.Click += new System.EventHandler(this.button1_Click);`
5. Run a release build, the run ConfuserEx 1.4.1 on the exe with the only the control flow "jump" protection, i.e. `<protection id="ctrl flow"> <argument name="type" value="jump" /> </protection>`
Confused exe won't launch!

**Comment by mkaring** [comment]
I'm still on this issue. For some reason the Jump control flow obfuscation causes at times a single instruction to be duplicated. I'm still working on this one.

**Comment by griknok** [comment]
All good! 👍
In your opinion, is the spaghetti code produced by 'jump' much harder to follow/deobfuscate than switch? I would expect it also to be less performant?

**Comment by mkaring** [comment]
I found the code produced by the Jump mangler to be slightly better in matters of performance but significantly worse when it comes to it's obfuscation strength. Even the ILSpy code that creates C# from MSIL code is basically reverting the obfuscation of the Jump mangler.

How ever, I got a couple of ideas to significantly improve the obfuscation of the Jump mangler at the cost of reducing the runtime performance to about the level as the switch mangler. Got those ideas while trying to find this issue.

**Comment by mkaring** [comment]
I finally found and fixed the issue. I wonder how anyone is using the jump mangler …
You can download the build with the fix [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/36989429/artifacts).

It would be great if you could test it with your project and see if that fixes it for you in your project.
