### ISSUE TITLE
TypeLoadException is thrown in complicated cases with inheritance if renPublic=true and several assemblies are involved

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#187]
Consider the main assembly **SignatureMismatch2**:

```cs
using System;
using SignatureMismatch2Helper;

namespace SignatureMismatch {
	public interface IInterface
	{
		void Method(External obj);
	}

	public class Class : IInterface
	{
		public void Method(External obj) => Console.WriteLine(obj.Name);
	}

	public class Program {
		static int Main(string[] args) {
			Console.WriteLine("START");
			new Class().Method(new External());
			Console.WriteLine("END");

			return 42;
		}
	}
}
```

And the helper assembly **SignatureMismatch2Helper**:

```cs
namespace SignatureMismatch2Helper {
	public class External
	{
		public virtual string Name => "External";
	}
}
```

When I'm trying to apply renaming obfusctation with `renPublic=true` the following exception is being thrown:

```
Unhandled Exception: System.TypeLoadException: Signature of the body and declaration in a method implementation do not match.  Type: '?????????????????????????????????????????'.  Assembly: 'SignatureMismatch2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ?????????????????????????????????????????.?????????????????????????????????????????(String[] )
```

Instead of correct output.

It seems to me this is because of missing obfuscation of `External` type in `IInterface.Method(External)` signature:

```cs
void \u202A\u206D\u206E\u206E\u202A\u206B\u200D\u206F\u200C\u200B\u206F\u202D\u200B\u206F\u200E\u206E\u206C\u206F\u206B\u202C\u202A\u206F\u200D\u200E\u202E\u200B\u206D\u206E\u202A\u206E\u206E\u206A\u200B\u200B\u206F\u200D\u206E\u206D\u202B\u202E\u202E(External);
```

The signature of the implementation class `Class.Method(External)` is being transformed correctly:

```cs
public void \u202A\u206D\u206E\u206E\u202A\u206B\u200D\u206F\u200C\u200B\u206F\u202D\u200B\u206F\u200E\u206E\u206C\u206F\u206B\u202C\u202A\u206F\u200D\u200E\u202E\u200B\u206D\u206E\u202A\u206E\u206E\u206A\u200B\u200B\u206F\u200D\u206E\u206D\u202B\u202E\u202E(\u200D\u206B\u206B\u202D\u202E\u206D\u206E\u200E\u206B\u206E\u202D\u206F\u200F\u202C\u200E\u206A\u202B\u200C\u206B\u202B\u206A\u202E\u200E\u200D\u202E\u206E\u200B\u200E\u200C\u206A\u200E\u206D\u206F\u200D\u202D\u202C\u206F\u202A\u206F\u200C\u202E A_1)
{
	Console.WriteLine(A_1.\u206F\u202C\u202B\u200F\u200C\u206A\u200F\u206E\u206E\u206B\u202C\u200D\u206D\u200F\u200E\u200E\u202D\u206B\u202D\u206D\u206F\u200B\u202A\u200C\u200C\u206B\u200E\u200F\u206D\u206D\u206D\u206F\u206D\u202B\u200B\u202E\u200F\u200E\u202E\u202B\u202E);
}
```

**Comment by mkaring** [comment]
I found the cause if this issue. The problem is that the type reference in the overwrite signature is not fixed during the renaming. The only time this happens is in case an method in another assembly is overwritten that is still being renamed.

**Comment by KvanTTT** [comment]
Any change to fix it?

**Comment by mkaring** [comment]
Yes. There is a single line that this causing the issue. [This one](https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Renamer/Analyzers/VTableAnalyzer.cs#L285). If I disable it or only execute it if the modules do not match everything works fine. But I am not sure why this line is required at all. I need to think about the implications of removing it (conditionally).

The reason this is a problem is that it creates a duplicated `TypeRef` entry for the `External` type, when it processes the overwrite directives for the type.

**Comment by mkaring** [comment]
Okay I am certain that the line is completely useless. If the import is required, it's already done at this point.

The bigger issue here is that the `VTableAnalyzer` modifies that assembly during the analysis phase. This causes all sorts of issues, because it requires that this analyzer is executed first to cause no issues. This is not the case currently.

To avoid any further issues in the future, this analyzer must not alter the assembly during the analysis phase.

**Comment by KvanTTT** [comment]
Now everything related to obfuscation works as expected in my job project, big thanks!
