### ISSUE TITLE
Add some options to allow exclude renaming Types, Properties, Fields etc. when renaming.

### ISSUE THREAD

**Issue by alpakeno** [mkaring/ConfuserEx#191]
This option is necessary since renaming all will cause some applications to not working properly and throwing errors.
Which the only way is to remove the renaming rule option in order to make the application to work correctly.

**Comment by mkaring** [comment]
You can disable the `rename` protection for individual types and members as you see fit. That should allow you to disable this protection for exactly the types you don't want renamed.

There is an example for that in the wiki in the documentation for the [`rename` protection](https://github.com/mkaring/ConfuserEx/wiki/Name-Protection#example). You find the different expressions you can use in the rules [here](https://github.com/mkaring/ConfuserEx/wiki/Expression-Functions).

**Comment by alpakeno** [comment]
I see, but how to exclude specific type when using renPublic?
Like when I enable it, all forms will be renamed, else it will not.

**Comment by mkaring** [comment]
You can simply disable the renaming protection for the specific type or the specific method you don't want protected.

For example you have a type like this:
```c#
namespace MyNamespace {
  public class MyType { 
    public void MyMethod() {}
  }
}
```

In the project file for ConfuserEx (`*.crproj`) you have most likely a rule that enables the renaming and it's parameters for the entirety of the project. If you want to disable the renaming rule for the type mentioned above, you can create a new rule that affects only this type.

```xml
<rule pattern="full-name('MyNamespace.MyType')">
  <protection id="rename" action="remove">
</rule>
```

This would disable the renaming for this type completely. Same works for a method like this for an example.

```xml
<rule pattern="decl-type('MyNamespace.MyType') and name('MyMethod')">
  <protection id="rename" action="remove">
</rule>
```

You could also modify the parameters of the protection for the type to disable the public renaming for example. This would have the effect that the public type and all it's public members remain untouched. For example like so:

```xml
<rule pattern="full-name('MyNamespace.MyType')">
  <protection id="rename">
    <argument name="renPublic" value="false" />
  </protection>
</rule>
```

You can add as many of those rules as you like. They are evaluated one after another and the parameters that take effect are the aggregation of all rules that are active for the member that is being processed.

**Comment by alpakeno** [comment]
Thank you for the clarifications, it solved my base issue :+1: 

While testing, I have encountered an issue when trying to use:

`<rule pattern="decl-type('MyNamespace.MyType') and name('MyMethod')">
      <protection id="rename" action="remove">
</rule>`

or

`<rule pattern="decl-type('MyNamespace.MyType')">
      <protection id="rename" action="remove">
</rule>`

It says "invalid project!" when importing the project file.

**Comment by mkaring** [comment]
Yes. It's an XML file. You have to close the tags.

Either this way:
```xml
<rule pattern="decl-type('MyNamespace.MyType') and name('MyMethod')">
  <protection id="rename" action="remove" />
</rule>
```

or this way:
```xml
<rule pattern="decl-type('MyNamespace.MyType') and name('MyMethod')">
  <protection id="rename" action="remove"></protection>
</rule>
```

**Comment by alpakeno** [comment]
That's right! thank you for your help and your excellent clarifications :+1: 
The issue is now solved :100:
