### ISSUE TITLE
rename-Library

### ISSUE THREAD

**Issue by logicchild0x00** [mkaring/ConfuserEx#195]
Hi, it's great to add a protection called 'rename-Library', in this protection, all **public** classes/methods/properties/fields will be untouched, don't rename these, this case is useful when working with **plugins**, those public members names need to be the same/unchanged.

**Comment by mkaring** [comment]
As of 1.4.1 this is the default behavior for assemblies that are not executable. For executable assemblies renaming of public types and members is enabled by default.

If the default is not to your liking, you can easily change it using the `renPublic` parameter of the `rename` protection. Please have a look at [the wiki page for the `rename` protection](https://github.com/mkaring/ConfuserEx/wiki/Name-Protection).
