### ISSUE TITLE
Update dnlib and use nuget package instead of submodule

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#208]
I've encouraged the problem [unknown custom debug info](https://github.com/0xd4d/dnlib/issues/386) that will be fixed in the following release nuget version.

Also, what's the meaning of using submodule instead of package? The last one is easier to use.

**Comment by mkaring** [comment]
I'm backporting the changes from the `release/2.0` branch to the `master` branch for the dnlib switch to nuget.
