### ISSUE TITLE
Declarative obfuscation is broken / not backwards compatible.

### ISSUE THREAD

**Issue by SteffanDonal** [mkaring/ConfuserEx#21]
Hey!

Thanks for maintaining the project.
I've just run into an issue whilst migrating to this fork - we make heavy use of declarative obfuscation in our projects and found that this version throws a parsing error for our use case:

Broken:
```cs
preset(aggressive);+rename(mode=decodable)
```

Working:
```cs
false:preset(aggressive);+rename(mode=decodable)
```

I found out how to do this by looking at the feature match regex. Putting that colon in pushes the protection string into another capture group. I then checked the pattern parser's lexer to find a good value to use here, and `false` turns out to be a noop.

**Comment by mkaring** [comment]
Good catch. I fixed the issue. It would be nice if you could test it and get back to me if it works for you now.

**Comment by mkaring** [comment]
No further feedback. It works for the provided example and the change referenced in this ticket.
