### ISSUE TITLE
how to obfuscate generated log

### ISSUE THREAD

**Issue by kushalsaha** [mkaring/ConfuserEx#211]
I would like to obfuscate my solution project which is dependent on 5 different project as well as dependent dlls files (from nuget) using Confuser MsBuild Target 1.4.1.
and am getting below error :- 
**An IO error occurred, check if all input/output locations are readable/writable.
Could not open file C:\**\kushal\obj\Debug\Project_1 A.dll for reading. Error: 00000002".
Could copy the file 'obj\Debug\confused'\Project_2 B.dll' because it was not found.**

project structure:-
Project_1  A 
Project_2  B 
Project _3 C 
Project_4  D 
Project_5  E 

Project_2  B  is our soultion project which is dependent and having references of all other project like Project_1  A, Project _3 C, Project_4  D , Project_5  E .

Followed all steps and created *.crproj file and also reffered issue no #59 ( https://github.com/mkaring/ConfuserEx/issues/59) and i tried 1.3.1 also but build is still failing.

By using ConfuserEx from CLI/GUI everything works perfect.  (Confuser.CLI.exe *.crproj) => working perfect

My requirement is as i click for rebuild solution, i should get Obfuscated dll so that we can wrap this obfuscated dll and create an automatic deployment build using jenkins

**Comment by kushalsaha** [comment]
tried all possible sceanrio :- 
<PackageReference Include="Confuser.MSBuild" Version="1.4.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>


<PackageReference Include="Confuser.MSBuild" Version="1.3.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>

**Comment by mkaring** [comment]
I'm using the MSBuild integration in the very same way without any issues like this. The obfuscation using the msbuild task runs for each project separately. Meaning only the assembly produced by the project is being subject to the obfuscation.

Maybe there is a problem with your Confuser project file. Could you share this one?

**Comment by kushalsaha** [comment]
Ok I understood, you mean in my case Project_2 B is a solution project, so using MS build confuser only Project_2 B will be obfuscated .

But my query is i need to obfuscate all Project_1 A, Project _3 C, Project_4 D , Project_5 E  from Project_2 B. and i need all project Project_1 A, Project _3 C, Project_4 D , Project_5 E, Project_2 B to be get obfuscated, total 6 obfuscated file requried by running one solution file  Project_2 B.

**Comment by mkaring** [comment]
There is a difference between a solution and a project. A solution does not get obfuscated. If you want a project to have a obfuscated output you need to add the ConfuserEx MSBuild task to that project. This will mean that only the output of this project will be obfuscated.

If you need two projects to have a obfuscated output, you need to add the ConfuserEx msbuild reference to both of them. In that case both of them will get obfuscated individually. When building all your projects, all of them will produce obfuscated assemblies in case you add ConfuserEx to all of them.

**Comment by kushalsaha** [comment]
ok @mkaring let me try.... really thank u for your support and guidence

**Comment by kushalsaha** [comment]
@mkaring currently.. log is not getting obfuscated.. is there any way so that log generated in log file can be obfuscated

**Comment by kushalsaha** [comment]
please guide me with the solution is there any way to 
obfuscate generated log and what parameter need to add in crproj file so that obfuscated dll should not get de-obfuscated

**Comment by mkaring** [comment]
1. What log are you talking about? The stack trace or something? This would be obfuscated in case you  enable the name protection.
2. No. That is the point of the obfuscation. You can't revert it. You can choose a renaming mode that is reversible by a mapping file or a password. You'll find some instructions on that in the wiki of ConfuserEx and the ConfuserEx application contains a stack trace decoder for either case.

**Comment by kushalsaha** [comment]
our requirement is to obfuscate log stacktrace, and obfuscated log stack trace should be deobfuscated so that we can can resolve the exception that occured while system/application running.
Can you please help, we are stuck in implementation
Thanking you in advance!

**Comment by kushalsaha** [comment]
> 1. What log are you talking about? The stack trace or something? This would be obfuscated in case you  enable the name protection.
> 2. No. That is the point of the obfuscation. You can't revert it. You can choose a renaming mode that is reversible by a mapping file or a password. You'll find some instructions on that in the wiki of ConfuserEx and the ConfuserEx application contains a stack trace decoder for either case.

this is my .crproj file
<project   baseDir="../Common/bin" outputDir="../bin" xmlns="http://confuser.codeplex.com">
    <rule preset="none" pattern="true" inherit="false">
        <protection id="anti dump" />
		<protection id="anti ildasm" />
		<protection id="anti tamper" />
		<protection id="constants" />
		<protection id="ctrl flow" />
		<protection id="ref proxy" />
		<protection id="rename" />
    </rule>
  <module path="Common.dll" />
</project>

used **name protection** but log stack trace is not getting obfuscated

**Comment by KvanTTT** [comment]
It seems like obfuscation is not working at all in your case. Can you try to obfuscate your app using CLI version?

> implementing renaming mode that is reversible by a mapping file or a password.

You have to use `decodable` renaming mode, see the wiki: https://github.com/mkaring/ConfuserEx/wiki/Name-Protection

**Comment by mkaring** [comment]
This is very strange. Are you absolutely sure that the types are subject to obfuscation? There are a couple of reasons why the types would not get renamed. For example in case they are `public` or in case they are `internal` and you are using the `InternalsVisibleToAttribute`. Could anything like his be the reason for the issue in your case?

**Comment by kushalsaha** [comment]
@KvanTTT  @mkaring :-   I tried obfuscatiny my app using CLI version? and also added decodable  in mode and parallely also i tried all other mode of Name-Protection, but still my log exception stack trace is in readable format, it's not obfuscated.

i can assure that dll got obfuscated. i used Telerik just decompile software to check whether my dll is obfuscated or not.. i found yes it got obfuscated.

have two query
1) generated log stack trace should be obfuscated
2) and when required i can deobfusctae my log stack trace in readable format and solve the production issue.

Thanking You in advance, please guide me with a solution, it will be helpful for me to implement 

[exceptionStackTrace.txt](https://github.com/mkaring/ConfuserEx/files/5175422/exceptionStackTrace.txt)

am attaching my *.crproj file and used *.csproj file for reviewing and guidence so that i can implement confuserEx in my application.
[A.txt](https://github.com/mkaring/ConfuserEx/files/5175373/A.txt)
[B.txt](https://github.com/mkaring/ConfuserEx/files/5175374/B.txt)
[C.txt](https://github.com/mkaring/ConfuserEx/files/5175375/C.txt)
[D.txt](https://github.com/mkaring/ConfuserEx/files/5175377/D.txt)
[E.txt](https://github.com/mkaring/ConfuserEx/files/5175378/E.txt)
[F.txt](https://github.com/mkaring/ConfuserEx/files/5175379/F.txt)
[csproj_file.txt](https://github.com/mkaring/ConfuserEx/files/5175381/csproj_file.txt)
[confuser_Query.docx](https://github.com/mkaring/ConfuserEx/files/5175387/confuser_Query.docx)

**Comment by kushalsaha** [comment]
@mkaring yes types are subject to be get obfuscated. i checked entire apllication code not using InternalsVisibleToAttribute.

**Comment by mkaring** [comment]
Okay, I found the reason. You are using the wrong nuget package for ConfuserEx. Please use [Confuser.MSBuild 1.4.1](https://www.nuget.org/packages/Confuser.MSBuild/1.4.1). This is the correct one. No idea what ConfuserEX.Final does. That package is not created or maintained by me.

**Comment by kushalsaha** [comment]
@mkaring hi mkaring, i tried all suggested approach, but still amd failling to achieve my requirement, i reffered all doc detail and reported issues written in this git hub page.

a small request, please can you share us an **example** for creating dll obfuscation, log stack strace obfuscation and decode stacktrace.  
we searched entire internet for a complete example go through, **but we not found any example.**
request can you **please share a small step by step document** by referring which we can use obfuscation.msbuild in our production deployment. and your small step will help us a lot

**Comment by kushalsaha** [comment]
please share us a detailed work example using Confuser.Msbuild.CLI.exe not using GUI

**Comment by mkaring** [comment]
Okay.

1. Add the ConfuserEx msbuild project to the project you want to obfuscate. This should be a package reference in the project file looking like this: 
   ```xml
   <ItemGroup>
     <PackageReference Include="Confuser.MSBuild" Version="1.4.1">
       <PrivateAssets>all</PrivateAssets>
       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
     </PackageReference>
   </ItemGroup>
   ```
2. Setup the obfuscation in the project. You need to set two properties in your project file to get this working:
   ```xml
   <PropertyGroup>
     <Obfuscate>true</Obfuscate>
     <ConfuserReplaceOutput>true</ConfuserReplaceOutput>
   </PropertyGroup>
   ```
   These settings will enable the obfuscation itself and will cause ConfuserEx to override the output. If the second property is not set or set to `false`, the obfuscated output will be dropped into a `confused` directory in your output directory.
3. Add the ConfuserEx project to the project directory. The name should match the project name by default. Meaning if you got a project that is called "MyProject.csproj", the ConfuserEx project should be called "MyProject.crproj". The project should look something like this:
   ```xml
   <?xml version="1.0" encoding="utf-8" ?> 
   <project xmlns="http://confuser.codeplex.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://confuser.codeplex.com https://raw.githubusercontent.com/mkaring/ConfuserEx/v1.4.1/Confuser.Core/Project/ConfuserPrj.xsd"
            baseDir="." outputDir="." debug="true">
     <rule preset="none" pattern="true">
       <protection id="rename" />
     </rule>
   </project>
   ```
   You don't need to add the assembly name for your project or the directories or anything. That will be setup during the build.

With all this set up the obfuscation will be active and your output will be obfuscated.

If there are still any issues, please head over to https://msbuildlog.com/ and get yourself the structured log viewer. Using this one, you can execute your build and generate a *.binlog file. This will will help to identify if there is any issue during the build that causes the obfuscation to fail.

**Comment by kushalsaha** [comment]
i Implemented the above approach, but not found any success and am really lagging with my delivery timeline in organization.
i created new ticket referrence #214 with sample data example.

once sample data example is obfuscated i will implemennt in this structure project.
project structure:-
Project_1 A
Project_2 B
Project _3 C
Project_4 D
Project_5 E

Project_2 B is our soultion project which is dependent and having references of all other project like Project_1 A, Project _3 C, Project_4 D , Project_5 E .

**Comment by kushalsaha** [comment]
Thanks @mkaring
