### ISSUE TITLE
Public method and class not obfuscating, because of which error stack trace is in readable format

### ISSUE THREAD

**Issue by kushalsaha** [mkaring/ConfuserEx#214]
i used PackageReference Include="Confuser.MSBuild" Version="1.4.1" for dll obfuscation.
attached is the *.crproj file and *.csproj file,

[TestObfustacorWebApp.zip](https://github.com/mkaring/ConfuserEx/files/5201710/TestObfustacorWebApp.zip)
zip file is sample project that i was using.. while uploading zip file i deleted packages folder because of large size. so while downloading and running the solution file may git build error.
![image](https://user-images.githubusercontent.com/31513210/92730747-d35b3980-f391-11ea-8282-2dc08f88ff96.png)

[TestObfustacorWebApp_Csproj.txt](https://github.com/mkaring/ConfuserEx/files/5201608/TestObfustacorWebApp_Csproj.txt)

[TestObfustacorWebApp_CRPROJ.txt](https://github.com/mkaring/ConfuserEx/files/5201613/TestObfustacorWebApp_CRPROJ.txt)
<img width="960" alt="error" src="https://user-images.githubusercontent.com/31513210/92729671-4ebbeb80-f390-11ea-8e75-4bd2970c4268.png">

Please guide me with the solution

**Comment by kushalsaha** [comment]
My main target is to **(1) obfuscate the error stack trace**, means anything should not be in readable format.
once it get obfuscted, latter with **(2) deobfuscation technique i can see the stack trace and fix the production issue.**

am totally new to this. please guide me with solution or example step by step so that i can implement both of issues.

**Comment by kushalsaha** [comment]
Is there any wayto connect with you LIVE either facebook live or youTube live, so that i can explain my issue

**Comment by mkaring** [comment]
There is the gitter chat. You find a link in the readme of the repository.

Also: If you are obfuscating an dll assembly, ConfuserEx assumes that everything public is called by another outside assembly that is not subject to the obfuscation. For that reason it does not rename these types and methods.

If you want all the things public to be obfuscated, you can force ConfuserEx to do so. To do that you can add the argument `renPublic` with the value `true` to the  `rename` obfuscation. You find the information about this [in the documentation](https://github.com/mkaring/ConfuserEx/wiki/Name-Protection)

The tag for the rename protection would look like this, if you add the argument:
```xml
    <protection id="rename">
      <argument name="renameArgs" value="true" />
      <argument name="renPublic" value="true" />
      <argument name="mode" value="decodable" />
      <argument name="password" value="This password is secret" />
    </protection>
```

**Comment by kushalsaha** [comment]
I tried above suggested approach used :- 
 <protection id="rename">
      <argument name="renameArgs" value="true" />
      <argument name="renPublic" value="true" />
      <argument name="mode" value="decodable" />
      <argument name="password" value="This password is secret" />
    </protection> 
by using above configuration file got obfusctaed, but application not running still getting error landing page not found, please see snap shot of obfusctaed dll on Telerik Just Decompiler
![image](https://user-images.githubusercontent.com/31513210/92872081-406adf80-f423-11ea-8c34-a2d79f2737f9.png)


application not running,  still getting error. please see error snap shot below

![image](https://user-images.githubusercontent.com/31513210/92871874-07cb0600-f423-11ea-972b-84e7465ee2b8.png)

**Comment by kushalsaha** [comment]
application not running, still getting error

**Comment by mkaring** [comment]
You can't obfuscate any classes, that are referenced by `aspx` files. Those files reference the classes by name. If you rename the class, the reference is gone and ASP.NET is unable to find the type.

In your case, you need to disable renaming for `TestObfuscatorWebApp.WebForm1`. You can't hide that class and it *will* be visible in the stack trace. That goes to the extend that you can't hide anything that is referenced by the `*.aspx` file.

In your example that is, as far as I can see:
- The class `TestObfustacorWebApp.WebForm1`
- The method `Page_Load`
- The method `btncalc_Click`
- The field `form1`
- The field `TextBox1`
- The field `TextBox2`
- The field `btncalc`
- The field `lblResult`

This means that currently *all* members of this class and the class itself can't be renamed and there is no way to hide it from the stacktrace. The `clsCalculator` class can be obfuscated in your case and would be obfuscated in case it's as as `internal` class with the default configuration.

If you enable the obfuscation for public types and need to disable renaming by hand for all types, methods and fields that are referenced by aspx. Otherwise your application will be broken.

**Comment by mkaring** [comment]
I think the best way to get a handle on this, is to disable the public renaming for all classes overwriting `System.Web.UI.Page`.

That would work by adding a new rule to the Confuser Project.
```xml
<?xml version="1.0" encoding="utf-8" ?> 
<project xmlns="http://confuser.codeplex.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://confuser.codeplex.com https://raw.githubusercontent.com/mkaring/ConfuserEx/v1.4.1/Confuser.Core/Project/ConfuserPrj.xsd"
         baseDir="." outputDir="." debug="true">
  <rule preset="none" pattern="true">
    <protection id="rename">
      <argument name="renameArgs" value="true" />
      <argument name="renPublic" value="true" />
      <argument name="mode" value="decodable" />
      <argument name="password" value="This password is secret" />
    </protection>
  </rule>
  <rule preset="inherits('System.Web.UI.Page')" pattern="true">
    <protection id="rename">
      <argument name="renPublic" value="false" />
    </protection>
  </rule>
</project>
```

This would disable the renaming of all members visible outside of the assembly for all  types that inherit of the `Page` type. This should work for your case.

Alternatively you can add the `ObfuscationAttribute` to the code to disable the renaming.

```c#
[Obfuscate(Exclude := False, Feature := "-rename")]
public class WebForm1 : System.Web.UI.Page {
  …
}
```

Both methods work and will yield the desired result.

**Comment by mkaring** [comment]
Does it work for you now?

**Comment by kushalsaha** [comment]
i refactor my code and made all business logic public classes as private and then obfuscated...

**Comment by kushalsaha** [comment]
but currently we are not much focused on deobfuscation.. but have one query while doing obfuscation we are getting multiple mapping file.. one mapping file for each dll,
but our project have dependency on 6 project and we get 6 mapping file, which created issue at time of deobfuscation of log stack trace.

any option to have one mapping file for 6 dependent dll, rather then having 6 seperate mapping file for each dll

**Comment by mkaring** [comment]
The msbuild integration can't join the mapping files into one, because it obfuscates one assembly at a time. If you run ConfuserEx using the CLI, and process all the assemblies at once, it will produce a single mapping file for all assemblies.
