### ISSUE TITLE
Declarative Obfuscation + symbols.map + watermark

### ISSUE THREAD

**Issue by alexguerin4** [mkaring/ConfuserEx#218]
Is it possible to disable the watermark with declarative obfuscation?

When using Name protection + sequential for the mode and the MSBUILD Nuget package, no symbols.map file is generated. If using the CLI on the same project, it is.
`ConfuserEx would rename symbols to sequential string. The obfuscated name mapping would be saved to output folder in the file "symbols.map".`

**Comment by mkaring** [comment]
It's possible that the file is not copied to the output. Have a look into the immediate output folder (usually `obj`) if the file is present in the `confused` directory. That seems to be a bug in the current release.

As for the watermark. Yes you can disable it using declarative obfuscation:
```c#
[assembly: Obfuscation(Exclude = False, Feature = "-watermark")]
```

**Comment by alexguerin4** [comment]
Thanks for the watermarking, works a treat,

The obj folder does contain the symbols file, along with the PDB and execute.

**Comment by mkaring** [comment]
@alexguerin4: I fixed the issue with the missing copy of the symbol map for the upcoming release. The fixed version is being build [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/37059834). It would be great to get some feedback if this new version works in your project.

The file name for the symbols file can be controlled with the `<ConfuserSymbolFileName>` property. It defaults to `symbols.map` if `ConfuserReplaceOutput` is not set to `true` and to `$(AssemblyName).symbols.map` in case the `ConfuserReplaceOutput` property is set.

**Comment by alexguerin4** [comment]
Great, thanks. The CLI build works, the symbols map and PDB are both copied to output directory but I'm not sure if that already did work and the issue was just when using the nuget package. I can't get the nuget package to work - I might be doing something wrong. The package was installed via the console with
`Install-Package Confuser.MSBuild.1.5.0-alpha-gca3cdd2479.nupkg -Source C:\users\alexg\downloads\` and the solution updated but the following shows when attempting to build in release mode.

1>  [CRITICAL] Unknown error occurred.
1>C:\Users\alexg\.nuget\packages\confuser.msbuild\2.0.0-alpha-0191\build\Confuser.MSBuild.targets(61,5): error MSB4181: The "Confuser.MSBuild.Tasks.ConfuseTask" task returned false but did not log an error.

Here is the parts from the solution.
```xml
  <ItemGroup>
    <PackageReference Include="Confuser.MSBuild">
      <Version>2.0.0-alpha-0191</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU' ">
    <Obfuscate>false</Obfuscate>
    <ConfuserReplaceOutput>true</ConfuserReplaceOutput>
    <ConfuserSymbolFileName>symbols.map</ConfuserSymbolFileName>
  </PropertyGroup>

**Comment by mkaring** [comment]
It did not install the correct version. It installed `2.0.0-alpha-0191` instead of `1.5.0-alpha-gca3cdd2479`.

Try installing it using:
```powershell
Install-Package Confuser.MSBuild -RequiredVersion "1.5.0-alpha-gca3cdd2479" -Source "https://ci.appveyor.com/nuget/confuserex-r4olq7m3uysu"
```

**Comment by alexguerin4** [comment]
No luck I'm afraid.  ```-RequiredVersion``` isn't recognized when installing via VS. Changing to -Version doesn't help either -- all result in `NU1603: Project1 depends on Confuser.MSBuild (>= 1.5.0-alpha-gca3cdd2479) but Confuser.MSBuild 1.5.0-alpha-gca3cdd2479 was not found. An approximate best match of Confuser.MSBuild 2.0.0-alpha-0191 was resolved.`

The same goes for 1.5.0-alpha-gd5882a5bda listed in the appveyor links.

**Comment by mkaring** [comment]
Okay. We need to force Visual Studio to get the proper package source.

Please do the following things in that order:
1. Make sure Visual Studio **is not running**.
2. add [this `NuGet.config`](https://github.com/sjdirect/TestApp/blob/master/NuGet.config) to the directory that contains the solution file, your project is a part of. This will add the Nuget Server to the list of package sources. This will only be relevant for the projects in this solution. Your other package sources are still active.
3. Change the `version` tag in your project from `<Version>2.0.0-alpha-0191</Version>` to `<Version>1.5.0-alpha-gca3cdd2479</Version>`
4. Remove the `obj` directory of your project, to ensure that everything is properly restored.
5. Start Visual Studio and open the project

After this Visual Studio should restore the correct nuget package without and error or warning displayed in the solution explorer regarding this nuget package. The `NU1603` message must not appear. Otherwise it's not working correctly.

**Comment by alexguerin4** [comment]
Nope, still not working. The build error goes away but a different NU1603 now pops up `NU1603	Project1 depends on Confuser.MSBuild (>= 1.5.0-alpha-gca3cdd2479) but Confuser.MSBuild 1.5.0-alpha-gca3cdd2479 was not found. An approximate best match of Confuser.MSBuild 1.5.0-alpha-gcb2afdd219 was resolved.`

The obfuscation works with `1.5.0-alpha-gcb2afdd219` but the symbols file is not copied. Any ideas?

**Comment by mkaring** [comment]
Okay... that one is on me. :wink: The version number is wrong. The correct one is: `1.5.0-alpha-gd5882a5bda`

**Comment by alexguerin4** [comment]
All fixed! Symbols file is now copied as expect. Thanks mkaring.
