### ISSUE TITLE
Obfuscating assemblies in-place causes an IOException: The requested operation cannot be performed on a file with a user-mapped section open.

### ISSUE THREAD

**Issue by SteffanDonal** [mkaring/ConfuserEx#22]
Previously I was able to obfuscate assemblies in-place successfully, however now it fails every time.

Unfortunately I can't provide the project I was testing with. I looked into the issue with `procmon` while stepping through code and found that there is a handle left open to one of the obfuscated modules.

This is even with the code that was originally intended to fix this problem: yck1509/ConfuserEx#76

I gave up here, as I'm not 100% sure where in ConfuserEx 2 to begin hunting for this!

**Comment by mkaring** [comment]
I'll look into it. Can you provide the project file you are using, so I know the protections you are using?

**Comment by mkaring** [comment]
I found the issue. Could you please verify if it works for you with the latest build from the buildserver?

**Comment by mkaring** [comment]
No feedback. In my tests it now works with the changes.
