### ISSUE TITLE
Make obfuscation process parallel

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#223]
As I noticed ConfuserEx utilizes only one thread during obfuscation. Is it possible to increase performance by using all available cores?

**Comment by mkaring** [comment]
This would be an enormous effort to even support multiple threads during the obfuscation. All the collections and storages are not set up in a way to allow multiple threads to work with them at the same time.

`dnlib` seems to support multiple threads properly by now, by using read-write locks.
There may be a way to run some parts of ConfuserEx in parallel. Meaning if multiple assemblies are processed, the analyzing and processing part could run in parallel. How ever, the slow IO bound operations of reading and resolving the assemblies, won't run in parallel and can't run in parallel.

I really doubt that the effort is worth the performance improvement.
