### ISSUE TITLE
Consider using Brotli compressor instead of LZMA

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#224]
It's faster and integrated to .NET Core >= 3.1, see comparison https://cran.r-project.org/web/packages/brotli/vignettes/brotli-2015-09-22.pdf

**Comment by Smurf-IV** [comment]
IN My Tests, If the source to be compressed is not text, then Brotli takes twice as long as LZMA, and achieves worse than LZMA2 (xz)

**Comment by mkaring** [comment]
In the `release/2.0` branch there is already the option to choose from lzma, lz4 and deflate. Where lz4 archives impressive speeds at the cost of significantly worse compression ratio. Deflate is somewhere in the middle, lzma is what we know and ... "love".

Adding more algorithms is easy, but in the case of brotli I question the viability. This algorithm was created to compress websites and not binary data so it performs really good on html and javascript code, but not so much on general binary data.

Also the current implementation of LZMA that is used by ConfuserEx is just bad. It's the LZMA algorithm as it was implemented like 15 years back and it was never updated. The SDK is deployed with every new version of 7zip, but the .NET implementation is never updated.

**Comment by KvanTTT** [comment]
> Adding more algorithms is easy, but in the case of brotli I question the viability. This algorithm was created to compress websites and not binary data so it performs really good on html and javascript code, but not so much on general binary data.

But more proves are required because of in my practice the Brotli shows very good compression ratio and performance even on binary data. Also, as I understand, IL code contains many text identifiers and commands.

> Also the current implementation of LZMA that is used by ConfuserEx is just bad. It's the LZMA algorithm as it was implemented like 15 years back and it was never updated. The SDK is deployed with every new version of 7zip, but the .NET implementation is never updated.

How much complex to update it? I profiled ConfuserEx on my big project and it is shown that LZMA methods have a solid part of overall time.

**Comment by mkaring** [comment]
IL code is mostly binary. The only text are the string constants. 

As for updating the LZMA implementation... That is simply the task of writing the entire thing again from scratch, or rather converting the C code of the implementation into unmanaged C#
