### ISSUE TITLE
System.BadImageFormatException: Invalid DOS signature

### ISSUE THREAD

**Issue by Jacquers** [mkaring/ConfuserEx#225]
Getting the following error: System.BadImageFormatException: Invalid DOS signature

WPF App .Net 4.6.1with some .Net Standard 2.0 referenced projects.

**Comment by mkaring** [comment]
Can you give me some more information regarding your application? The DOS signature is actually something the obfuscation shouldn't touch. What version of ConfuserEx did you use? Where any warnings or errors shown during the obfuscation process?

**Comment by Jacquers** [comment]
I managed to get it working in the mean time, thanks.

**Comment by nilsonsrjunior** [comment]
@Jacquers  how did you manage to get it working ? i'm facing the exactly same problem

**Comment by Jacquers** [comment]
I think the issue was that I didn't configure the options before using it (no protections selected). Or I hadn't dragged an exe / dll into the ui. Once I figured out what to do on the ui it worked.

**Comment by mkaring** [comment]
That is strange. In either case, the obfuscation shouldn't produce a broken signature.

@nilsonsrjunior: Could you send me the assembly with the broken signature for analysis?
