### ISSUE TITLE
Mutation.cs in Confuser.RunTime issue

### ISSUE THREAD

**Issue by HeXN0P** [mkaring/ConfuserEx#226]
After modify Mutation Key Value in Mutation.cs in Confuser.RunTime. Packed exe can't launch and if turn on compressor it error out.

Modified value:
 
x is a integer

`	public static readonly int KeyI0 = x;
	public static readonly int KeyI1 = x;
	public static readonly int KeyI2 = x;
	public static readonly int KeyI3 = x;
	public static readonly int KeyI4 = x;
	public static readonly int KeyI5 = x;
	public static readonly int KeyI6 = x;
	public static readonly int KeyI7 = x;
	public static readonly int KeyI8 = x;
	public static readonly int KeyI9 = x;
	public static readonly int KeyI10 = x;
	public static readonly int KeyI11 = x;
	public static readonly int KeyI12 = x;
	public static readonly int KeyI13 = x;
	public static readonly int KeyI14 = x;
	public static readonly int KeyI15 = x;`

`[ERROR] Failed to resolve dependency of 'StringGenerator.exe'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Confuser.Runtime, Version=1.5.0.0, Culture=neutral, PublicKeyToken=5fbc98a9d8494c64
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule)
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context)
[ERROR] Failed to protect packer stub.
Failed at 11:38:15 AM, 0:01 elapsed.`

In DnSpy it try to add Confuser.RunTime ref to use Mutation value.
![image](https://user-images.githubusercontent.com/13214994/93556884-e7132b00-f9a3-11ea-96bf-2dd03d707b61.png)

**Comment by mkaring** [comment]
The mutation values are filled with random values during the obfuscation. Do not set them by hand.

**Comment by HeXN0P** [comment]
Oh i see. Thank you for reply.
