### ISSUE TITLE
Strong mode on reference proxy protection breaks module

### ISSUE THREAD

**Issue by ElektroKill** [mkaring/ConfuserEx#229]
Hello,

After applying reference proxy on strong mode onto a module using the latest build (0b7d2816c7e283ebb01b89f514388d7beada6f05) the output module no longer runs.

Thanks in advance.

**Comment by mkaring** [comment]
Are we talking about the `master` branch here?

**Comment by ElektroKill** [comment]
Yes, i faced this issue with latest build(dnlib nugget) from master branch

**Comment by XenocodeRCE** [comment]
@mkaring still no fixes ? This is considered as a major flaw since your changes broke one of ConfuserEx bests protection so far

**Comment by xmoer** [comment]
Me, too. But when "encoding = x86" protection is work. In strong mode, both "normal" and "expression" cause errors.

**Comment by mkaring** [comment]
I can reproduce the error. It's some random error that hits in about 50% of the runs.

**Comment by mkaring** [comment]
The changes introduced in #85 are the cause for this error. The protections require the wrong behavior of the trace service in order to work properly.

**Comment by mkaring** [comment]
I got this mess sorted out. A new build that contains the fix for this specific issue is available [here|https://ci.appveyor.com/project/mkaring/confuserex/builds/37086224/artifacts]. It would be great if the fix could be verified in an actually affected project. The unit test I created is very simple.

**Comment by ElektroKill** [comment]
Hello, I tested the build with an application that targets .NET 2.0 and it crashes on startup. I tried with the same application but with the target framework set to .NET 4.0 and it worked flawlessly. I think there is still a problem here.

I used the following configuration:
```
<protection id="ref proxy">
  <argument name="mode" value="strong" />
  <argument name="encoding" value="expression" />
</protection>
```

Here are both of the files I used for testing:
(NOTE: I didn't create this application, it's just some file I had laying around)
[testsamples.zip](https://github.com/mkaring/ConfuserEx/files/5762248/testsamples.zip)

**Comment by mkaring** [comment]
That is an unrelated error. This problem is caused by the changes for #144.

**Comment by mkaring** [comment]
Not done yet.

**Comment by mkaring** [comment]
Okay. Rewiring the runtime code to the proper target assembly, works fairly easy. How ever, there is still the problem that the runtime code is not .NET Framework 2.0 compatible, as I just noticed...

**Comment by mkaring** [comment]
Okay. I got this sorted out. It should now work in all cases starting with .NET Framework 2.0 and later.
The new build can be downloaded [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/37185391/artifacts).

**Comment by ElektroKill** [comment]
The mentioned build fixed the problem and the .net 2.0 file runs fine!
