### ISSUE TITLE
How to use this with Visual Studio Post-Build Events

### ISSUE THREAD

**Issue by unmeshbane** [mkaring/ConfuserEx#237]
I am a beginner in programming , I've used the Gui exe of ConfuserEx1.4.1 but I want to use it in the post build events of Visual studio. Need help with it. I am also new to Github and I dont know how to ask questions to the Author, hence I have posted it as an issue.

**Comment by mkaring** [comment]
ConfuserEx 1.4.1 has a MSBuild integration that helps to create an obfuscated assembly as part of the compilation process. This is limited to handling each project in your solution individually. So in case you want to use the packer or something like this, it will not work.

You can also use the command line executable of ConfuserEx as a post-build step. You just need to provide it with the project file and that is populated with the required information. Best use relative paths in the project file in this case.
For information regarding the command line interface, just call the `Confuser.CLI.exe` in a console and you'll get the required information printed to the console.

**Comment by mkaring** [comment]
@unmeshbane: Let me know if you got it working or if you need further help.

**Comment by unmeshbane** [comment]
I've checked, but I didn't find any suitable documentation to add the post build event. If you do have handy guidelines please do share.

**Comment by wmjordan** [comment]
I can give you an example.

Put the following code snippet under the root element in your _csproj_ file.
And create a _**crproj**_ file with ConfuserEx and save it to the project folder with your _csproj_ file.
I assume that the protected assembly is an EXE file and it has some assembly dependencies to be packed before protection.

````xml
  <Target Name="AfterBuild" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <InputAssemblies Include="$(AssemblyName).exe" />
      <InputAssemblies Include="<<ASSEMBLY_DEPENDENCY>>.dll" />
      <!--REPEAT ABOVE ELEMENT IF YOUR ASSEMBLY HAVE MORE DEPENDENCIES NOT IN GLOBAL CACHE-->
    </ItemGroup>
    <Exec WorkingDirectory="$(OutputPath)" Command="&quot;<<OPTIONAL_IL_REPACK_PATH>>ILRepack.exe&quot; /union /ndebug /keyfile:<<OPTIONAL_YOUR_KEY_TO_CODE_SIGN>> /out:$(AssemblyName).exe @(InputAssemblies, ' ')" />
    <Exec Command="if errorlevel 0 &quot;<<YOUR_PATH_TO_CONFUSEREX_HERE>>\Confuser.CLI.exe&quot; -n $(ProjectName).crproj" />
  </Target>
````

**Comment by Paul-Schroeder** [comment]
You can also use PowerShell, as such:
`if $(ConfigurationName) == Release (powershell.exe -file "$(ProjectDir)Scripts\YourScript.ps1" "$(TargetPath)" YourAdditionalScriptArguments)`

Then, in the PowerShell script do what you need to do and when you're ready to obsfucate do something like this:

`& 'C:\PathToExe\Confuser.CLI.exe' "C:\PathToYourConfuserProj\MyConfuserEx.crproj" -n;`

**Comment by mkaring** [comment]
I think this issue ran it's course :wink:
