### ISSUE TITLE
Token handles leak using <packer id="compressor" />

### ISSUE THREAD

**Issue by ElRapoh** [mkaring/ConfuserEx#245]
Executable works perfectly before obfuscation process or with all protections enabled and no packing.

When confusing the executable with the compressor packer enabled (with or without protections), many token handles are opened and never released making ram usage slowly but constantly increasing.

Process Explorer will help testing this behaviour (handles count and handles view).

**Comment by ElRapoh** [comment]
Update:

The issue is related to the use of a ServiceHost with NetNamedPipeBinding.


```
 _serviceHost = new ServiceHost(this, new Uri[] { new Uri("net.pipe://localhost/exampleService") });
 _serviceHost.AddServiceEndpoint(typeof(IIPCService), new NetNamedPipeBinding(), "UIService");
_serviceHost.Open();
```

when this service is called from an external process, if the executable is packed, there is a Token handles leak. 
Further investigations on this correlation will follow.

**Comment by ElRapoh** [comment]
Update:

There is something inside WCF implementation of named pipe inter-process communication that does not like the executable to be packed by Confuser.

For an unknown reason, in this behaviour a ServiceHost with NetNamedPipeBinding will leave Token handles opened. This is related to the authentication machanism of the named pipe channel, which requires security tokens.

As a workaround to prevent token handles leak, security may be set to None:

```
_serviceHost = new ServiceHost(this, new Uri[] { new Uri("net.pipe://localhost/exampleService") });
_serviceHost.AddServiceEndpoint(typeof(IIPCService), new NetNamedPipeBinding() { **Security = new NetNamedPipeSecurity() { Mode= NetNamedPipeSecurityMode.None }** }, "UIService");        
_serviceHost.Open();
```

This is the only way I found to use NetNamedPipe on a packed executable without token handles leak.

So, not sure this could be considered a Confuser issue, anyway this case can be useful for other developers.

**Comment by ElRapoh** [comment]
Update:

There is also a Thread handles leak. Original exe image works perfectly, packed compressed image presents the issue.

**Comment by mkaring** [comment]
The only reason for this I can think of, is that the compressor changes the module name of the compressed assembly. Maybe this messes with the `ServiceHost`.

The thing you could try to work around this, is use the compatibility mode of the compressor.

You can find the [documentation for the `compressor` here](https://github.com/mkaring/ConfuserEx/wiki/Compressor). You'd need to set the `compat` argument to `true`. Could you test if that improves the situation?
