### ISSUE TITLE
Issue with resources

### ISSUE THREAD

**Issue by agendec-com** [mkaring/ConfuserEx#25]
Hi.

First of all I want to thank you for continuing development of ConfuserEx :)

We get the following exception when embedded resource are being used:
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Agendec.Client.Resources.resources" was correctly embedded or linked into assembly "DPAgenda" at compile time, or that all the satellite assemblies required are loadable and fully signed.

We are using Normal preset and adding rename.
I've also tried removing resources but still get the same exception.
Without obfuscation it works fine.

Regards, Rolf

**Comment by mkaring** [comment]
What Version are you using? The current 1.1 release or the 2.0 branch?

**Comment by agendec-com** [comment]
I'm using the current 1.1 release.

**Comment by mkaring** [comment]
So I wrote a small unit test trying to get a minimal example working to reproduce your problem. How ever my simple example works fine, so it seems there are some specific changes you applied to your project that cause problems here.

You'll find my minimal project [here][1]. Can you provide any additional information how you got your resources set up, so I can track down that error? Can you provide the `*.crproj` file you are using? Or even better, can you share a minimal example that suffers the error, I can use as baseline for the unit test?

[1]: https://github.com/mkaring/ConfuserEx/tree/feature/issue_25/Tests/NeutralResx

**Comment by MurariAlex** [comment]
Maybe the application is multi-language. When working with multi-language applications (like when you set the thread culture), the resources for non-neutral languages is deployed to different folders, for example, brazilian portuguese goes to the folder pt-BR (or a custom folder, but you must set the Probe Path in the app settings).

ConfuserEx (Yck´s branch) resources/rename protections always have broken my multi-language apps. (Didn´t test this project yet). The only resource it could find was the neutral after confused, the specific languages never worked.

Maybe it´s getting lost there, or the OP is forgetting to copy the resources to the output folder after confusing the app.

**Comment by mkaring** [comment]
The error message indicates that it doesn't even find the neutral language resources that should be in the same assembly. Obfuscating multi language assemblies works, but you have to add all the satellite assemblies to the project for it to work. With the packer it only works for .NET >= 4.0 right now, because older versions have a hack in the way they are loading satellite assemblies.

@agendec-com Are you using the "default" generated code to load the resources or is there anything custom in place?

**Comment by agendec-com** [comment]
I've attached a simple example which causes the issue, including the crproj file.
It's a VB.Net project using .Net 4.6.1. Target CPU is set to x86 (don't know if it matters).
The resource causing the problem is the png image set on button1 in form1. It's added by importing the image to the project's resource file (Resources.resx) when setting the image on the button.

[ResourceIssue.zip](https://github.com/mkaring/ConfuserEx/files/2939992/ResourceIssue.zip)

**Comment by mkaring** [comment]
I tracked the issue down. The `rename` protection isn't handling resources in VB.NET projects properly. Working on a solution.

**Comment by agendec-com** [comment]
Great :)

**Comment by mkaring** [comment]
I fixed the issue. Could you please verify that it works for you with the build you can [download here][1].

[1]: https://ci.appveyor.com/project/mkaring/confuserex/builds/22895671/artifacts

**Comment by agendec-com** [comment]
It now seems the initial problem is fixed.
However, I get the following exception on an execution path in our app:
Err number: 5. System.ArgumentNullException: Argumentet name kan ikke være null.
Parameternavn: name
   ved System.Data.DataColumnCollection.get_Item(String name)
   ved System.Data.DataRow.GetDataColumn(String columnName)
   ved Agendec.Client.rscActivitySrv.CheckRemindForAct(AgFoundation.rscActivityBE& , DateTime& )

"Argumentet name kan ikke være null" translates to something like "The argument name cannot be null", and "Parameternavn" to "Parameter name".

When not obfuscated it works fine, and also works fine with ConfuserEx 1.0.0.

**Comment by mkaring** [comment]
Could you please open a new issue for that?
Please also add some more details regarding how you are indexing the `DataColumnCollection`.
