### ISSUE TITLE
Renaming could fail when implementing multiple interfaces with members of the same name

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#252]
Recently I found that the renamer reported failed to rename quite a few members in some complicated projects.

After some tracing, I found that the cause was that there were two interfaces which had a same member name, and two classes happened to implement both interfaces individually. When I removed the `IName` from one class, no warning any more.

You can reproduce the error with the following classes or the following assembly.
[sample.zip](https://github.com/mkaring/ConfuserEx/files/5536072/sample.zip)

````C#
	public interface IName { string Name { get; } }
	public interface IOperator {
		string Name { get; }
		void Operate();
	}
	public interface IWorker : IName, IC
	{

	}
	public interface IC {
		void C(string x);
	}
	sealed class Operator : IC, IOperator, IName {
		public string Name { get; set; }

		public void C(string x) {
			throw new NotImplementedException();
		}

		void IOperator.Operate() {
			throw new NotImplementedException();
		}
	}
	class Worker
	{
		public void C(string x) {
			throw new NotImplementedException();
		}
	}
	sealed class Manager : Worker, IWorker, IOperator
	{
		public string Name { get; }

		public void Operate() {
			throw new NotImplementedException();
		}
	}
````

The warning message:
````
 [WARN] Failed to rename all targeted members, because the references are blocking each other.
Remaining definitions: 
• Original Name: ConsoleApp1.Manager::Name; Name Hash: 7FD14884
• Original Name: ConsoleApp1.Operator::get_Name; Name Hash: 80656335
• Original Name: ConsoleApp1.Manager::get_Name; Name Hash: 29F5020F
• Original Name: ConsoleApp1.Operator::Name; Name Hash: DC8BAEA4
• Original Name: ConsoleApp1.IName::get_Name; Name Hash: CC986802
• Original Name: ConsoleApp1.IOperator::get_Name; Name Hash: 47B3E33D
• Original Name: ConsoleApp1.IOperator::Name; Name Hash: 1112CB76
• Original Name: ConsoleApp1.IName::Name; Name Hash: 7B5602B1
````

**Comment by wmjordan** [comment]
The project which encountered this issue was quite large. In small projects, things were going well.

I will post a sample project if I can produce one later.

**Comment by mkaring** [comment]
I think these problems where already reported in #187. This issue would be fixed in 1.5. Could you verify if it works in the current 1.5 build. You can download it here: [ConfuserEx - AppVeyor](https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts)

**Comment by wmjordan** [comment]
I tried that build.
The renaming operation still failed on those members.

**Comment by mkaring** [comment]
I'm looking into it.

**Comment by wmjordan** [comment]
Any news for this issue?

**Comment by mkaring** [comment]
Sorry that took so long. I identified the issue, fixed it and added a unit test to cover this kind of the problem. It would be great if you could run a test with the build you can download here: [Appveyor - ConfuserEx](https://ci.appveyor.com/project/mkaring/confuserex/builds/36920629/artifacts)

**Comment by wmjordan** [comment]
Thank you very much for taking on this tough problem.

I'd used this build to protect my program and put it onto my experimental servers. So far, so good.

**Comment by wmjordan** [comment]
I shall leave this issue open and let your PR to close it.
