### ISSUE TITLE
ConfuserEx-Unpacker kinda fully restores control flow

### ISSUE THREAD

**Issue by lengyeljanos** [mkaring/ConfuserEx#253]
Hello!

I just found ConfuserEx-Unpacker-v2.0 and it almost fully restores the whole assembly I obfuscated with ConfuserEx 1.4.0.
If you need it then I can send the unpacker in private.

my protection setup

    <protection id="anti dump" />
    <protection id="anti tamper">
      <argument name="key" value="dynamic" />
    </protection>
    <protection id="ref proxy" />
    <protection id="rename">
      <argument name="renPublic" value="false" />
      <argument name="renameArgs" value="true" />
    </protection>
    <protection id="harden" />
      <protection id="ctrl flow">
        <argument name="predicate" value="x86" />
        <argument name="intensity" value="100" />
        <argument name="depth" value="20" />
        <argument name="junk" value="true" />
      </protection>
      <protection id="constants">
        <argument name="mode" value="x86" />
        <argument name="decoderCount" value="100" />
        <argument name="cfg" value="true" />
      </protection>
      <protection id="invalid metadata" />
      <protection id="resources" />

**Comment by ElektroKill** [comment]
As the developer of this tool (sry ConfuserEx) I can for sure tell you that enabling cfg on constants will break the tool’s constant decrypter. Enabling dynamic mode for key on AntiTamper can lead to the file being corrupted instead of properly unpacked. The new harden option is completely unsupported by the tool which means any protection affected by it should not be removed. Sadly, ref proxy and control flow are able to be cleaned by this tool. I hope this kind of clarified the problem.

**Comment by lengyeljanos** [comment]
You developed it and you say "sadly"? :)

**Comment by lengyeljanos** [comment]
1) I use harden
2) I use dynamic anti tamper
3) I use cfg constant

still your tool can almost fully clear the protected assembly :/

**Comment by ElektroKill** [comment]
> You developed it and you say "sadly"? :)

I no longer develop the tool.

> 1. I use harden

This should prevent constant and resource protections from being removed. Some of the other protections which inject code into <Module>.cctor like AntiDump and AntiDebug.
> 2. I use dynamic anti tamper

This should lead to the tool outputting code which is able to be viewed in a decompiler but the file would be unable to start if it’s and exe.
> 3. I use cfg constant

This option will make the decryption of constants much harder.
> still your tool can almost fully clear the protected assembly :/

As for the ref proxy, you could try enabling strong mode and seeing if that helps. If it comes to control flow there is nothing I am aware off in the current ConfuserEx version that would make the tool not function. If you would like to experiment with making your code even harder to read I would suggest trying if the type scrambler option works for your application but I can’t promise that it will work 100%. This type scrambler option is not touched by the unpacker utility.

**Comment by KvanTTT** [comment]
Also, try to use `renPublic` flag.

**Comment by thekjohn** [comment]
> I no longer develop the tool.
So the package behind the link in the comments of this video is not yours?
https://www.youtube.com/watch?v=O7gx3hsWIVk

**Comment by lengyeljanos** [comment]
"I no longer develop the tool."

So the package behind the link in the comments of this video is not yours?
https://www.youtube.com/watch?v=O7gx3hsWIVk

**Comment by ElektroKill** [comment]
The program named ConfuserExUnpacker 2.0 was created by me and is featured in the video. However, I haven’t done any work on it since 14th of November 2019. Hope this clarifies some things up.

**Comment by mkaring** [comment]
The questions have been answered.
