### ISSUE TITLE
Issue with DataBindings

### ISSUE THREAD

**Issue by Dan-of-BIT** [mkaring/ConfuserEx#254]
Get a warning during build as follows
`[WARN] Failed to extract target property in 'System.Void aFrm::aMethod()`
when that method contains databindings like the following
`txtBox.DataBindings.Add("Text", AnObject, "Property");`
the build will not fail and will generate the obfuscated exe.
but when running the code will fail on the data binding line of code with an error

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at eGufJuRjagMKabKzHFTMaVBJWcOAA.FmmDvCcGSFHaOuhAuWKDuIlqQskO() in C:\... \aFrm.cs line xxx

also creating bindings the following way also has the same issue
`new Binding(nameof(txtBox.Text), AnObject, nameof(AnObject.aProperty));`

**Comment by mkaring** [comment]
Hello,

this warning means that ConfuserEx was unable to find the `Property` that is referenced in the binding in any type of the current assembly. Is there anything special about the object you are referencing? Where is it located? Same assembly or another?

**Comment by Dan-of-BIT** [comment]
Hey,

Looks like the class is Serializable. It's located in the same namespace

**Comment by mkaring** [comment]
There still has to be a reason, why it's not detecting the property correctly. Can you provide the declaration of the property that doesn't work and the declaration of it's type? Maybe there is something there.

This warning is raised, in case it does not find any property that is matching the name of the property in the data binding.

**Comment by Dan-of-BIT** [comment]
So the object is declared like this
```
    public partial class frmConsole : Form
    {
        MdConnection ActiveSource = new MdConnection();
```
the class is implemented like so
```
    [Serializable()]
    public class MdConnection 
    { ...
```
I also tried adding this
```
    [Serializable()]
    [System.Reflection.ObfuscationAttribute(Exclude = false, Feature = "constants")]
    public class MdConnection
    {
```
just thought since it was **NOT** throughing a warning when forceRen i might as well try to manually set to obfuscate

**Comment by mkaring** [comment]
It's not the constants protection that is  causing the issue. The source of the problem is the "rename" protection.

So you may need to add this attribute to the property:
```CS
[System.Reflection.ObfuscationAttribute(Exclude = false, Feature = "-rename")]
```
I am guessing all this happens in an assembly that is an executable, right? Otherwise there wouldn't be a problem here at all.

Note that the warning may still show up, but the assembly should work.

**Comment by Dan-of-BIT** [comment]
Okay. Yes it is an executable. The -rename feature works. I still do get the warnings but the exe runs without throwing errors. Except now the class isn't obfuscated. 
This class is serialized and saved to file during save operations. On open it is de-serialized.
I wonder is there a way to take serialized classes and obfuscate them so they can be opened again and deserialized back into an object of that type.

**Comment by mkaring** [comment]
For a more detailed analysis of the issue I either need the assembly you are trying to protect or a minimal working example. Otherwise it will be difficult to figure out what is wrong.
