### ISSUE TITLE
Renaming could not be excluded by rule

### ISSUE THREAD

**Issue by gallinule** [mkaring/ConfuserEx#255]
Hello,
I found that it may not be possible to exclude renaming of 'public enum' by rule settings. 
It was reproduced under the following conditions.
 -Not include code of 'typeof(T).Name'.
 -It happens in v1.1.0 or later, no probrem with v1.0.0.

This causes problems with XML serialization.

Refer to the following code and configuration.

```
    public enum Enum1
    {
        Item1,
        Item2
    }

    public class DataObject
    {
        public Enum1 Member1 { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            System.Console.WriteLine(nameof(Enum1));
            System.Console.WriteLine(typeof(Enum1));
            //System.Console.WriteLine(typeof(Enum1).Name); // <- It works fine if you uncomment this line.

            using (var stream = new MemoryStream())
            {
                var dataObject = new DataObject();
                var serializer = new XmlSerializer(typeof(DataObject));
                serializer.Serialize(stream, dataObject);
                System.Console.Write(Encoding.UTF8.GetString(stream.ToArray()));
            }
        }
    }

```
```
<project outputDir="Confused" baseDir="bin\Release" seed="Test" debug="true" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="maximum" inherit="false" />
  <rule pattern="inherits('System.Enum') and is-public()" inherit="false">
    <protection id="rename" action="remove" />
  </rule>
  <rule pattern="match-type-name('DataObject')" inherit="false">
    <protection id="rename" action="remove" />
  </rule>
  <module path="PublicEnumCouldNotBeExcluded.exe" />
</project>
```
[ConfuserEx2Issues.zip](https://github.com/mkaring/ConfuserEx/files/5558414/ConfuserEx2Issues.zip)

**Comment by mkaring** [comment]
I checked this problem, and the source of the problem is the `is-public` filter. In an executable all `public` members are considered `internal`, because nothing else is calling the members in an executable.

So changing project like this resolves the issue:
```xml
<project outputDir="Confused" baseDir="bin\Release" seed="Test" debug="true" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="maximum" inherit="false" />
  <rule pattern="inherits('System.Enum')" inherit="false">
    <protection id="rename" action="remove" />
  </rule>
  <rule pattern="match-type-name('DataObject')" inherit="false">
    <protection id="rename" action="remove" />
  </rule>
  <module path="PublicEnumCouldNotBeExcluded.exe" />
</project>
```

It is a bit confusing, but `is-public()` is actually `is-visible-outside()` instead of actually public. If you are working a lot with serialization I suggest disabling the renaming without checking for `is-public()` or something. Doing it by namespace or by the serialization attribute usually works best.

**Comment by gallinule** [comment]
Thank you for your advice.
I will remove is-public() and consider another method.

However, although less necessary, public type in executable is actually visible outside. 
I think for filter, it may not be necessary to consider it as internal.
I will try to change is-public() to do so.
