### ISSUE TITLE
About tab

### ISSUE THREAD

**Issue by Guiorgy** [mkaring/ConfuserEx#256]
The `About` tab in the app still takes you to the old discontinued project page, and asks to donation there.
It should take you to this github repo and probably opencollective for donations, and it would also help if it mentioned the [wiki](https://github.com/mkaring/ConfuserEx/wiki) for more information

**Comment by Guiorgy** [comment]
Never mind, you changed that in **ConfuserEx 2**, but as the master branch is **_currently the one intended for use in production environments_** as stated in the wiki, I think it should also do so.

**Comment by mkaring** [comment]
It's done.
