### ISSUE TITLE
.NET Core 3.1 | Failed to resolve a type, check if all dependencies are present in the correct version

### ISSUE THREAD

**Issue by WGOS** [mkaring/ConfuserEx#257]
Greetings.
For some reason, I can't obfuscate my .NET Core 3.1 assemblies. [Stacktrace on pastebin](https://pastebin.com/G9bDt45k)
Seems like Core App referencing its own System.Runtime assembly but Confuser loads up System.Runtime from .NET Framework, not Core:
`Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: System.Runtime.CompilerServices.IAsyncStateMachine (System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)`

`[ERROR]     System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.NET\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)`

What I've tried:

- Switching to lastest version of Confuser on CI-server
- Adding .NET Core's System.Runtime
- Replaceing assembly in `C:\WINDOWS\Microsoft.NET\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\` for .NET Core one

**Comment by KvanTTT** [comment]
.NET Core is not supported yet. It's duplicate, see #58, #106 and other

**Comment by WGOS** [comment]
Thanks. I've already checked entire tracker so sorry for another dupe

By the way I think that support for Core should not be claimed at the description on project's web page in this case 😄

**Comment by jafreitas90** [comment]
But it says in the readme that supports .netcore :\ I  am trying to put this to work in a wpf .netcore 3.1 without success

**Comment by KatDevsGames** [comment]
Why is netcore support claimed if it's not present? This makes no logical sense.
