### ISSUE TITLE
Exception when getting a column item from a DataRow object

### ISSUE THREAD

**Issue by agendec-com** [mkaring/ConfuserEx#26]
I get the following exception on an execution path in our app:
```TXT
Err number: 5. System.ArgumentNullException: Argumentet name kan ikke være null.
Parameternavn: name
ved System.Data.DataColumnCollection.get_Item(String name)
ved System.Data.DataRow.GetDataColumn(String columnName)
ved Agendec.Client.rscActivitySrv.CheckRemindForAct(AgFoundation.rscActivityBE& , DateTime& )
```
"Argumentet name kan ikke være null" translates to something like "The argument 'name' cannot be null", and "Parameternavn" to "Parameter name".

As stated in the header it seems to happen when accessing a column item from a DataRow object.
We access the get property of a column item in two ways:
1. **row.Item("nameOfColumn")**. 
2. **row!nameOfColumn**.

However, the exception doesn't seem to happen consistently; it seems to go ok in other parts of the code where we have the same type of code. Also, when I tried to add some logging code in the function where the exception occurred, the exception no longer occurred!?

When not obfuscated it works fine, and also works fine with ConfuserEx 1.0.0.

**Comment by mkaring** [comment]
The two different ways of accessing the string indexer are exactly the same after compiling. So that can't be the problem. I am having trouble reproducing the error. I tried to build a test case (create a [`DataTable`][1], populate the rows and access those rows after) and it works fine. So my best guess is that there is something in the affected method that causes the issue. Is there any chance that you could send me the source code of one of the methods that are affected? This way I may be able to locate the issue. 

I'm guessing the same obfuscation instructions as in issue #25 are in place?

[1]: https://docs.microsoft.com/dotnet/api/system.data.datatable?view=netframework-4.7.2

**Comment by agendec-com** [comment]
Attached is the relevant source - source.txt contains the function where the exception occurs.
The other 2 files are the ones most used by the function that contains the column items source.
Don't know if it's relevant, but the source.txt is in another assembly which reference another assembly containing the 2 other files.
Yes, same obfuscation instructions as in issue 25.

[source.txt](https://github.com/mkaring/ConfuserEx/files/2943908/source.txt)
[rscActivityBE.vb.txt](https://github.com/mkaring/ConfuserEx/files/2943910/rscActivityBE.vb.txt)
[rscActParticipantBE.vb.txt](https://github.com/mkaring/ConfuserEx/files/2943912/rscActParticipantBE.vb.txt)

**Comment by mkaring** [comment]
I can't reproduce the issue. Could you send me the affected assembly before obfuscation to karing.martin@gmail.com

I won't be able to find the issue without,  because I'll need to extract the IL code. I don't need any dependencies, just the assembly that is not working properly.

**Comment by agendec-com** [comment]
Ref. my latest answer on issue 27; could this also be the cause here?

**Comment by mkaring** [comment]
I very much doubt that, because it shouldn't effect the way the string for the method are obfuscated. I'll suggest we keep this issue on hold until I figured out what sort of side effect is happening in #27.

Once that is clear this issue may or may not be resolved.

**Comment by agendec-com** [comment]
Ok.

**Comment by mkaring** [comment]
@agendec-com: There have been a lot of improvements to the protections of ConfuserEx in the mean time. Is this issue still present in the latest version?

**Comment by agendec-com** [comment]
I've now tested and it seems to work ok :)

FYI: When I tried to download the ConfuserEx.zip for 1.5.0 RC1, Google Chrome gave me a warning of a potential harmful file. When downloading the zipfile for version 1.4.1 it gave no warning. In MS Edge no files gave any warning.

Regards, Rolf

**Comment by mkaring** [comment]
Thank you for the feedback. I noticed this message as well. Not sure yet, what causes message to appear. I'm looking into it.
