### ISSUE TITLE
Failed to resolve dependency

### ISSUE THREAD

**Issue by raduvarga** [mkaring/ConfuserEx#261]
I get the following error on building:

```
  [ERROR] Failed to resolve dependency of 'Example.exe'.
  Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Windows.Foundation.UniversalApiContract, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
     at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule)
     at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context)
```

and using this .crproj file:

```
<?xml version="1.0" encoding="utf-8"?>
<project baseDir="..\Release" outputDir="..\Release\Confuse">
    <rule preset="none" pattern="true">
        <protection id="anti debug" />
        <protection id="anti dump" />
        <protection id="anti ildasm" />
        <protection id="anti tamper" />
        <protection id="constants" />
        <protection id="ctrl flow" />
        <protection id="invalid metadata" />
        <protection id="ref proxy" />
        <protection id="rename" />
        <protection id="resources" />
    </rule>
    <module path="Example.exe" />
</project>
```

I do see that it's using .NET Framework v4.0, while my app uses 4.7.2

`[INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 32 bits`

How to fix this?
Thanks in advance!

**Comment by xtremertx** [comment]
Same problem, not sure how to solve this. Docs are not mentioning how to ignore some assemblies from renaming...

**Comment by mkaring** [comment]
ConfuserEx requires all assemblies to be resolved, no matter if they are subject to the obfuscation or not. This is required to properly analyse all the members that are declared in the assemblies that are obfuscated.

Missing assemblies can be added to the project as external references. Just add them to the project file:
```xml
<module path="full/path/to/missing/assembly.dll" external="true" />
```
