### ISSUE TITLE
Parameter "x86" caused the 64-bit program to become 32-bit

### ISSUE THREAD

**Issue by dxj25104** [mkaring/ConfuserEx#269]
VS Release Settings: AnyCPU + Disable Prefer 32-bit. So application that will run as x64 on an x64 machine. But when the protected parameter contains "x86", disable prefer 32-bit is broken.

For example:

```
<protection id="ctrl flow">
  <argument name="predicate" value="x86" />
</protection>

<protection id="ref proxy">
  <argument name="encoding" value="x86" />
</protection>
```

**Comment by xmoer** [comment]
yeah, I verified that this problem does exist.

**Comment by mkaring** [comment]
This is no error. An assembly that contains native code has to be either x86 or x64. There is no such thing as an assembly containing native code that is "AnyCPU".

This means that once native code is injected, "AnyCPU" and "x86" assemblies will be x86 assemblies and "x64" assemblies will remain x64 assemblies. The reason why "AnyCPU" is turned to x86 is to ensure that the assembly does not suddenly work on fewer systems.

I verified that this works fine.

If you require your assemblies to run as 64-bit applications, you need to compile them with the 64-bit target or avoid using the native code based protection modes.
