### ISSUE TITLE
Control Flow Bug

### ISSUE THREAD

**Issue by dmanchura** [mkaring/ConfuserEx#295]
I'm not 100% sure on this as the original C# error and the "true" error appear different but here it goes.
Running control flow on the below function causes the function to be left in an un-compilable state.
Using 1.4.1 July 2020 release.

Test:
Minimal preset + ctrl-flow.
None + ctrl-flow
Copy ctrl-flow'd code back into VS2019 and cannot compile (obvious why in the code below).

Fix:
Code can be rearranged but our library is large and the code is a common pattern.

Base code:

    public void ReadSets(Project project)
    {
        if (project == null)
            return;
        List<SetInfo> sets = new List<SetInfo>(); 
        ReadSets(project, project, sets);
        DataSource = sets;
    }
Fixed code (Moving the initialization of the list above the null check creates the correct switch):

    public void ReadSets(Project project)
    {
        List<SetInfo> sets = new List<SetInfo>(); 
        if (project == null)
            return;
        ReadSets(project, project, sets);
        DataSource = sets;
    }

Preset non + ctrl flow of the base code (snippet):

    public void ReadSets(Project project)
    {
        //Discarded unreachable code: IL_0313
        if (project == null)
        {
            goto IL_0003;
        }
        goto IL_006d;
        IL_006d:
        List<SetInfo> list = new List<SetInfo>();
        int num = -1648406663;
        goto IL_0008;
        IL_0008:
        while (true)
        {
            uint num2;
            switch ((num2 = (uint)num ^ 0xCCCF8B87u) % 14u)
            {
            case 7u:
                break;
            default:
                return;
            case 6u:
                ReadSets(project, (IEntities)(object)project, list);→この行のlistが未初期化と出ました。
                num = randomNumber * something ^ `something
                continue;
           case 101:
                DataSource = sets;
                return;
        }
        goto IL_0003;
        IL_0003:
        num = -29898;
        goto IL_0008;
       
    }

Because the "list" variable is not initialized in all cases (Project == null) so this is not compilable. 
Now even if it is not compilable it probably could still run because obviously if the data is not null it is initialized and the function at 6u is called. But what I do know is that the library function cannot run with the base code + ctrl flow. Moving the initialization above the null check creates a switch with the list initialization happening before the switch. And this runs correctly.

The error message we saw was about duplicate keys for a grid UI object which is related to the read sets. Changing only that line removes the error entirely.

**Comment by mkaring** [comment]
The goal of the control flow obfuscation isn't to produce instructions that can be converted to legal c# code. Quite the opposite. Is the code actually failing at runtime with the obfuscation is place? The sequence the instructions are actually executed in, shouldn't be changed by the obfuscation.

**Comment by mkaring** [comment]
Could the cause of the issue be, that the `ReadSets` method is called twice due to the control flow obfuscation? I am guessing that the error raised would be  a different one if `list` parameter would be passed uninitialized.

**Comment by dmanchura** [comment]
Ok so I took a look at the base dll and the ctrl flow dlls myself.
The code snippets would have been more useful if I had the full information. I've updated the root comment with this line:
DataSource = sets; which happens after going into the overloaded readSets(p,p,sets) is finshed.

What the function does is:
ReadSets(Project)
Creates sets list.
Calls ReadSets(Project,Project,list)
This function then iterates through a list of items in the project object. In the project object there are also collections and a recursive call is made to the function too. Each of the UI elements have unique serial numbers. I'm guessing this is the key used in the grid,.
It filters items that are of certain types, it then creates a set using unique names, The UI items themselves do not have unique names so a while loop appends an integer until the set does have a match. It is then added to the sets object.
So we have a for loop, about 10 conditional filters that continue to the next object, then a while loop to generate a unique name.

The original function is about 70 lines which is control flowed to almost 500 lines. I'm not suspecting that somewhere in that switch of 43 cases is adding an item twice or in the unique-naming while loop is not finding a unique name for some reason.

As mentioned I have asked the other remember to debug when he can (to see what is inside the sets object), but now that I have the raw dll I can try make a sample application doing the same steps.

If the bug is due to a duplicate it would be in this function. Too much business logic to put in but looks something like this:

    private void ReadSets(Project project, ICollection cof, List<SetInfo> sets)
    {
        foreach (IItem item2 in cof)
        {
            if (item2 is IWantType && ((IWantType)item2).IsUIItem)
            {
                if (item2 is Type1,2,3,4,5)
                {
                    continue;
                }
                if (item2.createChild() is null)
                {
                    continue;
                }
                
                if (string lookup of item 2's child cast as Type 8 is null)
                {
                    continue;
                }
                
                string item;
                string text = (item = string.Format(format, description));
                int num = 2;
                while (sets.Find((SetInfo match) => (match.Name == item) ? true : false) != null)
                {
                    item = text + "-" + num;
                    num++;
                }
                SetInfo setInfo = new SetInfo(item2.SerialNumber, item);
                sets.Add(setInfo);
            }
            else if (item2 is ICollection)
            {
                ReadSets(project, (ICollection)item2, sets);
            }
        }
    }

**Comment by mkaring** [comment]
Is there a chance that you could try the upcoming release 1.5 in your project? There are a lot of changes in this release. See if the issue persists in this release.
You can download it here: [AppVeyor - ConfuserEx](https://ci.appveyor.com/project/mkaring/confuserex/builds/37270209/artifacts)

**Comment by dmanchura** [comment]
I had asked them to debug for the duplicate bug but they have come back to me that they cannot reproduce the bug.
At this point they are releasing with just minimal set without control flow enabled.

Sorry for wasting your time.
