### ISSUE TITLE
Incorrect symbol map generating for nested classes if decodable is activated

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#296]
Consider the following code:

```cs
public class Program {
    public class Test {
        public override string ToString() => "test";
    }
}
```

I expect the following item in `symbols.map`

```
_UNGBbErDirxca0xAkREvZYr73rA	Program/Test
```

But sometimes I get the following:

```
_UNGBbErDirxca0xAkREvZYr73rA	_S85FzvPKrDzk44myGxSbATVSgRq/Test
```

**Comment by mkaring** [comment]
Define "sometimes" here. Is that a clear way to reproduce the issue?

**Comment by KvanTTT** [comment]
It depends on bypassing order. But it's always reproducible for the following sample:

```cs
namespace Test {
	public class Class {
		public class NestedClass {
			public class NestedNestedClass {
			}
		}
	}

	public class Program {
		static void Main(string[] args) {
		}
	}
}
```

I get something similar to:

```
_exWCLLT3qUyzMXM0ghLFmKELpfN	Test.Program
_D2hKrIDHaGziSLkdb00xfJz7jOu	Main
_yFMnkoMB1GXBFzsqS69VV5jbT59	Test.Class/NestedClass/NestedNestedClass
_ZmQDHyqBAaKYRvO5e1osXCKGwlY	Test.Class
_atnAP43N9XfhLVg6b194MYaPGxR	_ZmQDHyqBAaKYRvO5e1osXCKGwlY/NestedClass
_bTbvhqgppV7F4yASaVBeVByIKfL	SignatureMismatch2Helper.External
_NvD0Vp1zsPDYXMjOA42KxA6Uruc	get_Name
_9crO2X93uutIb1ckc4q6j9oDGs1	Name
```

I've found the reason and I'm going to fix this issue together with #293

**Comment by mkaring** [comment]
Seems the original name of the object is not properly stored or something like this. How ever please avoid doing too many things as part of a single pull-request. That makes checking the code and understanding the changes much more difficult.

**Comment by KvanTTT** [comment]
Ok, eventually I've decided to split this merge request because I've found more bugs in renamer that may occur in rare cases.

**Comment by KvanTTT** [comment]
Is it okay to build the map will full names including namespaces instead of short names? It seems more correct because it allows us to get rid of some conflicts where class names are equal but namespaces are different.

**Comment by mkaring** [comment]
No objection on the full name for the types. But why not also a full name for the type members? It seems cleaner to use the full name in all cases, doesn't it?

This change may also require a update to the stack decoder. This one should be able to handle both the old and the new variants for now, so it can still handle older mapping files properly.

**Comment by KvanTTT** [comment]
> No objection on the full name for the types. But why not also a full name for the type members? It seems cleaner to use the full name in all cases, doesn't it?

Yes, maybe this is even better. Also, it automatically resolves https://github.com/mkaring/ConfuserEx/issues/293 because the full name already contains method parameters. In the beginning, I thought that the full name is too surplus but not I think that's not a big problem.

> This change may also require a update to the stack decoder. This one should be able to handle both the old and the new variants for now, so it can still handle older mapping files properly.

Good remark, but it seems it's possible unambiguously to extract a short name from a full name. So, the stack decoder shouldn't be a problem.
