### ISSUE TITLE
I was able to decompile the dll that I obfuscated with ConfuserEx

### ISSUE THREAD

**Issue by mrtinkz** [mkaring/ConfuserEx#30]
First, I'd like to thank you for providing the open source software to obfuscate the dll, exe and .csproj files. I tried to protect the dll using the ConfuseEx UI application from the latest release and tried to test it to decompile using dotPeek. I could see the source as is clearly. Is there any settings I must apply to properly protect it?

**Comment by mkaring** [comment]
That sounds like you did not enable any of the protections. Open the "Settings" tab in the ConfuserEx application and add a new entry for all assemblies. Then open the new entry for configuration. Leave the pattern as it is (`true`) and set the preset to "normal" for starters.

In the configuration you can also setup the individual protections, but starting the the presets is a good idea.

**Comment by mrtinkz** [comment]
I did enabled the default protections in the settings tab and did set the preset to normal. Somehow dotPeek is able to decompile it.

**Comment by mkaring** [comment]
That shouldn't be the case. Are you absolutely positive that you are looking at the correct file? The obfuscated file is placed in a "Confused" sub-directory by default.
If you are certain, please attach your *.crproj file to this issue, so I can verify that it is properly set up.

The "normal" preset actually doesn't contain any protection that hides the code completely, but it will transform the code, hide string constants and resources and wrap the method calls in proxy methods to hide the references. Also it renames everything that is not public. The only way that wouldn't do anything is if your assembly only contains public methods that contain a single line of code each.

**Comment by MurariAlex** [comment]
@mrtinkz It won´t stop decompilers from working, except "Invalid Metadata Protection" which breaks most of decompilers (except DnSpy, which is able to bypass it), but it´s not included in normal preset I think.
Still, even if the decompiler works, the code that is shown is very... uhm.. confusing! (pun intended). 😝
Like @mkaring said, the strings should be hidden, and the code mangled e hidden by proxy calls...

**Comment by Smurf-IV** [comment]
In the past,  I have suspected that if you still have the pdb's in the original location on the same machine using dotpeek, it will go and find them and use that to perform decompilation.

**Comment by mkaring** [comment]
That is also correct. If the debug symbols are present, they contain the location of the original source files. In case they are present, dotpeek will not actually decompile anything, but just show you the original files on your system.

**Comment by mrtinkz** [comment]
You guys are absolutely correct, I removed pdb and tried decompile and code is all confusing, which is exactly what I want. I'll close this one but should the README update to exclude pdb files to avoid decompilation?

**Comment by mkaring** [comment]
The “decompilation“ using the pdb file only works because you have the original source code on your computer. Provided this is not the case for the consumers of your software, it won't work for them this way.
