### ISSUE TITLE
"Arithmetic operation resulted in an overflow" in Lzma.cs, Preventing "Confused" Application form Running

### ISSUE THREAD

**Issue by darkroastcreative** [mkaring/ConfuserEx#301]
A customer recently reported an issue with software that my team builds and maintains (and obfuscates using ConfuserEx 2) in which the application failed to start up as expected due to an overflow error thrown in "Lzma.cs" (`Confuser.Runtime\Lzma.cs`). Specifically, when the user tries to run our software either by manually running its executable or by running via scheduled task, the software is unable to start running as expected/crashes immediately and the following is printed to the console:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.OverflowException: Arithmetic operation resulted in an overflow.
    at ?????????????????????????????????(Byte[] ) in C:\projects\confuserex\Confuser.Runtime\Lzma.cs:line 42
    at .cctor()
    --- End of inner exception stack trace ---
```

My team isolated this issue to "confused" builds (and by association ConfuserEx), as a build that was built from the same source and not confused with ConfuserEx ran without issue in the customer's environment. We believe that the environment meets or exceeds the documented requirements for ConfuserEx and we have over a hundred other organizations that use the same software and have not have not experienced this issue.

When researching this issue, my team found evidence of a [similar (but slightly different) issue from the original ConfuserEx repository](https://github.com/yck1509/ConfuserEx/issues/535), but the issue was never officially resolved.

My team would like to continue to use ConfuserEx 2 to obfuscate our code and would appreciate any guidance that the maintainers may be able to provide to understand why this issue occurred and how we can prevent it in the future. Please let me know if there is any additional information that I can provide and I will follow up accordingly.

**Comment by mkaring** [comment]
I need a few additional information: What protections are you using? Can you share your `*.crproj` file? Also what version are you using exactly? Can you give me the exact version number?

**Comment by mkaring** [comment]
The error you are receiving indicates that there is a _very_ large package that is compressed. Is there anything in your assembly exceeding 2GB file size?

**Comment by mkaring** [comment]
The decryption code is not the most stable thing. I cleaned up the code a bit and removed a lot of casts that are not actually needed. The only thing that could cause the exception you are seeing is gone due to this change as well.

You could give [this build](https://ci.appveyor.com/project/mkaring/confuserex/builds/37304933/artifacts) a try and see if that resolves the issue you are facing. It may also just cause the error to change, in that case I need the new error message.

If that doesn't help I need the information mentioned above.

**Comment by darkroastcreative** [comment]
Hi, Martin! Thanks for following up so promptly. In terms of protections, we're using everything included in the "Maximum" preset with the exception of the `rename` protection, which we removed. For reference, I've attached our `*.crproj` file as `darkroastcreative.txt` (linked below). Regarding version, we are using version 1.4.1.

On your question about assembly sizes, I don't believe we are utilizing any assemblies exceeding 2GB in size.

Please let me know if there is any further information that I can provide and I'll follow up accordingly. The team appreciates your assistance!

[darkroastcreative.txt](https://github.com/mkaring/ConfuserEx/files/5831899/darkroastcreative.txt)

**Comment by mkaring** [comment]
@darkroastcreative: Could you give the build I linked above a try? The code that causes the error is changed there. Either it fixes the problem or it at least changes it to something a bit more useful. Currently I don't have a lot to go on.

**Comment by mkaring** [comment]
@darkroastcreative: Any update?

**Comment by darkroastcreative** [comment]
Hi, @mkaring, thank you for following up and apologies for the delay in response.

My team tested the new build against our local environment and didn't observe any negative impact of the changes made, but we haven't been able to test a build of our application confused with your new build in the environment where we initially observed the issue. Since the environment that spawned this issue is a customer's production environment, we need approval from the customer to make any changes in this environment. As of right now, we are still pursuing approval to do this testing (specifically, we are waiting for the customer to respond to this request). I'm hoping that we will receive a response from the customer this week so we can test in the affected environment and have feedback to share with you.

**Comment by mkaring** [comment]
@darkroastcreative: Any news on this one. The next release is due and it will be a while until the next one.

**Comment by darkroastcreative** [comment]
@mkaring My team spoke with the affected customer and, unfortunately, they indicated that the earliest that they would be willing to allow us to test a new build of our software in their environment ("confused" using the new build of ConfuserEx that you provided) would be late April. Would this fall within the development period for the release coming after the release that you're working to complete now?

**Comment by mkaring** [comment]
@darkroastcreative: We'll make it work. ;)
I will close this issue for now, because it's stale. Once you got something new: just reopen it.

**Comment by darkroastcreative** [comment]
Thank you, @mkaring! The team and I appreciate your assistance with this issue. We'll be sure to reach back out once the customer is ready to work with us on the issue further so we can provide feedback to you and your team. Apologies that we weren't able to provide good feedback on the fix this time around!
