### ISSUE TITLE
The obfused dll cannot be load:  Method 'x' in type 'xx' from assembly 'xxx' does not have an implementation

### ISSUE THREAD

**Issue by Anthony-GitHub** [mkaring/ConfuserEx#306]
Hi,

[ConfuserExTest.zip](https://github.com/mkaring/ConfuserEx/files/5828186/ConfuserExTest.zip)

This demo can reproduce the issue. There are 2 projects in this solution:

1. RenameBug1: A .NET class library that will be obfuscated with ConfuserEx. I use the Post-Build event to use ConfuserEx with configuration file ConfuserExTest\RenameBug1\confuserex.crproj. You may need to update the path for Confuser.CLI.exe in the Post-Build event.

2. ConfuserExDotNetBug: This is a test console app that uses the dll in part 1.

If I use the unobfuscated dll, then the console app works. If I use the obfuscated dll, then it will fail at runtime with error:
```
Test 'M:ConfuserExDotNetBug.Class1.Main' failed: Method 'FireLog' in type '_B._d' from assembly 'RenameBug1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
	System.TypeLoadException: Method 'FireLog' in type '_B._d' from assembly 'RenameBug1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
	at _B._f..ctor()
	RenameTest.cs(12,0): at test.Rename.PublicClass2..ctor()
	Class1.cs(6,0): at ConfuserExDotNetBug.Class1.Main()
```

It seems the method FireLog is renamed unintended.

I test this with the latest stable ConfuserEx 1.4.1

Thanks
Anthony

**Comment by mkaring** [comment]
I think that is the same issue as reported in #187. Could you give the upcoming 1.5 version a try? You can download it [here](https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts).

**Comment by Anthony-GitHub** [comment]
It's not working. The 1.5 version has the same result as ConfuserEx 1.4.1.

**Comment by mkaring** [comment]
I finally got around to fix this issue. It now works for your example, do you have a real project you can use to verify the fix?

You can download the new build [here on the buildserver](https://ci.appveyor.com/project/mkaring/confuserex/builds/37461848/artifacts).

**Comment by Anthony-GitHub** [comment]
Thank you @mkaring. It works on my real project.
