### ISSUE TITLE
JIT AntiTamper works but..

### ISSUE THREAD

**Issue by EternalData** [mkaring/ConfuserEx#308]
**Protect a file with the JIT Anti Tamper option and max protection, dump it with megaDumper you will get the raw file (non-obfuscated file)**

**Comment by EternalData** [comment]
[Dumps.zip](https://github.com/mkaring/ConfuserEx/files/5859947/Dumps.zip)

**Comment by mkaring** [comment]
Please provide the confuser project you were using. The anti tamper protection is executed after all the other protections, so it shouldn't interfere with the other protections.
