### ISSUE TITLE
snKey not working in template mode

### ISSUE THREAD

**Issue by Anthony-GitHub** [mkaring/ConfuserEx#310]
[ConfuserNotSignBug.zip](https://github.com/mkaring/ConfuserEx/files/5877737/ConfuserNotSignBug.zip)

The console prints a warning message when using the template mode:

> [WARN] [ConfuserNotSignBug.dll] SN Key or SN public Key is not provided for a signed module, the output may not be working.

The command using template mode:
```
Confuser.CLI.exe -o=test .\ConfuserNotSignBug.dll  confuserex.crproj
```
Part of the confuserex.crproj:
```
  <module path=".\ConfuserNotSignBug.dll" snKey=".\test.snk">
    <rule preset="none" pattern="namespace('ConfuserNotSignBug.Public')" >
        <protection id="rename" action="remove"/>
    </rule>
  </module>
```

With the same confuserex.crproj, it does not print this warning message if I use the normal mode with command:
```
Confuser.CLI.exe confuserex.crproj
```

The attachment can reproduce this issue. I test this with the latest code.

**Comment by mkaring** [comment]
The template mode is not matching the files to existing entries in the project file, but adds the modules passed by the command line to the file. So even your rule set will not apply to the file you passed by the module.

I'll look into that, the best way to handle this is very likely to reuse existing entries in case they reference the same file.

**Comment by Anthony-GitHub** [comment]
Hi, is there any update on this? Or is there a workaround?

**Comment by mkaring** [comment]
There isn't a work around I can think of. I know how to resolve it. I'll try to get a working build done as soon as possible.

**Comment by mkaring** [comment]
I got a build that should resolve the issue. Give it a try: [ConfuserEx - AppVeyor](https://ci.appveyor.com/project/mkaring/confuserex/builds/38100117/artifacts)

It's also now taking plugins, probe paths and external modules from the template project.
