### ISSUE TITLE
Resource protection without compression

### ISSUE THREAD

**Issue by avdevapp** [mkaring/ConfuserEx#314]
Hello.
I have one question about resource protection.

It is possible switch off only compression but encoding is still active?
How can be done? From configuration or by some modification in source code?

Any advice would be appreciated.
Thanks a lot for any help.

**Comment by mkaring** [comment]
There is currently no way to disable only the compression.

The compression and decompression is handled by two functions:
* [`Compress`](https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Core/Services/CompressionService.cs#L73) is executed when ConfuserEx is running and does exactly what is says. Just clear the content of this function and return the input `data` array, to disable the compression.
* [`Decompress`](https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Runtime/Lzma.cs#L31) handles the runtime decompression. Same thing goes here. Clear the method out and return the input array.

These two changes should get you the desired results.
