### ISSUE TITLE
Unexplainable behavior with constant strings.

### ISSUE THREAD

**Issue by miscigor** [mkaring/ConfuserEx#315]
Could you please help with the following issue.
In the latest version of ConfuserEx, something very strange was happening with constant strings.
For example, after obfuscation a WPF converter looking like this

```csharp
class TestConverter : IValueConverter {
  public object Convert(object value, ...) {
    switch (value) {
      case ...: return "A";
      case ...: return "B";
    }
  }
}
```
stopped to work. I've tried to apply `[Obfuscation(Exclude=true)]` to `TestConverter`, but it had no effect. Rewriting the method without constant strings solved the problem, but I wonder what caused it and why the attribute did not help, maybe I'm using it wrong?

Also it happened in another class method looking like `string GetName() => "N";`, again making string to be constructed dynamically resolved the problem.

**Comment by mkaring** [comment]
Please provide the full version identifier of ConfuserEx you are using. If possible also add the `*.crproj` file of your project.

In case you are using ConfuserEx 1.4.1, please give the pre-release of ConfuserEx 1.5 a shot. It contains a lot of fixes.

**Comment by miscigor** [comment]
1.5 RC fixed all the problems, thank you a lot!
