### ISSUE TITLE
Rename protection : new option

### ISSUE THREAD

**Issue by Vilo176** [mkaring/ConfuserEx#324]
Hi folks,

I'm facing an issue where a WPF Binding fails, because the Binding.Path value do not correspond to the member's name after obfuscation.

As a general coding agreement, I'm always using "nameof()" to declare bindings, so that if I change a member's name by refactoring, the binding changes accordingly (and if I change the member's name directly, the project does not compile anymore until I've changed the binding too).
But "nameof()" being evaluated at designtime, it doesn't assure me that obfuscation will not break anything ...

Sure, I could review all my code and add a decoration "[Obfuscation(Exclude = false, Feature = "-rename"]" on each members that are part of a binding.
But what would be very very convenient is the following option : as soon as a member/field/method ... is the target of a nameof() statement, it should not be renamed by obfuscation.

Any chances ?

**Comment by ElektroKill** [comment]
Sadly, since ConfuserEx modifies the assembly on the IL level after the source code is converted to the intermediate language it is not possible. `nameof()` statements are resolved and inlined to strings during the compilation stage and are not present in the .exe file. This means that ConfuserEx cannot detect these statements, so I don't think this is possible to implement.

**Comment by KvanTTT** [comment]
Maybe it's possible to implement it using some assumptions (if string equals member name then rename it). But not sure how reliable it is.

**Comment by Vilo176** [comment]
> Sadly, since ConfuserEx modifies the assembly on the IL level after the source code is converted to the intermediate language it is not possible. `nameof()` statements are resolved and inlined to strings during the compilation stage and are not present in the .exe file. This means that ConfuserEx cannot detect these statements, so I don't think this is possible to implement.

This is a very good point indeed.
What is a little weird is that, most of the time (99%), ConfuserEx will not rename a member being involved in a binding operation.

I don't know what mechanism is behind the scene, but obviously my assembly is still working after OBF, even with tones of bindings done in code behind.
But there are exceptions ... hence my post.

For now I will treat those exceptions by adding a decoration.
Thanks men for your reply.
