### ISSUE TITLE
Unable to confuse UWP class library

### ISSUE THREAD

**Issue by Vict0r-Chen** [mkaring/ConfuserEx#326]
- ConfuserEx Version: 1.5.0
- Target Framework: UWP library, Target: Win10 1809
- Operating System: Win10 2004

Error:
 [INFO] Confuser.Core 1.5.0+b5197549e4 Copyright © 2014 Ki, 2018 - 2021 Martin Karing
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 13 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading '..\..\..\MyLib\bin\x64\Release\MyLib.dll'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
[DEBUG] Executing 'Type scanner' phase...
 [INFO] Resolving dependencies...
[ERROR] Failed to resolve dependency of 'MyLib.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Windows.Foundation.UniversalApiContract, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule)
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context)
Failed at 4:46 PM, 0:00 elapsed.

**Comment by mkaring** [comment]
Getting ConfuserEx to work nice with UWP can be a challenge.

You need to manually supply the references to all the `*.winmd` files that are required to all types in the assembly as well as the probe path your local version of .NET Core 2.1 in order to resolve those assemblies.

For example your project file for ConfuserEx may look like this:
```xml
<project outputDir=".\Confused" baseDir="." xmlns="http://confuser.codeplex.com">
  <module path="MyLib.dll" />
  <module path="C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\Windows.Foundation.FoundationContract.winmd" external="true" />
  <module path="C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.UniversalApiContract\8.0.0.0\Windows.Foundation.UniversalApiContract.winmd" external="true" />
  <module path="C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0\Windows.Networking.Connectivity.WwanContract.winmd" external="true" />
  <probePath>C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.25</probePath>
</project>
```

Depending on what modules of UWP you are using, you may need to add more external references.

**Comment by Vict0r-Chen** [comment]
Thanks for reply, I currently have something at hand, I will try this after a while, thanks again.
