### ISSUE TITLE
Version 2.0 alpha not renaming

### ISSUE THREAD

**Issue by FenixDan** [mkaring/ConfuserEx#33]
Hello, I compiled my self the app and when I try to use the renamer it does nothing, just saves the assembly.

Do you know what could it be?

**Comment by mkaring** [comment]
It is renaming. Just tested it. Does you assembly contain anything it could rename? Internal members and such? Are you certain that renaming is enabled? Anything wrong with the rule pattern maybe?

**Comment by FenixDan** [comment]
I've tried the latest appveyor app and it doesn't work either.

**Comment by mkaring** [comment]
I just tested it with the very same version and renaming is working fine. Can you provide a minimal example showing your issue? So an assembly and the *.crproj file you are using to obfuscate it?

**Comment by FenixDan** [comment]
[rename.zip](https://github.com/mkaring/ConfuserEx/files/2988215/rename.zip)

I attach you a simple app I’m testing for renaming and the .crproj file.

**Comment by mkaring** [comment]
Good find. There was indeed a bug in there. Please test it with the new version build on appveyor. It actually works now.

**Comment by FenixDan** [comment]
AppVeyor failed building the app

**Comment by mkaring** [comment]
@FenixDan Just a hickup. Artifacts are available now.

**Comment by FenixDan** [comment]
Everything working as expected, thank you!
