### ISSUE TITLE
Keep getting error 

### ISSUE THREAD

**Issue by thebigjoe** [mkaring/ConfuserEx#334]
Failed to resolve a type, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.TypeResolveException: Could not resolve type:

Anyone got any idea?

**Comment by mkaring** [comment]
Too few information to do anything.

* What is the type that can't be resolved?
* What kind of assembly are you protecting?
* What is your target framework?
* What is the version of ConfuserEx you are using?
