### ISSUE TITLE
Cannot load the Strong Name Key located with Confuser.MSBuild.targets

### ISSUE THREAD

**Issue by patelvasu43** [mkaring/ConfuserEx#340]
When I build my  .net standard 2.0 library with Strong Name key  using Confuser.MSBuild with version 1.5.0
Then I am getting below error :
Cannot load the Strong Name Key located at: obj\Debug\netstandard2.0\Demo2.snk

Here my strong name key file name is Demo2.snk

.crproj file content
`<project baseDir=".\bin\Debug\netstandard2.0" outputDir=".\Confused"
	xmlns="http://confuser.codeplex.com">
	<rule pattern="true" inherit="false">
    <protection id="ctrl flow" />
    <protection id="anti tamper" />
  </rule>
  <module path="Demo2.Lib.dll" />
</project>`

It works when I put  file Demo2.snk into library path : *\obj\Debug\netstandard2.0
How can work it without put this file in obj folder.

- ConfuserEx Version: 1.5.0
- Target Framework: netstandard2.0
- Operating System: Windows 10

Steps to Reproduce:

1.   *.csproj file content

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>Demo2.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<PropertyGroup>
		<Obfuscate>true</Obfuscate>
		<ConfuserReplaceOutput>true</ConfuserReplaceOutput>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="Demo2.Lib.crproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Confuser.MSBuild" Version="1.5.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Demo2.snk">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>

**Comment by mkaring** [comment]
There is a bug in the integration. It only works properly if you supply the absolute path in the `<AssemblyOriginatorKeyFile>` tag.

To work around this issue you have to change the tag to:
```xml
<AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)Demo2.snk</AssemblyOriginatorKeyFile>
```

**Comment by patelvasu43** [comment]
@mkaring  thanks for quick solution and it is work perfect for Demo2.snk file.
If my strong name file is Demo2.pfx then it is not working.
any work around for this issue?

**Comment by mkaring** [comment]
From the top of my head I'd say that only `*.snk` files are supported at this point. I did not even know that you can strong name sign an assembly with a `*.pfx` certificate.

**Comment by patelvasu43** [comment]
Basically I have make strong name key of my assembly with password so it has generate  `*.pfx` file.
Reason to make Sign Assembly is that  I have to register this assembly in GAC and Com Component.
Anyway I will change file as `*.snk`
