### ISSUE TITLE
Method can't be obfuscated when has dynamic param

### ISSUE THREAD

**Issue by oljbo** [mkaring/ConfuserEx#345]
``` c#

        private void NewHidden(object strobj)
        {
            Console.WriteLine(strobj);
        }

        public void Test1()
        {
            NewHidden((dynamic)"test message");
        }

```

The NewHidden Method in Test1 can't renamesd!!

**Comment by mkaring** [comment]
* What version of ConfuserEx are you using? (the exakt Version number please!)
* What is the target .NET Framework you assembly is referencing?
* What configuration are you using? What protections/preset are enabled?

**Comment by oljbo** [comment]
ConfuserEx   1.5
.Net Framework 4.6.1
Os windows 10


<project outputDir="D:\tools" baseDir="D:\tools\" xmlns="http://confuser.codeplex.com">
  <module path="test.dll">
    <rule pattern="true" inherit="false">
      <protection id="rename">
        <argument name="renPdb" value="true" />
      </protection>
    </rule>
  </module>
</project>


`

using System;

namespace test
{
    public class Class1
    {
        private void NewHidden(object strobj)
        {
            Console.WriteLine(strobj);
        }
        public void Test1()
        {
            NewHidden((dynamic)"test message");
        }
        public void Test2()
        {
            NewHidden("test message");
        }
    }
}

`

The method NewHidden in Test2 can be obfuscated, but can't be obfuscated in Test1

**Comment by oljbo** [comment]
The obfuscated code is:

``` c#
public class Class1
{
	[CompilerGenerated]
	private static class \u206e\u202c\u206d\u202e\u206d\u202a\u202b\u206a\u200f\u206c\u202e\u200e\u202e\u206d\u202c\u202d\u206c\u202e\u206c\u206f\u200f\u206a\u206b\u202d\u206f\u206e\u202e\u200d\u200b\u200f\u206c\u200d\u200d\u200b\u200c\u200e\u202d\u200e\u202e\u202b\u202e
	{
		public static CallSite<Action<CallSite, Class1, object>> \u206b\u202b\u202e\u206d\u202d\u202e\u206e\u202c\u206f\u206e\u206e\u200d\u206b\u200f\u202c\u200e\u202c\u206c\u206c\u202b\u206c\u202a\u206f\u202d\u202d\u206f\u206b\u206a\u206f\u202e\u200d\u202d\u206a\u202c\u202d\u200d\u206c\u200b\u200b\u206c\u202e;
	}

	private int \u200e\u202d\u202c\u206f\u200c\u200f\u206c\u206c\u206c\u206d\u200d\u206f\u202c\u200b\u206f\u202e\u206b\u202b\u206e\u202e\u202a\u202a\u206f\u206e\u202c\u200e\u206e\u200e\u200c\u206e\u200c\u206e\u200b\u202e\u200f\u200f\u202d\u206c\u202e\u202c\u202e = 0;

	private void \u202d\u206a\u202b\u200f\u200f\u202c\u200b\u200d\u202c\u206b\u206a\u202e\u206d\u206d\u200d\u200e\u206d\u202d\u200f\u206b\u202e\u200b\u200e\u200e\u202c\u200e\u202c\u206e\u202b\u200b\u202c\u200c\u206d\u206c\u200f\u200b\u206d\u206a\u202d\u206a\u202e(object P_0)
	{
		Console.WriteLine(P_0);
	}

	public void Test1()
	{
		NewHidden((dynamic)"test message");
	}

	public void Test2()
	{
		\u202d\u206a\u202b\u200f\u200f\u202c\u200b\u200d\u202c\u206b\u206a\u202e\u206d\u206d\u200d\u200e\u206d\u202d\u200f\u206b\u202e\u200b\u200e\u200e\u202c\u200e\u202c\u206e\u202b\u200b\u202c\u200c\u206d\u206c\u200f\u200b\u206d\u206a\u202d\u206a\u202e("test message");
	}
}

```

**Comment by oljbo** [comment]
> * What version of ConfuserEx are you using? (the exakt Version number please!)
> * What is the target .NET Framework you assembly is referencing?
> * What configuration are you using? What protections/preset are enabled?

**Comment by mkaring** [comment]
I've implemented the support for the dynamic parameters in a first version.
You can download the version containing the changes [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/39182843/artifacts).

Please give it a try and get back to me if that works in your project.

**Comment by oljbo** [comment]
> I've implemented the support for the dynamic parameters in a first version.
> You can download the version containing the changes [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/39182843/artifacts).
> 
> Please give it a try and get back to me if that works in your project.


I tested it, it's work success
The obfuscated code is:

```  c#

public class Class1
{
	[CompilerGenerated]
	private static class \u206f\u200c\u200e\u200e\u206a\u206c\u206f\u200b\u202d\u200c\u202c\u206e\u200b\u202e\u202d\u200b\u206a\u206a\u200e\u202c\u202b\u206d\u206c\u206a\u206d\u202a\u206c\u202d\u202e\u200d\u206c\u202e\u202b\u200f\u206f\u202e\u200b\u202b\u206b\u200e\u202e
	{
		public static CallSite<Action<CallSite, Class1, object>> \u200b\u206d\u206d\u200c\u202d\u206e\u202d\u200e\u202c\u200d\u200c\u202b\u200d\u200d\u200f\u200c\u202b\u206a\u202b\u206d\u200c\u206e\u206b\u200f\u202c\u200c\u206a\u200b\u206c\u202e\u200f\u202d\u200f\u206c\u200b\u206f\u206b\u206c\u200d\u206c\u202e;
	}

	private void z!rJ7:j<ZK19@75NZgZ%uV&K((object P_0)
	{
		Console.WriteLine(P_0);
	}

	public void Test1()
	{
		z!rJ7:j<ZK19@75NZgZ%uV&K(((dynamic)"test message");
	}

	public void Test2()
	{
		z!rJ7:j<ZK19@75NZgZ%uV&K(("test message");
	}
}


```
