### ISSUE TITLE
"Arithmetic operation resulted in an overflow" in Lzma.cs, Preventing "Confused" Application form Running 

### ISSUE THREAD

**Issue by darkroastcreative** [mkaring/ConfuserEx#348]
Hi ConfuserEx Team,

I'm following up regarding issue #301, which I opened earlier this year but we were not able to fully resolve. Specifically, @mkaring proposed and developed a potential solution to the issue as reported and requested that my team test the solution, but we were unable to conduct this testing due to customer availability (we were not able to reproduce the issue outside of the customer's environment, hence the need for customer involvement). We are at a point where the customer is engaged and willing to helps us test a potential solution within the next few weeks. Would it be possible to receive a new build of ConfuserEx that includes the changes made in response to the original issue (#301) so we may test the changes with the customer and provide the ConfuserEx team feedback on the fix?

Please let me know if there is any further information I can provide or if you have any questions and I'll follow up as soon as possible.

**Comment by mkaring** [comment]
Welcome back :wink:

You'll find a build containing the fix, based on the latest version of ConfuserEx right [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/39139885/artifacts).

Let me know if that fixes the issue.

**Comment by darkroastcreative** [comment]
Thank you, Martin! My team is in the process of coordinating with the customer now to test the fix in the affected environment. I'll keep you posted as we clarify the timeline for that testing and as testing is conducted. 😄

**Comment by darkroastcreative** [comment]
My team has started testing a pre-release version of our software "confused" with the build you provided with the affected customer. In terms of the parameters of this test, the customer chose to clone their production server (the server which was experiencing the behavior that I originally reported) for the testing to ensure their production environment remained operational during testing.

The customer installed the pre-release version of our software this afternoon and will be using it over the next few days to confirm that the software is now functioning as expected. I'll follow up as my team receives any additional feedback from the customer and as we determine the final results.

**Comment by mkaring** [comment]
@darkroastcreative: Any update?

**Comment by darkroastcreative** [comment]
@mkaring My team received a "sign of life" from the customer after reaching out to check in and we are working to schedule a call with the customer with hopes that we can confirm the outcomes of their testing. My apologies for the time it's taking to get feedback for you and your team.

**Comment by darkroastcreative** [comment]
@mkaring I was able to speak with the customer and we confirmed that when using a build of our software confused using the pre-release version of ConfuserEx that you provided, they were unable to reproduce the original issue and use our software as expected. Is there any other feedback that my team and I can provide to help you and your team understand how the fix is working or what next steps should be?

**Comment by mkaring** [comment]
@darkroastcreative Okay, so I'll add the bugfix to the next release and we'll hope that it sticks.

I'm still not sure why this issue happend at runtime in the first place. I just "moved" the time when this issue occurs to the protection phase of ConfuserEx. So the protection fails instead of the runtime. I was expecting that you would encounter this issue. Luckly/Unfortunately (which ever way you look at it) you did not. So I don't know what else to do, to identify the original issue.

**Comment by darkroastcreative** [comment]
@mkaring, is there a timeline for when the changes you made in response to this issue will be available in a production release of ConfuserEx?

**Comment by mkaring** [comment]
There are a couple of new potential issues being tracked in the current version that is due for release. Resolving them may still take a couple of weeks. Before that is done, I will not release a new version.
Currently I'm guessing mid to late August.

**Comment by darkroastcreative** [comment]
Thanks for the update, Martin! I appreciate you sharing your anticipated timeline with me and my team. We're looking forward to adopting the fix through a production release of ConfuserEx and we'll be sure to keep you informed once we do so in terms of how the fix is working both for the customer that sparked this issue as well as our entire user base.

Thanks again for how helpful you and your team have been in working to resolve this issue!
