### ISSUE TITLE
FAQ link to wiki seems to be out of date

### ISSUE THREAD

**Issue by DaveInCaz** [mkaring/ConfuserEx#353]
In the FAQ https://mkaring.github.io/ConfuserEx/faq/ section "What about documentation?" it reads:

    Documentation is now available at the project wiki ...

The link to the wiki however goes to https://github.com/yck1509/ConfuserEx/wiki but I think should go to https://github.com/mkaring/ConfuserEx/wiki instead.

(The mkaring/... docs seem to be significantly more up to date, so its a shame if anyone uses the older ones without realizing.)

I looked in the code thinking to just fix this with a PR, but I actually didn't see where the FAQ file was located.

Thanks

**Comment by mkaring** [comment]
You are absolutely correct. I missed that one. I changed the link. You may need to clear the cache to see the change.

FYI: The pages are stored in the `gh-pages` branch of the repository.

Thank you for reporting that.

**Comment by DaveInCaz** [comment]
Thanks!
