### ISSUE TITLE
Could not resolve method/field: System.ValueTuple`2<T, System.Boolean>

### ISSUE THREAD

**Issue by elienairparronchi** [mkaring/ConfuserEx#358]
- ConfuserEx Version: 2
- Target Framework: .Net 5
- Operating System: Windows Server 2012 R2 Standard

Steps to Reproduce:

1. In the project add a method and the return is a Tuple<T, object> with a T
2. As print

Files: 
[Evidence Tuple.zip](https://github.com/mkaring/ConfuserEx/files/6634415/Evidence.Tuple.zip)

**Comment by mkaring** [comment]
Duplicates #302

The NET 5 support isn't working currently. Only .NET Framework works correctly.
