### ISSUE TITLE
Issue with name protection

### ISSUE THREAD

**Issue by zimj0** [mkaring/ConfuserEx#36]
I've successfully obfuscated an application using name protection only, but afterwards it crashes shortly after starting.  It seems activating name protection results in failure during dll loading. This happens even when using name protection with debug mode:

> System.IO.FileNotFoundException
>   HResult=0x80070002
>   Message=Die Datei oder Assembly "**ProductName.slyckugiymmwnuoiyzbzdktvmzhgb**, Culture=neutral" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
>   Source=mscorlib
>   StackTrace:
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
>    at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)
>    at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile)
>    at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)
>    at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
>    at System.IO.Packaging.Package.GetPart(Uri partUri)
>    at System.Windows.Application.GetResourceOrContentPart(Uri uri)
>    at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
>    at _ProductName.App.App.⁮‍⁭‍⁯‌⁮​‭⁪⁫‫‬⁫⁪⁪⁪​​⁯​⁯⁬‫⁬‍‪⁪‎⁫‫‎‪‮‮⁮⁬⁭‫‌‮(Object , Uri )
>    at _ProductName.App.App._InitializeComponent()
>    at _ProductName.App.App._Main()

The application is targeting .NET 4.6.

**Comment by mkaring** [comment]
What version of ConfuserEx are you using? The current release or the ´release/2.0` branch?
Did you only enable the `rename` protection or also a preset?

From the looks of it something is wrong with the renaming in relation to WPF. Can you share the obfuscated assembly for analysis?

**Comment by zimj0** [comment]
I'm using version 1.1 (Confuser.Core 1.1.0+a36320377a).
Unfortunately, I can't share the assembly, but I will try to create a MWE.

**Comment by zimj0** [comment]
Turns out the problem is caused by a ResourceDictionary in the App.xaml, which points to a ResourceDictionary in a referenced assembly:
>    <Application.Resources>
>        <ResourceDictionary>
>            <ResourceDictionary.MergedDictionaries>
>                < ResourceDictionary Source="pack://application:,,,/ExampleDll;component/Resources.xaml" />
>            </ResourceDictionary.MergedDictionaries>
>        </ResourceDictionary>
>    </Application.Resources>

If the executable is obfuscated, I observe an exception as posted above.
If only the referenced assembly (ExampleDll) is obfuscated, the exception is different:

> Ausnahmeinformationen: System.Windows.Markup.XamlParseException
>    bei System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
>    bei System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
>    bei System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
>    bei System.Windows.Application.LoadComponent(System.Object, System.Uri)
>    bei ProductName.App.InitializeComponent()
>    bei ProductName.App.Main()

**Comment by mkaring** [comment]
I found a bug, but I am not sure if it's the one you are affected by. Could you please test it with the new build you can download [here][1]?

If that is not working for you, could you please send me your minimal working example? Just pack it along with the *.crproj file so I have the same test base.

[1]: https://ci.appveyor.com/project/mkaring/confuserex/builds/23578676/artifacts

**Comment by zimj0** [comment]
Unfortunately, the problem persists with that version.
This is the [MWE.zip](https://github.com/mkaring/ConfuserEx/files/3043247/MWE.zip)

**Comment by mkaring** [comment]
Sadly there is no trivial fix for this issue. The problem is that the referencing of compiled WPF resources doesn't work cross assemblies and changing this is a major change.
I am not planning to do changes to this extend in the 1.x branch of ConfuserEx.

Your case will be covered in the 2.x branch.

As a workaround, the only way to go is to disable XAML renaming in the assemblies that contain the referenced XAML file. To do so you have to alter the ConfuserEx project file (*.crproj) like this:
```XML
<project outputDir=".\Confused" baseDir="." xmlns="http://confuser.codeplex.com">
  <rule pattern="true" inherit="false">
    <protection id="rename" />
  </rule>
  <module path="Interface.dll">
    <rule pattern="true">
      <protection id="rename">
        <argument name="renXaml" value="false" />
      </protection>
    </rule>
  </module>
  <module path="WebAppTestApp.exe" />
</project>
```

The important bit is that the `renXaml` argument is set to `false` for the `rename` protection of the assembly that contains the XAML file you are referencing from outside. This will stop ConfuserEx from renaming the XAML resources.

**Comment by zimj0** [comment]
Thanks, that worked.
