### ISSUE TITLE
Error DeserializeObject Json

### ISSUE THREAD

**Issue by drnxloc** [mkaring/ConfuserEx#371]
[obf bupdate.zip](https://github.com/mkaring/ConfuserEx/files/6730852/obf.bupdate.zip)

- ConfuserEx Version: 1.5.0
- Target Framework: 4.8
- Operating System: Windows 10

when I use: JsonConvert.DeserializeObject<DataType>(jsonType) , it doesn't work correctly. original json:
{
     "name": "Tool",
     "type": "tool",
     "version": "1.0.7",
     "summary": "vip",
     "link": "https:\/\/domain.com",
     "file_name": "app.zip",
     "date_update": "06-06-2021"
}
After DeserializeObject and SerializeObject and the result is null
{"name":"Tool","type":"too","version":"1.0.7","⁪‌‎⁯⁯⁯⁯‍⁯⁪⁬⁬ ‎⁬‍⁯⁯⁬‌‍⁬⁫‏⁫":null,"‎‏‎⁭‌⁭‏‎⁬‏‏⁪⁮‌‏⁮​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ ​‏‌‎⁯":null,"⁯‎⁯ ⁭‍‌⁭⁮⁯⁫⁪‌​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ ‎⁯⁮":null,"⁪⁪‌⁭⁫⁪​⁫⁭‎​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ ‌":null}
This error occurs when using confuser

**Comment by mkaring** [comment]
Without any information, how the C# part of things is set up, it's impossible to say what is wrong here.
Have you tried reducing the protections to see what is actually causing the issue? The `typescrambler` and `name` protections are candidates that may cause the issue.

Do you have a minimal example that shows the error?

**Comment by drnxloc** [comment]
I removed as you said, typescrambler and name protections, here is the sample project causing the error, including the file obf.crproj
You can run this project and check for errors
https://github.com/drnxloc/json-test

**Comment by drnxloc** [comment]
![image](https://user-images.githubusercontent.com/62972447/124227441-df88d100-db34-11eb-9ec5-1a170940555d.png)

**Comment by drnxloc** [comment]
I found the rename option causing the error, thanks
