### ISSUE TITLE
Confusing the assembly is too slow.

### ISSUE THREAD

**Issue by EircYangQM** [mkaring/ConfuserEx#373]
I have the same issue with Catester. Please check this link https://github.com/yck1509/ConfuserEx/issues/600. I have been fix the issue in local code. Maybe it could merge to the current version.

**Comment by mkaring** [comment]
I added the changes. You can get the modified version [here](https://ci.appveyor.com/project/mkaring/confuserex/builds/39993326/artifacts). Let me know if this improves it for you.

**Comment by wmjordan** [comment]
I has tried this. It performs at least 10 times faster on my computer.
I have not yet verify whether the results are correct.

**Comment by wmjordan** [comment]
I put the output files on to my servers, they have been running for about a week.
And another desktop application are released to the public.
Both of those projects have used complicated design patterns in the source code.

Things are still OK. No one complains anything wrong.

I think #374 is safe to be merged.
