### ISSUE TITLE
Generic parameter sometimes not renamed in class method that implements an interface

### ISSUE THREAD

**Issue by dmirmilshteyn** [mkaring/ConfuserEx#38]
I have an odd case where the override IL declaration for a method that implements an interface method does not have the generic parameter of the return type renamed. This only happens sometimes, though. Running Confuser for identical inputs (same project file/input assemblies) sometimes correctly does the rename, and other times it doesn't. I haven't been able to identify what triggers this, other than just rerunning Confuser until it fails to rename (although it's fairly frequent).

The class that implements the interface is in assembly A, while the interface itself is in assembly `Dep`. Public member renaming is enabled. 

This results in a TypeLoadException when trying to run the program/access the type:

`Unhandled Exception: System.TypeLoadException: Type '_hEn8b4s8oBY1jgZcQVQz4THS2ij' from assembly 'ConfuserTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' tried to override method '_dmsD4dyBswIfo0cd1FveEj2vUhX' but does not implement or inherit that method.
   at _i3zNHiwCYlitdxpMvsALWfmv8OM._tZQC7BOe6PSavpqbssDocOJC0W7(String[] )`

Below is a screenshot of what I mean. `_c4N69m2rOXJXyRZw1HwXxNcEk7c` corresponds to `Dep.IB`.

![image](https://user-images.githubusercontent.com/9707562/55697684-75524780-5990-11e9-9964-b19e22ccc264.png)

The corresponding code:
```
class A : Dep.IA<Dep.IB>
{
    public Dep.IB Test(int a, string b, Dep.IB t) {
        return default;
    }
}
```

Version: 2.0-master
Example: [ConfuserTest.zip](https://github.com/mkaring/ConfuserEx/files/3052573/ConfuserTest.zip)

**Comment by mkaring** [comment]
I'm able to reproduce the issue even in the 1.x branch.

**Comment by mkaring** [comment]
This is fixed.
