### ISSUE TITLE
A hybrid protection mode of symbol map and reversible password

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#382]
In #375 , we discussed that:
1. using symbol map files can cumulatively add up to a good pile after compilations, but the output files are relatively smaller;
2. reversible password protection generates longer encoded symbol names, however, we don't have to keep a lot of map files.

Is it possible to bring those two together?
The symbol names are renamed to names as short as possible like the map file mode,
the map file is stored somewhere in the output file, encrypted by a password.
Ideally, the offset of the map file can vary a bit according to the provided password.

Having the right password, we can use the ConfuserEx's stack trace decoder tool to read the map inside the assembly and decode the stack trace.

**Comment by mkaring** [comment]
This would surely be possible to store the map file, password protected and compressed inside the assembly. How ever this has one massive disadvantage over the current reversible mode: to decode the stack trace you need access the the assembly that created the stack trace.

**Comment by KvanTTT** [comment]
It is definitely possible to optimize size for `reversible` mode without depending on assembly since it only considers short names for members (methods, fields, properties) and for nested classes, see how method [ExtractShortName](https://github.com/mkaring/ConfuserEx/blob/master/Confuser.Renamer/MessageDeobfuscator.cs#L62) works: only strings after `::` and after `/` are required for decryption.

**Comment by wmjordan** [comment]
> to decode the stack trace you need access the the assembly that created the stack trace.

@mkaring Thank you for the remarks! I forgot what I did when I encountered errors on my servers. When that happens after adopting this mode, I not only have to copy the trace, but also the assembly file! Oh, yes, it is really inconvenient. I will drop this suggestion.

**Comment by wmjordan** [comment]
> I can try to implement it this weekend.

Thank you @KvanTTT. I look forward to your optimization.
