### ISSUE TITLE
Obfuscation cannot handle reflections

### ISSUE THREAD

**Issue by Mighty00** [mkaring/ConfuserEx#39]
The Obfuscator can't handle reflections within the Assembly since it doesn't check for reflections before renaming.

Example: typeof(Program).GetMethod("HelloWorld"); will throw a NullReferenceException, because the "HelloWorld" method gets renamed after Obfuscation (if Renaming Feature is enabled).

Solution: Add a reflection analyzer to cex using blocks and analyze all methods before renaming them

Test files (unobf & obfed):
[TestFile.zip](https://github.com/mkaring/ConfuserEx/files/3077941/TestFile.zip)

**Comment by mkaring** [comment]
I can change the renaming to cover this simple case. How ever in general you should't allow ConfuserEx to rename a method you are accessing using reflection, by disabling renaming using the [`ObfuscationAttribute`][1] like this:
```C#
[Obfuscation(Exclude=false, Feature="-rename")]
void HelloWorld() {
  …
} 
```
Or by adding a rule to the Confuser Project (`*.crproj`) that disables renaming for the specific method. 

[1]: https://docs.microsoft.com/de-de/dotnet/api/system.reflection.obfuscationattribute

**Comment by mkaring** [comment]
@Mighty00 The enhancement has been implemented and is supported in this [feature build][1]. It would be great if you could confirm that it works in your specific case. The improvement will be part of the 1.2 release.

[1]: https://ci.appveyor.com/project/mkaring/confuserex/builds/24152509/artifacts

**Comment by Mighty00** [comment]
Renaming works good now. But you should also add support for GetILAsByteArray reflection method, since other protection modules could change the bytes of a method body

**Comment by mkaring** [comment]
[`GetILAsByteArray`][1] is still working, as refetching the required `MethodInfo` is now working again. Detecting exactly what you are doing with that `MethodInfo` is very difficult. Also the function will still work, but it will receive the obfuscated code. If you code is relying on the IL code of a method being not obfuscated, that is a method you **really** should exclude from obfuscation.

[1]: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbody.getilasbytearray?view=netframework-4.7
