### ISSUE TITLE
Resource protection without compression

### ISSUE THREAD

**Issue by BBUBBA** [mkaring/ConfuserEx#395]
https://github.com/mkaring/ConfuserEx/issues/314

My app Run this Step..

1. start normal user -> Process start runas admin
2. start admin user -> ProcessstartasSystemUser.
3. start System user..

When i use Resource Protection.. My App need 7 sec for start.
if skip Resource Protection. My app can start 1 sec..

so can you Make Skip Compression flag about Resource Protection?

Thank you~! Mr. Karing and ConfuerEx Team.

( Sorry About my english is Not good. ^^;; )

Have a nice day ^^

**Comment by KvanTTT** [comment]
What if just disable resource protection?

**Comment by BBUBBA** [comment]
It works if I turn off resource protection,
However, DnSpy can view the resource.

So I am using it after manually fixing it.

**Comment by mkaring** [comment]
The compression is hard implemented into the resource protection as of right now. This is going to change with the 2.0 version of ConfuserEx, that will allow to change and disable the compression using parameters.
How ever this version is not yet done and will still take some time.

**Comment by BBUBBA** [comment]
Thank you !!! Reply to me ^^

Looking forward to the new version.
