### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by helloBmark** [mkaring/ConfuserEx#4]
Hello,
I got the error

`CS1061	'Importer' does not contain a definition for 'Resolver' and no accessible extension method 'Resolver' accepting a first argument of type 'Importer' could be found (are you missing a using directive or an assembly reference?)`

Am I missing something? Or do I use wrong dnlib version?

**Comment by mkaring** [comment]
That is the wrong version of dnlib. You have to use my fork of dnlib. It is fully up to date with the version of original version of @0xd4d, but it contains a couple of additional modifications that are required to get ConfuserEx working.

**Comment by mkaring** [comment]
@helloBmark Did you get it working?

**Comment by helloBmark** [comment]
@mkaring yeah, it works fine for me now. Thank you for your support.
