### ISSUE TITLE
No pdb generated

### ISSUE THREAD

**Issue by uecasm** [mkaring/ConfuserEx#405]
- ConfuserEx Version:
   ```
   [INFO] Confuser.Core 1.5.0+b5197549e4 Copyright c 2014 Ki, 2018 - 2021 Martin Karing
   [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
   ```
- Target Framework: 4.6.2

Steps to Reproduce:

```
[assembly: Obfuscation(Exclude = false, Feature = "generate debug symbol: true")]
[assembly: Obfuscation(Exclude = false, Feature = "preset(minimum);-anti debug;")]
```

```
cd bin\Release
Confuser.CLI -n -debug -o=%CD%\..\Confused %CD%\TestApp.exe
```

There is no pdb file generated in the Confused output directory.  There was one in the input directory.

(Also I'm not sure if I need both `-debug` on the command line and the attribute; I've tried each individually and together but there's still never a pdb file.)

**Comment by mkaring** [comment]
Can you provide a minimal example that doesn't work for you? I just tested it with one of my projects and the debug symbols are correctly transformed and copied over.
