### ISSUE TITLE
Overwrites the input dll instead of writing to output folder if full input module path given

### ISSUE THREAD

**Issue by ClearCutDevel** [mkaring/ConfuserEx#413]
- ConfuserEx Version: 1.5
- Target Framework:
- Operating System: Win 10

Steps to Reproduce:

instead of

```xml
<module path="some.dll">
```

put the dll in some other folder and specify the path like:

```xml
<module path="C:\path\some.dll">
```

When saving ConfuserEx will overwrite the input .dll as opposed to writing it out to the output folder.

**Comment by mkaring** [comment]
There are information missing in your description. Maybe screenshots or something like this?

**Comment by mkaring** [comment]
Nevermind. Found the missing parts.

**Comment by mkaring** [comment]
A version containing a fix for this issue is available [on the buildserver](https://ci.appveyor.com/project/mkaring/confuserex/builds/41942304/artifacts). Give it a try and tell me if that fixes the issue for you.
