### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by helloBmark** [mkaring/ConfuserEx#42]
Hi,

I got this error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\dnlib\src\bin\Debug\netstandard2.0\dnlib.dll' could not be found	Confuser.Core.Exports	D:\VisualStudio\confuserEX2\Confuser.Core.Exports\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\dnlib\src\bin\Debug\netstandard2.0\dnlib.dll' could not be found	Confuser.Renamer.Exports	D:\VisualStudio\confuserEX2\Confuser.Renamer.Exports\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\dnlib\src\bin\Debug\net461\dnlib.dll' could not be found	Confuser.Helpers (net461)	D:\VisualStudio\confuserEX2\Confuser.Helpers\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\dnlib\src\bin\Debug\netcoreapp2.1\dnlib.dll' could not be found	Confuser.Helpers (net461)	D:\VisualStudio\confuserEX2\Confuser.Helpers\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\dnlib\src\bin\Debug\net461\dnlib.dll' could not be found	Confuser.Utilities (net461)	D:\VisualStudio\confuserEX2\Confuser.Utilities\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\dnlib\src\bin\Debug\netcoreapp2.1\dnlib.dll' could not be found	Confuser.Utilities (net461)	D:\VisualStudio\confuserEX2\Confuser.Utilities\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\Confuser.Helpers\bin\Debug\netcoreapp2.1\Confuser.Helpers.dll' could not be found	Confuser.Core (net461)	D:\VisualStudio\confuserEX2\Confuser.Core\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\Confuser.Utilities\bin\Debug\netcoreapp2.1\Confuser.Utilities.dll' could not be found	Confuser.Core (net461)	D:\VisualStudio\confuserEX2\Confuser.Core\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\dnlib\src\bin\Debug\netcoreapp2.1\dnlib.dll' could not be found	Confuser.Core (net461)	D:\VisualStudio\confuserEX2\Confuser.Core\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\Confuser.Helpers\bin\Debug\net461\Confuser.Helpers.dll' could not be found	Confuser.Core (net461)	D:\VisualStudio\confuserEX2\Confuser.Core\CSC	1	Active
Error	CS0006	Metadata file 'D:\VisualStudio\confuserEX2\dnlib\src\bin\Debug\net461\dnlib.dll' could not be found	Confuser.Core (net461)	D:\VisualStudio\confuserEX2\Confuser.Core\CSC	1	Active
Error		Unable to locate repository containing directory 'D:\VisualStudio\confuserEX2\dnlib\src'.	dnlib	C:\Users\Admin\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	
Error		Unable to locate repository containing directory 'D:\VisualStudio\confuserEX2\dnlib\src'.	dnlib	C:\Users\Admin\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	
Error		Unable to locate repository containing directory 'D:\VisualStudio\confuserEX2\dnlib\src'.	dnlib	C:\Users\Admin\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	

```

Did I miss something?

Thank in advance.

**Comment by ElektroKill** [comment]
You are missing the sub modules, open a command prompt in the folder of the repository and run:
`git submodule update --init --recursive`
This will clone the sub modules which include dnlib and antinet.
You can also just use the appveyor build.

**Comment by helloBmark** [comment]
> You are missing the sub modules, open a command prompt in the folder of the repository and run:
> `git submodule update --init --recursive`
> This will clone the sub modules which include dnlib and antinet.
> You can also just use the appveyor build.

Thank you,
I still have the error :( 
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ImportMapper' could not be found (are you missing a using directive or an assembly reference?)	Confuser.Helpers (net461)	D:\VisualStudio\confuserEX - mkaring\Confuser.Helpers\InjectHelper_Injector.cs	14	Active
Error	CS0115	'InjectHelper.Injector.Map(ITypeDefOrRef)': no suitable method found to override	Confuser.Helpers (net461)	D:\VisualStudio\confuserEX - mkaring\Confuser.Helpers\InjectHelper_Injector.cs	408	Active
Error	CS0115	'InjectHelper.Injector.Map(MethodDef)': no suitable method found to override	Confuser.Helpers (net461)	D:\VisualStudio\confuserEX - mkaring\Confuser.Helpers\InjectHelper_Injector.cs	420	Active
Error	CS0115	'InjectHelper.Injector.Map(FieldDef)': no suitable method found to override	Confuser.Helpers (net461)	D:\VisualStudio\confuserEX - mkaring\Confuser.Helpers\InjectHelper_Injector.cs	429	Active
`

**Comment by mkaring** [comment]
There is some mismatch between the branch of ConfuserEx and the branch of dnlib. Make sure the referenced submodule is properly up to date. After you updated the submodules make sure to "rebuild" everything.

You can check if the submodules are synced up by checking the `git status` of the main repository. It shouldn't list dnlib as changed.

**Comment by helloBmark** [comment]
I still can not build it. If it's possible, please upload built versions. Thank you.

**Comment by mkaring** [comment]
The build versions are uploaded so you can use them. There is the release build on github [here][1] and there are the artifacts on the buildserver [here][2]

[1]: https://github.com/mkaring/ConfuserEx/releases
[2]: https://ci.appveyor.com/project/mkaring/confuserex/branch/release/2.0/artifacts
