### ISSUE TITLE
DLL Not found error.. When Protecting exe with confuserEx

### ISSUE THREAD

**Issue by RiteshMehtaIndia** [mkaring/ConfuserEx#420]
- ConfuserEx Version: 1.5.0.97
- Target Framework: 4.5
- Operating System: Windows 10

Steps to Reproduce:

Hi

[SampleDIr.zip](https://github.com/mkaring/ConfuserEx/files/7315177/SampleDIr.zip)

I'm attaching Directory to check this at your end. (SampleDir.zip)

This Exe basically use DevExpress Reporting components and print report files.

This directory contain 2 exe's

    1) Exe without confuser protection
    2) Exe with confuser protection

If you run exe NO. 1, then all type of print works fine

If you run exe no. 2,

    Print 1 works fine 
    **_Print 2 failed dll error._**

Also, attached CrossTabIssue.zip (which contains source code of above exe)
[CrossTabIssue.zip](https://github.com/mkaring/ConfuserEx/files/7315179/CrossTabIssue.zip)

**Comment by mkaring** [comment]
Both the protected and unprotected versions raise the same missing DLLs errors for me. Both applications crash instantly when clicking any button.

**Comment by RiteshMehtaIndia** [comment]
Hi There Kindly refer below ticket, which I raised with DevExpress Team.https://supportcenter.devexpress.com/ticket/details/t1035303/could-not-find-dll-error The said issue arises whenYou build exe in VB.NetIn runtime, you append some script which is written in C#    Kindly read above ticket carefully, it will help you trace exact cause. Also, refer below similar ticketshttps://supportcenter.devexpress.com/ticket/details/t416360/problem-with-vb-scripting-and-referenced-obfuscated-dll  I’m ready to help you and repeat the same issue in your pc. For this, I need online access of your PC. Regards,Ritesh Mehta  Sent from Mail for Windows From: github-actions[bot]Sent: 06 January 2022 09:43To: mkaring/ConfuserExCc: RiteshMehtaIndia; AuthorSubject: Re: [mkaring/ConfuserEx] DLL Not found error.. When Protecting exe with confuserEx (#420) This issue needs more information and has not had recent activity. Please provide the missing information or it will be closed in 7 days. Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mkaring** [comment]
This kind of scripting may be affected by ConfuserEx due to the renaming.
That being said, I think the main issue is that the declarations inside the DLL are broken in the "Confuser" version.

This does not look like anything I've seen before.

Also I found that the two DLLs do not line up. There was something else modifying the assembly beside ConfuserEx. In the confused version there is a `AritoCrypto` attribute present. This one doesn't exist in the original version.
What is the source of this attribute?

**Comment by RiteshMehtaIndia** [comment]
- I Changed Project Title to "AritoCrypto". But it might not be issue, since I checked above issue in fresh version also.
- You are right regarding inside declarations.
- Let me more specific

1. We have ERP Software which is developed using VB.Net
2. Recently, We have add-on Tool **DevExpress Winforms** (https://www.devexpress.com/products/net/controls/winforms/)
3. In their tool, the provide End-User Report Designing Tool.
4. In Said tool, they provide facility to write end-user script.
5. If above end-user script, we write in C# then Confuser is working fine.
6. But If we write the in VB.Net, then Confuser is creating issue.

I'm ready to repeat issue at your end.

Regards,
Ritesh Mehta

**Comment by RiteshMehtaIndia** [comment]
Download supporting dll from below link
https://we.tl/t-yausjP4Lkk

And dump all dll into root folder of my sample project.

**Comment by mkaring** [comment]
You did not understand me.

There is an attribute declared in the non-functioning assembly:
```cs
using System;

// Token: 0x02000016 RID: 22
internal class AritoCrypto : Attribute
{
	// Token: 0x06000072 RID: 114 RVA: 0x00002524 File Offset: 0x00000724
	public AritoCrypto(string A_1)
	{
	}
}
```

Where does this come from?

**Comment by RiteshMehtaIndia** [comment]
I can not help much regarding above code snip.

Regarding "AritoCrypto".. as I already said, I downloaded source of your project and did some title modifications.

And changed project title to "AritoCrypto".

**Comment by mkaring** [comment]
Also the versions of the files you just send, do not line up with the versions in the original project. Please recreate a _working_ example of the issue, otherwise there is nothing I can do.

**Comment by mkaring** [comment]
The code snip of the attribute is from _your_ assembly. This attribute is declared in the `CrossTabIssue CONFUSER.exe` file. It's not present in the `CrossTabIssue.exe` file. This means something modified the `CrossTabIssue CONFUSER.exe` aside from ConfuserEx.

**Comment by RiteshMehtaIndia** [comment]
Send you directory, in which error repeating

https://we.tl/t-G3JKF6SE0b

Please try it

**Comment by RiteshMehtaIndia** [comment]
![Confusor error](https://user-images.githubusercontent.com/92203777/148372270-7e2138e8-267e-4f39-a5a2-cfc0c8d21cc1.gif)

Recording of error at my end

**Comment by mkaring** [comment]
Okay, so the cause of the error is the visual basic compiler crashing when processing the assembly. This issue is caused by the presence of the `constants` protection. Obfuscated assemblies aren't working well as reference for an compiler.

**Comment by RiteshMehtaIndia** [comment]
Can it be fix in upcoming updates ?

**Comment by mkaring** [comment]
No. The way this protection works, breaks the old visual basic compiler.

**Comment by RiteshMehtaIndia** [comment]
The same issue occurs, if we compile internal VB code unit using the Roslyn API instead of CodeDOM ?

**Comment by mkaring** [comment]
It's very unlikely that the Roslyn implementation has the same issue.
