### ISSUE TITLE
Internalize certain namespaces

### ISSUE THREAD

**Issue by LaraSQP** [mkaring/ConfuserEx#424]
First of all, **thank you**, Mr. Karing, you are a freaking hero for picking up this project and keep it going.

Now, to the issue.

Would it be possible to mark certain namespaces as internal (although their API's are public) to the overall build so as to "hide" their interfaces?

In case the question is unclear (sincere apologies), please ask for details.

**Comment by LaraSQP** [comment]
OK.

Tests with simple mock namespaces work are obfuscated as expected with nothing more than the `Name Protection`.

So internalizing is clearly happening.

Could anyone think of a reason why this is not so in complex scenarios?

**Comment by LaraSQP** [comment]
Talking to myself here.

The problem must be that the code targets .Net Core 3.1 and the NETStandardLibrary 2.0.3

Maybe this could help:

https://github.com/mkaring/ConfuserEx/issues/311

**Comment by LaraSQP** [comment]
I've made some tweaks to my code (though still .Net Core 3.1) and ConfuserEx actually does the job.

Incredible.

Done.

**Comment by mkaring** [comment]
Glad I could help :wink:

Just for completeness sake, the answer to the initial question:
ConfuserEx is not renaming any public facing members/types unless the [`renPublic` option](https://github.com/mkaring/ConfuserEx/wiki/Name-Protection) is set to `true`.
If you want the types inside specific namespaces to be renamed, you can declare a rule, that enables this option for specific namespaces:

```xml
<rule pattern="namespace('My.Internal.Namespace')">
  <protection id="rename">
    <argument name="renPublic" value="true" />
  </protection>
</rule>
```

The argument to the [`namespace` pattern](https://github.com/mkaring/ConfuserEx/wiki/Expression-Functions#namespacestring) function is a regular expression. So you have some freedom there.

**Comment by LaraSQP** [comment]
You rock.
