### ISSUE TITLE
Integration with ILMerge

### ISSUE THREAD

**Issue by ElektroKill** [mkaring/ConfuserEx#43]
Would it be possible to add Integration with ILMerger into ConfuserEx?
perhaps it could come in the form of a packer.

**Comment by MurariAlex** [comment]
Tracked by issue #23 already.

**Comment by mkaring** [comment]
Indeed. This is a planned feature for ConfuserEx 2. How ever it will not utilize ILMerge, since ConfuserEx already contains it's own implementation for merging assemblies that is used for merging the runtime components.
