### ISSUE TITLE
In Name Protection, renPublic parameter seems to be missing

### ISSUE THREAD

**Issue by jorgemrsantos** [mkaring/ConfuserEx#44]
I may be missing something here.

If I activate Name Protection, all classes are being renamed, including public ones (I wanted public classes to keep their name and namespace) even though the default of the [renPublic](https://github.com/yck1509/ConfuserEx/wiki/Name-Protection) parameter is false.

After checking the code there seems to be no renPublic parameter implemented:
```
internal sealed class NameProtectionParameters : ProtectionParametersBase {
		internal IProtectionParameter<bool> RickRoll { get; } = ProtectionParameter.Boolean(rickRoll, false);
		internal IProtectionParameter<bool> RenameArguments { get; } = ProtectionParameter.Boolean("renameArgs", true);
		internal IProtectionParameter<bool> RenamePdb { get; } = ProtectionParameter.Boolean("renPdb", false);
		internal IProtectionParameter<bool> FlattenNamespace { get; } = ProtectionParameter.Boolean("flatten", true);
		internal IProtectionParameter<RenameMode> Mode { get; } = ProtectionParameter.Enum("mode", RenameMode.Unicode);
		internal IProtectionParameter<string> Password { get; } = ProtectionParameter.String("password", "");
		internal IProtectionParameter<bool> ForceRename { get; } = ProtectionParameter.Boolean("forceRen", false);
		internal IProtectionParameter<uint> IdOffset { get; } = ProtectionParameter.UInteger("idOffset", 0);

		internal IProtectionParameter<string> SymbolMapFileName { get; } =
			ProtectionParameter.String("mapFileName", "symbols.map");

		internal IProtectionParameter<bool> RenameXaml { get; } = ProtectionParameter.Boolean("renXaml", true);
	}
````

How can I rename only non public classes?

**Comment by mkaring** [comment]
In the 2.0 branch it is gone. That is correct. You can get the same behavior by applying the rename protection only to a rule applying to non public members.

**Comment by jorgemrsantos** [comment]
Oh, nice!
Can you please help me with an example of how to set it up in a project file?
Looking through the xsd I wasn't able to figure it out.

**Comment by mkaring** [comment]
The reference project you are using will work fine with the ConfuserEx 1.x branch. So you can use the [ConfuserEx 1.1.0 Release][1]. If you want to use it yourself you can use the `master` branch.

If you want to use the ConfuserEx 2.x branch, you can do so, but you have to add another rule to avoid renaming of public stuff. That can be done by adding a rule like this:
```XML
<rule pattern="not is-public()" preset="none">
    <protection id="rename" >
      <argument name="flatten" value="false"/>
      <argument name="renameArgs" value="false"/>
    </protection>
</rule>
```
Add this and remove the rename protection from the rule with the pattern `"true"` and it will work as you expect it.

The pattern are currently not very well documented. You'll find the parser located [here][2]. You can review the lexer instructions there to get an idea what those pattern are.

Also I noticed that you are using the `"jit"` mode for the `anti tamper` protection. This mode is very unsafe and depends on the implementation of the JIT on the executing system. If it works for you that is okay, but in general I do not recommend using it.

[1]: https://github.com/mkaring/ConfuserEx/releases/tag/v1.1.0
[2]: https://github.com/mkaring/ConfuserEx/tree/release/2.0/Confuser.Core/Project

**Comment by jorgemrsantos** [comment]
Thanks for the tip on the anti tamper mode!
I decided to try to go forward with some small customization of the RenamePhase so that all public artifacts keep their names, including Events and Fields as I want others to be able to use all things that are public but I'm running into some difficulties with Enum but I'll move this to another thread.
