### ISSUE TITLE
How can I prevent Enums from being renamed?

### ISSUE THREAD

**Issue by jorgemrsantos** [mkaring/ConfuserEx#45]
I decided to try to go forward with some small customization of the RenamePhase so that all public artifacts keep their names, including Events and Fields as I want users of my obfuscated dlls to be able to reference all things that are public but I'm running into some difficulties with Enum.

When going through all the obfuscation targets: foreach (var def in target)
the target list doesn't seem to have the Enums in there although their names are being obfuscated.

Can you help me find where the Enums are being renamed?

**Comment by mkaring** [comment]
If you want to modify the renaming process I'd suggest to register a new [`IRenamer`][1] at this point in the [`NamingService`][2]. These renamers are able to process all types and members and are expected to set the "CanRename" flag using [`INamingService.SetCanRename`][3]. This way the renaming of a specific type or member can be disabled. You find the default implementations of those renamers [here][4]. The Enums are in the end just types and their members are static fields.

This should also work using the default version of ConfuserEx using the pattern. `is-public()` should trigger on all types and members that are visible outside if you assembly. Meaning all public members that are in public types (in case of type nesting, all types have to be public) and it should also trigger on all protected members. If it does not, something is wrong. If you need help there I need more details on the visibility structure of the code you are trying to obfuscate.

The pattern are pretty confusing right now, and I am planning to extend them and change their behaviour a bit to make it clearer what they are expected to do, as the current `is-public()` should rather be called `is-visible-outside()` 

[1]: https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Renamer.Exports/IRenamer.cs
[2]: https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Renamer/Services/NameService.cs#L42
[3]: https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Renamer.Exports/Services/INameService.cs#L38
[4]: https://github.com/mkaring/ConfuserEx/tree/release/2.0/Confuser.Renamer/Analyzers

**Comment by i00** [comment]
I think that ConfuserEx should be made to respect the System.Reflection.Obfuscation attribute.

**Comment by mkaring** [comment]
The 1.x version (`master` brach) does not rename public members by default and the 2.x version is planned to do so, but in a different way. Currently the 2.x version doesn't do this by default.

Both versions respect the `Obfuscation` attribute.

**Comment by i00** [comment]
> the 2.x version is planned to do so, but in a different way

What does this mean?? ... and this seems like a really bad idea IMHO
