### ISSUE TITLE
Is there any difference between 'normal' and 'aggressive' presets ?

### ISSUE THREAD

**Issue by elkoiko** [mkaring/ConfuserEx#450]
Hello,

First of all, thanks to everyone contributing to this amazing project ! 🙏

While reading the documentation I wanted to figure out the differences between the different presets. I ended up doing this table that compares them with their default protections:
 
| *Protection / Preset* | Minimum            | Normal             | Aggressive         | Maximum            |
| --------------------- | ------------------ | ------------------ | ------------------ | ------------------ |
| **Anti Debug**        | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **Anti Dump**         |                    |                    |                    | :white_check_mark: |
| **Anti IL Dasm**      | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **Anti Tamper**       |                    |                    |                    | :white_check_mark: |
| **Constants**         |                    | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **Control Flow**      |                    | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **Invalid Metadata**  |                    |                    |                    | :white_check_mark: |
| **Name**              | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **Hardening**         | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **Reference Proxy**   |                    | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **Resources**         |                    | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **Type Scramble**     |                    |                    |                    |                    |
| **Watermark**         | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

As you can see above, there is no difference that stands out between the normal and aggressive presets. Is there something I'm missing ?

Thanks

**Comment by mkaring** [comment]
You are correct. There is nothing to miss here. Currently both presets are exactly the same.

**Comment by elkoiko** [comment]
Thank you very much for your quick answer !
