### ISSUE TITLE
Skip obfuscation for *.winmd library

### ISSUE THREAD

**Issue by adamshakhabov** [mkaring/ConfuserEx#455]
- ConfuserEx Version: 1.5.0
- Target Framework: .NET Framework 4.8
- Operating System: Windows 10 Pro

## *.csproj v1
Here is my initial *.csproj file:

```XML
<project baseDir="obj\Release" outputDir="..\Release" xmlns="http://confuser.codeplex.com">
    <rule pattern="true" preset="aggressive" />
    <module path="MyProduct.exe">
        <rule pattern="true" preset="aggressive" inherit="false"></rule>
    </module>
</project>
```

Build fails with:

> Confuser.MSBuild.targets(69, 5): Could not resolve method: System.Void Windows.Storage.Streams.InMemoryRandomAccessStream::Dispose() (Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime)

My application uses `Windows.winmd` library.

![image](https://user-images.githubusercontent.com/5969304/149592296-fa2d84d9-453a-481c-8305-b384d839fd74.png)

## *.csproj v2
Now I am trying to avoid `Windows.winmd` obfuscation with the following updates:

```XML
<project baseDir="obj\Release" outputDir="..\Release" xmlns="http://confuser.codeplex.com">
    <rule pattern="true" preset="aggressive" />
    <module path="MyProduct.exe">
        <rule pattern="true" preset="aggressive" inherit="false"></rule>
    </module>
    <module path="..\..\..\libs\Windows.winmd">
        <rule pattern="true" preset="none" inherit="false"></rule>
    </module>
</project>
```

This also failed, but this time on the other type:

> Confuser.MSBuild.targets(69, 5): Could not resolve method: System.Object Windows.Foundation.Collections.IMapView`2<System.String,System.Object>::Lookup(System.String) (Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime)
---

Since `Windows.winmd` does not relate to my business code, I would like to avoid obfuscation for that. Is it possible? Or how I can resolve the latest issue?

**Comment by mkaring** [comment]
You can always declare a library as external.
You can do that by adding `external="true"` in the `module` tag. Those attributes are considered dependencies and will not get obfuscated.
The second error still points to confuserex being unable to find a specific type. Where is `Windows.Foundation.Collections.IMapView`2` located? You may need to add that library as well to the project.

**Comment by adamshakhabov** [comment]
`Windows.Foundation.Collections.IMapView` also in the same [Windows.winmd](https://github.com/mkaring/ConfuserEx/files/7874406/Windows.winmd.zip) library.

----

Regard `external=true` attribute, if I use it:

```XML
<project baseDir="obj\Release" outputDir="..\Release" xmlns="http://confuser.codeplex.com">
    <rule pattern="true" preset="aggressive" />
    <module path="Define.Pdf.exe">
        <rule pattern="true" preset="aggressive" inherit="false"></rule>
    </module>
    <module path="..\..\..\libs\Windows.winmd" external="true"></module>
</project>
```

it does not affect — it still throws initial exception about `Windows.Storage.Streams.InMemoryRandomAccessStream::Dispose()`:

> Confuser.MSBuild.targets(69, 5): Could not resolve method: System.Void Windows.Storage.Streams.InMemoryRandomAccessStream::Dispose() (Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime)

**Comment by mkaring** [comment]
There is a bug in 1.5 that may cause this. Could you give the 1.6 RC version a try. This should sort it out.

**Comment by adamshakhabov** [comment]
I was able to resolve this issue with `"ref proxy".mode=strong` setting. Here is my work .crproj:

```XML
<project baseDir="obj\Release" outputDir="..\Release" xmlns="http://confuser.codeplex.com">
    <rule pattern="true" preset="aggressive" inherit="false" />
    <module path="MyProduct.exe">
        <rule pattern="true" preset="aggressive" inherit="false">
            <protection id="ref proxy">
                <argument name="mode" value="strong" />
            </protection>
        </rule>
    </module>
</project>
```
