### ISSUE TITLE
Add non-assembly file to compress packer as a embedded resource 

### ISSUE THREAD

**Issue by JerryJian** [mkaring/ConfuserEx#463]
Hi,

I want to package some files which are not assemblies into the result exe using compressor. Is there any option for that?

Thanks.

**Comment by mkaring** [comment]
No there is not. Reason is that the assemblies are handled _always_ loaded in the same way and ConfuserEx can inject intercept code that redirects loading the assembly. That is the basis for the packer.

For general files the logic to load and handle those files can be anything. If you want the files embedded, why not just link them into the resx files and have those load the files?

**Comment by JerryJian** [comment]
My app is a plugin framework application. The first time boot, it will scan all assemblies and cache the plugin information to a file. And next time start up, if there is no version changed, the app loaded assemblies according to the cache file.

The problem is, it can't scan plugins after pakaging assemblies into a single exe.

So I want to package the cache file without encryption into the final exe as a manifest resource, then I can load the cache file at the entry point using Assembly.GetEntryAssembly().GetManifestResource as the first priority cache and fallback to cache file.

I can't add the cache file to my assembly because the mechanism check a checksum of all the dll files. If I change the content of the dll file, the checksum is changed, and will trigger the re-scan plugins method.

At present I will try to use other tool or Mono.Ceil to achieve the goal. But I still want this great tool can support this feature.

Thanks @mkaring
