### ISSUE TITLE
Temp Files remain after packing

### ISSUE THREAD

**Issue by ElektroKill** [mkaring/ConfuserEx#47]
During the packing stage, a temp directory is created containing the packed exe. After the protection, the file and directory remain, my suggestion is to make ConfuserEx delete the temp directory after everything is done.

**Comment by mkaring** [comment]
I agree. There shouldn't be any left over file. Could you please specify the version of ConfuserEx you were using when observing this issue?

**Comment by ElektroKill** [comment]
I am using the latest build from AppVeyor

**Comment by mkaring** [comment]
Fixed the problem. The files are now properly cleaned up. Will be fixed in 1.2 and 2.0.
