### ISSUE TITLE
ImportResolver error (Solved)

### ISSUE THREAD

**Issue by T5ive** [mkaring/ConfuserEx#5]
In InjectHelper.cs I found the error
'Importer' does not contain a definition for 'Resolver' and no accessible extension method 'Resolver' accepting a first argument of type 'Importer' could be found (are you missing a using directive or an assembly reference?)

**Comment by mkaring** [comment]
You are using the wrong version of dnlib. Please make sure that you are using my fork of dnlib. It is up to date with the original one by @0xd4d and contains a few ConfuserEx specific modifications to make it work. Such as the `Resolver` in the `Importer`. :wink:
