### ISSUE TITLE
Random Service Issue (Common Language Runtime Detected an Invalid Program)

### ISSUE THREAD

**Issue by FenixDan** [mkaring/ConfuserEx#52]
I don't know what happened, but since 3 days ago the project is giving me this error with Random Service.

I have downloaded the last commit again and it's still giving me this issue.

It's not even executing the method, it crashes before, or at least that's what it looks like.

![img](https://image.prntscr.com/image/JSQ9KGwISwO4QW4PNHh8IQ.png)

![img2](https://image.prntscr.com/image/rxtcLI-4SfSvVRAQwHSqSA.png)

I'm using the release/2.0 branch.

Any protection that uses the random service gets the issue.

This is with rename protection.

![img3](https://image.prntscr.com/image/fPSHMd6uTkq8yDTdDUR0xQ.png)

**Comment by mkaring** [comment]
I am absolutely certain that the random value generator is working file. An error like this would be raised during the unit tests. Also there is nothing special about the code where the exception is raised. The error points to the `NextUInt32` method to be the reason for the problem. The only idea I have is that the compiler is doing something wrong in relation to the `stackalloc` and the `Span<byte>` type.

Is your Visual Studio up-to-date? Or did you recently install an update that may be the source of the issue?

**Comment by FenixDan** [comment]
Indeed, you're right.

Looks like the preview version of Visual Studio 2019 was causing the issue.

Than you!
