### ISSUE TITLE
ConfuserEx Error

### ISSUE THREAD

**Issue by hrsk123** [mkaring/ConfuserEx#520]
[ERROR] Failed to load "YOUR MUTHER FIGHTER.vmp.exe" - Assembly does not appear to be a .NET assembly: ".NET data directory RVA is 0".
Failed at 11:28, 0:00 elapsed.

**Comment by hrsk123** [comment]
We trying with The strongest protect also try ConfuserEx can Protect with another thing protected well we tried With Normal exe Without protect and use ConfuserEx But Still same Error and We try rn make UnCrackable Or Harder to the File Get Cracked or source code leaked Any tip or etc for fix?

**Comment by edcdecl** [comment]
Well, _is it a .NET assembly?_

**Comment by hrsk123** [comment]
Fixed my bad and yes just the .net assembly have in the src Find debugger etc etc
