### ISSUE TITLE
ConfusedBy is seen.

### ISSUE THREAD

**Issue by bolt-b** [mkaring/ConfuserEx#537]
Hello everyone,

Used ILSpy to see how has been changed confused library. What is really seen before and after.
What I've seen first when confused lib was added to ILSpy is attached below.
Seems  it is good hint to those who need to know what was used for confusing.
So, how to turn off this hint?

![ConfusedBy](https://github.com/mkaring/ConfuserEx/assets/80217182/60faf481-bfb3-47d6-89e7-5a0cdbd42eec)

**Comment by sunnamed434** [comment]
Not sure if it can be disabled, but simply remove the attribute using dnSpy

**Comment by mkaring** [comment]
The watermark can be removed by the rules. 
More details about this, can be found here: [Watermark - ConfuserEx Wiki](https://github.com/mkaring/ConfuserEx/wiki/Watermark)

**Comment by bolt-b** [comment]
> The watermark can be removed by the rules. More details about this, can be found here: [Watermark - ConfuserEx Wiki](https://github.com/mkaring/ConfuserEx/wiki/Watermark)

That's the point, the _watermarking_ was not selected at all. The only kind of protection was used, it's _renaming_.
As it is shown below. So, I have no clue which way the _watermarking_ has been enabled in this particular case.



![rule](https://github.com/mkaring/ConfuserEx/assets/80217182/0e63b499-0fb8-4af5-916c-e3a375f74a3e)

**Comment by mkaring** [comment]
Please read the "remarks" part of the wiki page. The watermark is enabled by default and needs to be removed explicitly.

**Comment by bolt-b** [comment]
> Please read the "remarks" part of the wiki page. The watermark is enabled by default and needs to be removed explicitly.

Sorry, so, where do I need to put this line? I don't understand.

`<protection id="watermark" action="remove" />`

**Comment by mkaring** [comment]
Either in the rule file you save, or you add it to the rules you showed in the in the screenshot above, add the "watermark" rule and switch the first combobox in the line to "remove".

**Comment by bolt-b** [comment]
> Either in the rule file you save, or you add it to the rules you showed in the in the screenshot above, add the "watermark" rule and switch the first combobox in the line to "remove".

I confused a bit with how Confuser is working. :)
Based on your post above. If I nothing "removed"  as  you described above, does it mean that all  confusing methods will be applied?
In other words, if I want to use "renaming" _**only**_.  I should add it. It is understandable. 
What about other methods? Should I leave them as is (don't touch them)? Or should I "remove" them, the way you described above?

**Comment by TooMuchBlue** [comment]
> What about other methods. Should I leave them as is? Or should I "remove" them?

It varies by protection.  Many protections are only used if you enable them.  However, once you enable them, they may include some default behaviors that you don’t want, and you would need to disable or “dial down” those features to the level you need.

For example, the “constants” protection is disabled by default.  If you enable “constants” it will default to compressor=”LZMA”.  If you do not want compression of constants, you would need to disable this particular feature.

There are too many variations like this to explain via email.  The documentation is your friend.  https://github.com/mkaring/ConfuserEx/wiki/Documentation > Protections
