### ISSUE TITLE
Which dnlib version does ConfuserEx depends?

### ISSUE THREAD

**Issue by ismlsmile** [mkaring/ConfuserEx#56]
I used the newest version 3.2, but when compile, there is an error in InjectHelper.cs : can not find class ImportResolver

**Comment by mkaring** [comment]
The `release/2.0` branch depends on Version 3.2 of dnlib. The `master` branch depends on a custom version of dnlib you can find [here][1].

[1]: https://github.com/mkaring/dnlib

**Comment by ismlsmile** [comment]
thanks
