### ISSUE TITLE
MEF Issue

### ISSUE THREAD

**Issue by ElenaMilito** [mkaring/ConfuserEx#6]
Hello,
I wanted import a object in InjectPhase class but the imported object always return null I added Export attribute to InjectPhase class but exclude plugin from protections.

**Comment by mkaring** [comment]
In the cases I used, the phases were not exported over MEF. Only the protections and confuser components are. Not exactly sure what you tried to do. The protections currently all know exactly what phases are required.

Can you share some code? How you exported and imported the objects?

**Comment by ElenaMilito** [comment]
I noticed must import the class in Protection class for usage in InjectPhase must call to Parent property but if it was possible to import class directly from InjectPhase it would be good.

**Comment by mkaring** [comment]
I still do not understand what exactly it is you are trying to do. Have a look at the phases of the other protections on how to properly implement the `Parent` property.

For example:
https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Renamer/AnalyzePhase.cs#L16

**Comment by ElenaMilito** [comment]
My mean is solved my problem by call to Parent property (Parent.MyClassImport), Now I Import the CompositionContainer but returned null I want call the container to GetExportedValue.

`namespace Confuser.Protections.Test {
	[Export(typeof(IProtection))]
	[ExportMetadata(nameof(IProtectionMetadata.Id), _FullId)]
	[ExportMetadata(nameof(IProtectionMetadata.MarkerId), _Id)]
	internal sealed class TestProtection : IProtection {

	[Import]
	public CompositionContainer container;
   }
}`

**Comment by mkaring** [comment]
You can't import the `CompositionContainer`. The only thing you can import are the protections that got the `Export` attributes.

**Comment by mkaring** [comment]
You have to be aware that currently only the other protections are in the composition container. You should be able to get those with

```CS
[Import]
public IEnumerable<IProtection> Protections { get; set; }
```

Not sure if that is what you were going for.

**Comment by ElenaMilito** [comment]
Problem resolved, Thanks.
