### ISSUE TITLE
Confuser.CLI.exe (v1.2.0) throws exception whenever ObfuscationAttribute is used

### ISSUE THREAD

**Issue by glasgowrob** [mkaring/ConfuserEx#61]
Is the following syntax for ObfuscationAttribute correct?

[Obfuscation(Exclude = false, Feature = "-rename")]

=========================================================

Details:

I ask because while Confuser.CLI.exe (v1.2.0) and ConfuserEx.exe are working **_amazingly well_** on my C#/WPF exe **_(thank you!)_**, no matter which item in my C# I put the previously mentioned ObfuscationAttribute above, ConfuserEx.exe can't finish obfuscation, and Confuser.CLI.exe (v1.2.0) throws an exception that says:

```
      Unknown error occurred.
System.InvalidCastException: Unable to cast object of type 'dnlib.DotNet.UTF8String' to type 'System.String'.
   at Confuser.Core.ObfAttrMarker.CreateObfuscationAttributeInfo(IHasCustomAttribute owner, ICustomAttribute ca, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 94
   at Confuser.Core.ObfAttrMarker.ReadObfuscationAttributes(IHasCustomAttribute item, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line
```
I am using ConfuserEx v1.2.0, downloaded from this page:

https://github.com/mkaring/ConfuserEx/releases

I didn't compile the source code. I just unzipped the zip file download and started using Confuser.CLI.exe at the command line and the ConfuserEx.exe UI.

My crproj file is as follows:

```
<project outputDir="C:\projects\<MyProjectName>\bin\<MyReleaseDirectory>\Obfuscated\" baseDir="C:\projects\<MyProjectName>\bin\<MyReleaseDirectory>\" xmlns="http://confuser.codeplex.com">
  	<rule pattern="true" preset="maximum" inherit="false">
		<protection id="anti ildasm" action="remove" />
		<protection id="anti tamper" action="remove" />
		<protection id="constants" action="remove" />
		<protection id="ctrl flow" action="remove" />
		<protection id="anti dump" action="remove" />
		<protection id="anti debug" action="remove" />
		<protection id="invalid metadata" action="remove" />
		<protection id="ref proxy" action="remove" />
		<protection id="resources" action="remove" />
		<protection id="rename">
			<argument name="mode" value="decodable" />
			<argument name="flatten" value="true" />
			<argument name="renameArgs" value="true" />
			<argument name="renPublic" value="true" />
			<argument name="renEnum" value="true" />
			<argument name="renXaml" value="true" />
			<argument name="renPdb" value="false" />
			<argument name="forceRen" value="false" />
		</protection>
  	</rule>
  	<module path="C:\projects\<MyProjectName>\bin\<MyReleaseDirectory>\<MyExeName>.exe" />
</project>
```

**Comment by mkaring** [comment]
The syntax you are using is fine, the problem is that I can't reproduce the issue you are having. My tests with those attributes are running fine. I checked the code and it all looks okay. 

Are you able to reproduce this issue in a minimal example?

**Comment by glasgowrob** [comment]
[ConfuserExTester.zip](https://github.com/mkaring/ConfuserEx/files/3387026/ConfuserExTester.zip)

Hi mkaring,

Thank you very much for the response and for looking at this.

I was able to reproduce this issue with the very simple WPF app that I attached.

Instructions to reproduce the issue:

1. Extract the zip file such that the top-level "ConfuserExTester" folder becomes the directory "C:\projects\ConfuserExTester".

2. Open up the ConfuserEx UI  (use the version that you can obtain following my original instructions in the original issue) and open the crproj file "C:\projects\ConfuserExTester\MKaring_ConfuserEx_Github_Issue_61.crproj" with it.

3. "Protect It" by running the ConfuserEx UI. This didn't work for me.

4. Comment out Line 21 of code file "C:\projects\ConfuserExTester\ConfuserExTester\Class1.cs", which is the line that reads "[Obfuscation(Exclude = false, Feature = "-rename")]" recompile in Release Mode.

5. Use the ConfuserUI to attempt to obfuscate this executable again. This worked for me.

6. To reproduce this problem on the command line using Confuser.CLI.exe (v1.2.0) (use the version that you can obtain following my original instructions in the original issue)., just enter the following at the command prompt:

"< Path to Confuser.CLI.exe on your machine >" "C:\projects\ConfuserExTester\MKaring_ConfuserEx_Github_Issue_61.crproj"

That's it. Thank you very much for looking at this.

By the way, if you uncomment the enum definition in Lines 10-15 if the file "C:\projects\ConfuserExTester\ConfuserExTester\Class1.cs" and obfuscate it, you should be able to reproduce my other open github issue #62 , because only the enum name, not the enum values, like "human_readable_plain_text_value1", is obfuscated.

glasgowrob

**Comment by mkaring** [comment]
Okay I can protect the assembly without any problems using the released ConfuserEx 1.2.0 version.
I tried both Debug and Release Builds of your assembly and used the released and my own compiled version of ConfuserEx.

The strange thing I am seeing is this line in your original report:
```TXT
at Confuser.Core.ObfAttrMarker.CreateObfuscationAttributeInfo(IHasCustomAttribute owner, ICustomAttribute ca, ILogger logger) in C:\projects\confuserex\Confuser.Core\ObfAttrMarker.cs:line 94
```

The thing is that the line number that is shown does not match the actual line number in the source code and that should match because the line references in the `*.pdb` files are accurate.

Could you add the complete output of the `Confuser.CLI` executable. I need to see at what point it fails and what it does on the way to this issue.

**Comment by glasgowrob** [comment]
mkaring,

I am terribly sorry for wasting your time.

I just re-downloaded the compiled ConfuserEx binaries using my own instructions as written in my initial issue, and both the Confuser UI and the Confuser.CLI executable not only worked perfectly on the test executable I posted to this issue, but **also obfuscated my real application better** than whatever binary I was using that I incorrectly believed to be the one I downloaded based on my instructions above.

It even obfuscated my enum values, so I will now go and close issue #62 , because it was the mystery binary, not your binary, that was failing to obfuscated my enum values.

All I can think of that could have caused this is that I had your ConfuserEx, the Xenocode ConfuserEx, and the original ConfuserEx binaries in different folders, and I must have been accidentally using one of their binaries, not yours. Ouch.

**Again, I apologize for wasting your time. Your version of ConfuserEx is really fantastic.**

Best regards,

glasgowrob

**Comment by mkaring** [comment]
Glad it cleared up ;-)

**Comment by KvanTTT** [comment]
But this issue still actual.

When I add the following attribute:

```cs
[Obfuscation(Exclude = true, Feature = "-rename")]
```

the following exception occurrs:

```cs
System.InvalidCastException: Unable to cast object of type 'dnlib.DotNet.UTF8String' to type 'System.String'.
```

But If I remove `Feature` property and leave `Obfuscation` alone:

```cs
[Obfuscation(Exclude=true)]
```

another exception occurs:

```cs
System.NullReferenceException: Object reference not set to an instance of an object.
```

How can I fix it eventually? At least how to get rid of obfuscation of some classes and members?
