### ISSUE TITLE
MSBuild Task

### ISSUE THREAD

**Issue by eaba** [mkaring/ConfuserEx#69]
Please can you provide step by step guide on how to use MSBuild.Task?

**Comment by KvanTTT** [comment]
See also my attempts: https://github.com/mkaring/ConfuserEx/issues/59

**Comment by eaba** [comment]
Hello @KvanTTT  thanks for the response. I tried that and got same error as you:
```ConfuseAssembly:
  [CRITICAL] An IO error occurred, check if all input/output locations are readable/writable.```
Did you eventually get it to work?

**Comment by mkaring** [comment]
I think the main problem is that the MSBuild task was never tested to work with .NET Standard or .NET Core. I only ever used to with assemblies targeting the .NET Framework and there is works pretty well.

**Comment by mkaring** [comment]
The 1.3 version is deployed to [Nuget.org](https://www.nuget.org/packages/Confuser.MSBuild/1.3.0). This version should work properly. The 2.x branch is still a little... problematic with that package.
