### ISSUE TITLE
How can i change confusedby module?

### ISSUE THREAD

**Issue by Z01wvay** [mkaring/ConfuserEx#70]
Hey there, i was wondering if i could change the module [ConfusedBy("Confuserex1.0.0")

will appreciate really much, thanks a lot!

Jack

**Comment by MurariAlex** [comment]
Hello, take a look at [this post](https://github.com/yck1509/ConfuserEx/issues/305#issuecomment-135749150).

**Comment by mkaring** [comment]
The watermarking happens here: [ConfuserEngine.cs:341][1]
If you alter or remove that part of the code, you can easily change it to your needs.

[1]: https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Core/ConfuserEngine.cs#L341

**Comment by Z01wvay** [comment]
> Hello, take a look at [this post](https://github.com/yck1509/ConfuserEx/issues/305#issuecomment-135749150).

Ok, sorry but i didn't explained good yet, i will provide a screenshot of what i want to change,

Thanks a lot!

![image](https://user-images.githubusercontent.com/43723413/63637091-8c13e500-c678-11e9-8146-8b99ca7d4840.png)
Example

**Comment by mkaring** [comment]
I don't get it. What exactly are you trying to do?

**Comment by ElektroKill** [comment]
He’s trying to change/remove the watermark attribute.

Example:
`ConfusedBy(“ConfuserEx 1.0.0”)` into `ScambledBy(“CodeScrambler”)`

**Comment by Z01wvay** [comment]
> He’s trying to change/remove the watermark attribute.
> 
> Example:
> `ConfusedBy(“ConfuserEx 1.0.0”)` into `ScambledBy(“CodeScrambler”)`

Yeah, thats what i'd like to do, please tell me how! 
ElectroKill Amazing Dev!

**Comment by ElektroKill** [comment]
Here is how to change the name of the attribute
Go to [this line](https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Core/ConfuserEngine.cs#L34) and change the `ConfusedByAttribute` to anything else but remember it has to end with `Attribute`, Example `ProtectedByAttribute`.

To change the parameter go to [this line](https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Core/ConfuserEngine.cs#L364) and change `Version` to any string parameter.

**Comment by Z01wvay** [comment]
> Here is how to change the name of the attribute
> Go to [this line](https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Core/ConfuserEngine.cs#L34) and change the `ConfusedByAttribute` to anything else but remember it has to end with `Attribute`, Example `ProtectedByAttribute`.
> 
> To change the parameter go to [this line](https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Core/ConfuserEngine.cs#L364) and change `Version` to any string parameter.

Thanks a lot! Closing Thread!
