### ISSUE TITLE
Support for .NET Core 3.0

### ISSUE THREAD

**Issue by RobSiklos** [mkaring/ConfuserEx#74]
I see that at the moment only 2.2 is supported. Given that .NET Core is already in preview 8, and is supposed to release officially in a month, is there any timeline for .NET Core 3.0 support by ConfuserEx?

Also, will this support be in the 1.x line, or will we need to wait for 2.0?

Thanks!

**Comment by mkaring** [comment]
The 1.x line "supports" .NET Core 3.0 the same way as it kind of supports .NET 2.x
You have to add all the reference assemblies of the .NET Core runtime by hand. If you do so some of the obfuscations work.

The 2.x line will have proper support for .NET Core (all versions), that is the part I am working on right now, but it's more difficult to get this working properly than I initially thought. But I am getting there. ;-)

**Comment by abelykh0** [comment]
>> The 2.x line will have proper support for .NET Core (all versions), that is the part I am working on right now, but it's more difficult to get this working properly than I initially thought. But I am getting there. ;-)
What is the status of this? .Net Core 3.0 was released.

**Comment by kirsan31** [comment]
@mkaring 
May be reopen this for tracking on core 3.0+ support?
