### ISSUE TITLE
ApplyToMembers not work in ObfuscationAttribute(Exclude = true, ApplyToMembers = true)]

### ISSUE THREAD

**Issue by ahmedosama007** [mkaring/ConfuserEx#75]
**ApplyToMembers** does not work in `ObfuscationAttribute(Exclude = true, ApplyToMembers = true)]`, it should exclude all class members from certain protection modules

**Comment by ahmedosama007** [comment]
The workaround is to add the attribute to each property/method of the class

For example `[Obfuscation(Exclude = false, Feature = "-rename")]` to exclude from Rename protection

[https://github.com/yck1509/ConfuserEx/issues/525](https://github.com/yck1509/ConfuserEx/issues/525)

**Comment by mkaring** [comment]
Yes, but this is a proper hassle. Especially if the class contains a lot of members. I'll try to fix this for the 1.x and the 2.x releases.

**Comment by KvanTTT** [comment]
@ahmedosama007, unfortunately, it does not work for properties, only for fields. I guess this is due to properties contain autogenerated getter and setter.

**Comment by mkaring** [comment]
@KvanTTT: That did not work at all properly. A type with this specific attribute should forward it's altered configuration to all the members.

@ahmedosama007: I think I fixed the issue and the version containing the fix can be downloaded [here][1]. I would appreciate some feedback if it works for you now. 

[1]: https://ci.appveyor.com/project/mkaring/confuserex/builds/26942430/artifacts

**Comment by ahmedosama007** [comment]
@mkaring Thanks, I confirm that the issue was fixed, **ApplyToMembers = true** is now can exclude all class members from certain protections specified by attribute parameter **Feature**

**Comment by KvanTTT** [comment]
@mkaring in your build renaming of public members and types are disabled by default. It differs from previous behavior. Is this made intentionally?

**Comment by mkaring** [comment]
@KvanTTT Not exactly sure what you are talking about.

**Comment by KvanTTT** [comment]
`renPublic` is `false` in your build. In the previous version, it was `true`.

**Comment by mkaring** [comment]
@KvanTTT If you have a look [here][1] you find the behaviour of `renPublic` unchanged for some time in the 1.x branch. In the 2.x line this parameter is gone and that it intentional. It will be replaced with something more clearly structured.

[1]: https://github.com/mkaring/ConfuserEx/blame/master/Confuser.Renamer/AnalyzePhase.cs#L149
