### ISSUE TITLE
ConfusedBy attribute

### ISSUE THREAD

**Issue by ahmedosama007** [mkaring/ConfuserEx#76]
How to disable **ConfusedBy** attribute added to obfuscated assemblies
`[module: ConfusedBy("Confuser.Core 1.2.0+4110faee9d")]`

**Comment by MurariAlex** [comment]
Hello, take a look at [this post](https://github.com/yck1509/ConfuserEx/issues/305#issuecomment-135749150).

**Comment by mkaring** [comment]
Please see: #70
