### ISSUE TITLE
Hard fork with name ConfuserEx2?

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#77]
What do you think about a hard fork (without reference to source repository) with the actual name **ConfuserEx2**? The source repository died anyway.

It can help to resolve the confusion of Confusers 😄

**Comment by mkaring** [comment]
Once ConfuserEx 2 is closer to be ready, I am very likely doing that.
For now I still use the "network" this fork is part of to keep track of changes and improvements of other forks (I can use github to compare the changes relative to this fork)
Not much like this going on lately... but still. :wink:
