### ISSUE TITLE
signature of the body and declaration in a method implementation do not match

### ISSUE THREAD

**Issue by lengyeljanos** [mkaring/ConfuserEx#78]
I am getting the following exception when I start the resulting exe file, even if there is no protection enabled.

"signature of the body and declaration in a method implementation do not match"

code:

```
    public class EasyDict<TKey, TValue> : IEnumerable<KeyValuePair<TKey, TValue>>
    {
        private readonly Dictionary<TKey, TValue> _dict;

        public EasyDict()
        {
            _dict = new Dictionary<TKey, TValue>();
        }

        public EasyDict(int capacity)
        {
            _dict = new Dictionary<TKey, TValue>(capacity);
        }

        public int Count => _dict.Count;

        public IEnumerable<TValue> Values => _dict.Values;

        public TValue this[TKey key]
        {
            get
            {
                _dict.TryGetValue(key, out var value);
                return value;
            }
            set
            {
                _dict[key] = value;
            }
        }

        public void Add(TKey key, TValue value)
        {
            _dict[key] = value;
        }

        public void Clear()
        {
            _dict.Clear();
        }

        public bool ContainsKey(TKey key)
        {
            return _dict.ContainsKey(key);
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return _dict.GetEnumerator();
        }

        IEnumerator<KeyValuePair<TKey, TValue>> IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()
        {
            return _dict.GetEnumerator();
        }

        public bool Remove(TKey key)
        {
            return _dict.Remove(key);
        }

        public bool TryGetValue(TKey key, out TValue value)
        {
            return _dict.TryGetValue(key, out value);
        }
    }

```

**Comment by KvanTTT** [comment]
Useful issue and sample. I've encountered such an error several times in my code. Even `[Obfuscation(Exclude = false, Feature = "-rename"]` attribute does not help. I think this issue related to incorrect obfuscation of generic types.

I would be very appreciated if this issue was finally resolved.

**Comment by lengyeljanos** [comment]
I agree. Currently this bug blocks my release. A fix would be highly appreciated!

**Comment by mkaring** [comment]
What version are you using? 1.x or 2.x?

**Comment by KvanTTT** [comment]
I've tried both with the same result.

**Comment by lengyeljanos** [comment]
1.2.0.21

**Comment by mkaring** [comment]
I have a fairly good idea what the problem here is. I'm trying to fix this today.

**Comment by mkaring** [comment]
The issue is caused by the fix for #38

**Comment by mkaring** [comment]
I think this may be a error in dnlib. This may take a little longer, until I got in touch with 0xd4d.

The ticket for dnlib is: https://github.com/0xd4d/dnlib/issues/304

**Comment by lengyeljanos** [comment]
I see you got an answer in tthe dnlib ticket. Is this good news? :)

**Comment by mkaring** [comment]
It is. I know how to fix it. I'll do so as fast as possible.

**Comment by lengyeljanos** [comment]
thank you very much!

**Comment by mkaring** [comment]
@lengyeljanos Could you check if the build you can download here: https://ci.appveyor.com/project/mkaring/confuserex/builds/27216801/artifacts
Works for you?

**Comment by lengyeljanos** [comment]
It looks like working! Very good, thank you a lot!
