### ISSUE TITLE
Consider donations via opencollective

### ISSUE THREAD

**Issue by KvanTTT** [mkaring/ConfuserEx#79]
I want to make a donation to your awesome project for all your great work. I know, there is a donation link [liberapay](https://liberapay.com/mkaring/) but it does not support one-time payments, it supports only per period ones. I suggest to use [opencollective](https://opencollective.com/) service: it shows a clear history of money transfers, a lot of projects use it.

**Comment by mkaring** [comment]
I looked into that already, but the issue is that they don't seem to recognise forked repository. Guess I'll end up disconnecting his repository from the fork network like you suggested in #77 
I don't think I get this working any other way.

**Comment by mkaring** [comment]
Done
