### ISSUE TITLE
strange "missing something" problem

### ISSUE THREAD

**Issue by lengyeljanos** [mkaring/ConfuserEx#81]
One of my users got this error right when starting the .exe:
https://i.imgur.com/9TTs7vC.png

I hope you may know what can cause the issue.

He says it is a Windows 7 SP1 machine with .NET 4.7.2 and DX11, latest updates, C++ redist installed.
I can ask for details later if you need.

My obfuscation settings in a nutshell:

```
    <protection id="anti dump" />
    <protection id="anti tamper">
      <argument name="key" value="dynamic" />
    </protection>
    <protection id="ref proxy" />
    <protection id="rename">
        <argument name="renPublic" value="true" />
        <argument name="renameArgs" value="true" />
    </protection>
      <protection id="ctrl flow">
        <argument name="predicate" value="x86" />
        <argument name="intensity" value="100" />
        <argument name="depth" value="20" />
        <argument name="junk" value="true" />
      </protection>
      <protection id="constants">
        <argument name="mode" value="x86" />
        <argument name="decoderCount" value="100" />
        <argument name="cfg" value="true" />
      </protection>
      <protection id="invalid metadata" />
      <protection id="resources" />

```

**Comment by lengyeljanos** [comment]
Does the "x64" obfuscations need any "outside" .dll files?

**Comment by mkaring** [comment]
What version of ConfuserEx are you using? The 1.x or 2.x?
Are there any warnings appearing during the obfuscation?

Does the error happen only for your users or also on your system? Can you provide anything in addition to this error? I'll take memory dumps of the crash, the obfuscated application (so I can analyse it myself)

What version of .NET Framework is your assembly using?

My first guess would be that the constants protections may have broken the some native call reference, but that is the only guess I can offer as of right now and it's pure speculation.

The native protections aren't using any external assemblies. Some of the obfuscations are using external assemblies, but those are part of Windows since the beginning of time. What operating system are your users using?

**Comment by ElektroKill** [comment]
That name looks like it may be resource protection generated module

**Comment by lengyeljanos** [comment]
> What version of ConfuserEx are you using? The 1.x or 2.x?
> Are there any warnings appearing during the obfuscation?
> 
> Does the error happen only for your users or also on your system? Can you provide anything in addition to this error? I'll take memory dumps of the crash, the obfuscated application (so I can analyse it myself)
> 
> What version of .NET Framework is your assembly using?
> 
> My first guess would be that the constants protections may have broken the some native call reference, but that is the only guess I can offer as of right now and it's pure speculation.
> 
> The native protections aren't using any external assemblies. Some of the obfuscations are using external assemblies, but those are part of Windows since the beginning of time. What operating system are your users using?

I use the build you gave me to resolve issue #78:
https://ci.appveyor.com/project/mkaring/confuserex/builds/27216801/artifacts

I target .net 4.7.2, and this specific user has Windows 7 SP1 on his machine.

**Comment by lengyeljanos** [comment]
removing resource protection did not solve this error, but changed it:

https://i.imgur.com/XrfUbfr.png

**Comment by lengyeljanos** [comment]
no idea? :(

**Comment by mkaring** [comment]
I think the source of the issue is the `constants` protection. It looks like it is obfuscating some constant value that is used to call something native. And this in turn causes the native call to reference something that does not exist.

So it would be interesting to see if the issue can be resolved by disabling the constants protection. If we'll need to look at any native calls you got in your application.

**Comment by lengyeljanos** [comment]
My project is full with [DllImport], but I apply constants protection on only 1 namespace and it contains zero [DllImport].

It contains the following stuff:
- internal static readonly string in an internal static class
- internal classes
- Assembly.GetExecutingAssembly() call
- something like this:
            var asm1 = Assembly.GetExecutingAssembly();
            var asm2 = Assembly.GetAssembly(GetType());
            var asm1CodeBase = Path.GetFileName(asm1.GetName().CodeBase.Replace("file:///", "")).ToLowerInvariant();
- many calls to other namespaces without constant obfuscation
- some WebClient calls
- a simple Form
- 1 WinAPI call to
            [DllImport("user32.dll")]
            public static extern int SetWindowLong(IntPtr hWnd, int nIndex, int dwNewLong);
but the method is declared in a namespace without constant obfuscation
- and it contains the program.cs which starts the whole application

I can not disable constant obfuscation because I can't risk giving the .exe to the user without constant obfuscation :(

**Comment by mkaring** [comment]
Okay that is something.
How are you accessing these `internal static readonly string` fields? Any reflection going on there?

**Comment by lengyeljanos** [comment]
Just by name. The only reflection is the Assembly.GetExecutingAssembly stuff above.

I know real const can be obfuscated, that's why I use static readonly instead.

**Comment by mkaring** [comment]
Is there any chance that I could get my hands on the _obfuscated_ application or at least the assembly for analysis. I need something to go on, without I won't be able to find a solution.

**Comment by lengyeljanos** [comment]
how can I send you a private message?

**Comment by mkaring** [comment]
There is an [e-mail address][1] on my [profile][2]. If you have further security concerns, you can find the public part of my gpg key on [the tags][3] or [here][4]

[1]: mailto:karing.martin@gmail.com
[2]: https://github.com/mkaring
[3]: https://github.com/mkaring/ConfuserEx/releases/tag/v1.2.0
[4]: https://keyserver.ubuntu.com/pks/lookup?search=0x3C03D13B7A32D34A&op=get&fingerprint=on

**Comment by mkaring** [comment]
@lengyeljanos Any news?

**Comment by lengyeljanos** [comment]
The used got a new machine and he has no issue since then. I think this can be closed until somebody else experience it again.
