### ISSUE TITLE
CFG Constants causing error on VB app

### ISSUE THREAD

**Issue by ElektroKill** [mkaring/ConfuserEx#82]
When I use these settings ConfuserEx2 fails to protect the application and a maxstack error is thrown. I am using the 2.0 branch.
```
<rule pattern="true" inherit="false">
    <protection id="constants">
        <argument name="cfg" value="true" />
    </protection>
</rule>
```
Here is the project file and exe file I am using

[Files.zip](https://github.com/mkaring/ConfuserEx/files/3587786/Files.zip)

**Comment by mkaring** [comment]
Fixed the issue in the `master` branch as it was present there too.
I was a little lazy with the merges into `releases/2.0` lately and that means that this will take a little longer.

**Comment by mkaring** [comment]
@ElektroKill: The latest build for the `release/2.0` branch contains the fix.

**Comment by ElektroKill** [comment]
Just tested the new build and it works fine with my test app, thanks ;)
