### ISSUE TITLE
Execution problem after obfuscation - link to Visual Studio version ?

### ISSUE THREAD

**Issue by OlivierCARRE-O2C** [mkaring/ConfuserEx#83]
Since several days - I update Visual Studio to 16.2.4 version ? - my exe does not work anymore after obfuscation (it closes itself after the start phase). Warning messages during obfuscation are the same than before - I have tried the last version of ConfuserEx (1.3 alpha) but the problem is the same (with one warning less about my software resource). Before that, I used ConfuserEx 1.0 since 5 months without any problem. I have not change my project configuration :
```
<project outputDir="C:\Users\...\Confused" baseDir="C:\Users\...\bin" xmlns="http://confuser.codeplex.com">
  <module path="Appli_PDP_VCG.exe">
    <rule pattern="true" preset="normal" inherit="false">
      <protection id="anti ildasm" />
      <protection id="anti tamper" />
      <protection id="constants" />
      <protection id="ctrl flow" />
      <protection id="anti debug" />
      <protection id="invalid metadata" />
      <protection id="ref proxy" />
      <protection id="resources" />
      <protection id="anti dump" action="remove" />
      <protection id="rename" action="remove" />
    </rule>
  </module>
  <module path="EntityFramework.dll" />
  <module path="EntityFramework.SqlServer.dll" />
</project>
```

**Comment by mkaring** [comment]
First of I strongly recommend to mark the two additional assemblies with `external="true"` to avoid them being excessively analysed.

That being said, without any indication what kind of error the application encounters, this is next to impossible to diagnose. You can launch your application with dnspy or you can checkout the event viewser of windows to find the exception your application encounters.

**Comment by OlivierCARRE-O2C** [comment]
Thank you for your quick response Martin.
I will try with external = true and then track the error with dnspy.
I will come back to you soon.

**Comment by OlivierCARRE-O2C** [comment]
The parameter external=true have the ability to exclude all existing warning during obfuscation but the problem is still there so I will investigate the exception error with dnspy

**Comment by OlivierCARRE-O2C** [comment]
With the help of dnspy, I have shown my error = old version of a dll used by my software ! Thank you very much for your help

**Comment by MurariAlex** [comment]
@mkaring DLLs and Framework versions seems to be an recurrent problem that's not an ConfuserEx fault. Is there any way that the analyzer could point out in the output some warnings/errors when obfuscating code with inconsistent versions (if there's a way of doing that)?

**Comment by OlivierCARRE-O2C** [comment]
Inconsistent version is a testable delta between exe manifest which list all dll used by the software and each dll version
