### ISSUE TITLE
Renamer fails when inheriting properties from Attributes

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#84]
Here's a project which reproduces the issue by outputting the following message and the Attribute marked in the `Main` method in the demo project will get corrupted after obfuscation.

 [WARN] Failed to resolve CA property 'ConsoleApp1.ConstrainNullAttribute::Action : ConsoleApp1.ConstraintAction'.

[TEMP.zip](https://github.com/mkaring/ConfuserEx/files/3612214/TEMP.zip)

**Comment by mkaring** [comment]
Please check out [the build from the buildserver][1]. It contains the fix for the issue.

[1]: https://ci.appveyor.com/project/mkaring/confuserex/builds/27410604/artifacts

**Comment by wmjordan** [comment]
Great!
Thanks for the quick fix.
