### ISSUE TITLE
Generic Interface Implementation Could be Broken After Renaming

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#87]
Please test with the following assembly.
[ConsoleApp1.zip](https://github.com/mkaring/ConfuserEx/files/3630061/ConsoleApp1.zip)

The protection workflow ends without any error.
While you run the obfuscated one, you can get an error.

`Unhandled Exception: System.TypeLoadException: Signature of the body and declaration in a method implementation do not match.`

**Comment by MathieuSteiner** [comment]
We have the same error after obfuscation with one of our applications. 
Even with the build provided here: https://github.com/mkaring/ConfuserEx/issues/78, we are still facing the issue

I tried to reproduce with a simple example, but I failed at reproducing. 
Is this ConsoleApp1 application source code available in order for me to read it and check ?

**Comment by wmjordan** [comment]
The following code reproduces the issue:
````C#
	class Program
	{
		static void Main(string[] args) {
			var c = new C<string>();
			c.Print("", "");
		}
	}

	class C<X> : I<string, X>
	{
		public void Print(string t, X x) {
			
		}
	}

	interface I<X, Y>
	{
		void Print(X x, Y y);

	}
````

**Comment by mkaring** [comment]
Did you actually create an application that triggers every single bug in ConfuserEx? ;)
I'll look into it as soon as possible. I was fairly certain that I fixed this bug in #78. Seems I was wrong.

**Comment by wmjordan** [comment]
> Did you actually create an application that triggers every single bug in ConfuserEx? ;)

I don't know.
Hopefully this is the last one. :D

**Comment by KvanTTT** [comment]
I've just made a PR with such a bug at https://github.com/mkaring/ConfuserEx/pull/88 :smile:

**Comment by mkaring** [comment]
I got the bug. [This build][1] contains the fix that is the root cause I suspect to be the reason for the issue.
@wmjordan: Your console application works with this. Please give your actual application a try with the new build.
@KvanTTT: Your commit containing the update to the unit test is included in this build and the test was successful
@MathieuSteiner: Please give that new build a spin with your application.

[1]: https://ci.appveyor.com/project/mkaring/confuserex/builds/27536611/artifacts

**Comment by wmjordan** [comment]
Bravo!
My actual application is working after the protection.

**Comment by mkaring** [comment]
I'll keep this issue open for some feedback from @MathieuSteiner

**Comment by MathieuSteiner** [comment]
I have just been trying the build.
The error has disapared

Thanks a lot for your work and for sharing your knowledge @mkaring, we very apreciate it

**Comment by mkaring** [comment]
:+1: Very good. Issue closed.
