### ISSUE TITLE
Enhancement to StackTraceDecoder

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#92]
Please consider making the following changes to the stack trace decoder in _ConfuserEx\StackTraceDecoder.xaml_:

1. Using `PasswordBox` instead of TextBox for the `PassBox`.

```` XAML
<PasswordBox x:Name="PassBox" Grid.Row="1" Grid.Column="1" Margin="5" VerticalContentAlignment="Center"/>
````

2. Making the `stackTrace` box word-wrapped.

``` XAML
<TextBox x:Name="stackTrace" Grid.ColumnSpan="2" Grid.Row="2" Margin="5" AcceptsReturn="True" FontFamily="Consolas"
                 ScrollViewer.HorizontalScrollBarVisibility="Auto" ScrollViewer.VerticalScrollBarVisibility="Visible"
                 TextWrapping="Wrap" />
```

**Comment by mkaring** [comment]
Will be part of the 1.3 release as requested.

**Comment by wmjordan** [comment]
Thank you for adapting the code.

Could you please also make the "`Decode!`" button as the default button in the dialog as well?

**Comment by mkaring** [comment]
Will be part of the next release.
