### ISSUE TITLE
Not reading ObfuscationAttributes in v1.3.0

### ISSUE THREAD

**Issue by MulleDK19** [mkaring/ConfuserEx#95]
Just upgraded to the latest v1.3.0 release and now my assembly is not obfuscated at all; it just applies the ConfusedBy attribute.

For some reason, it's not reading the `[assembly: Obfuscation(...)]` anymore, and only obfuscates if I create a .crproj, which isn't ideal.

Haven't changed anything other than upgrading. Using command line as: `Confuser.CLI.exe -n "-out=C:\Bla\Confused" "C:\Bla\Main.exe" "C:\Bla\Assembly1.dll" "C:\Bla\Assembly2.dll"`

It works fine if I downgrade to v1.2.0.

**Comment by mkaring** [comment]
There is a change in the way the Obfuscation Attributes are handled. Did you set the "ApplyToMember" property of this attribute at all?

**Comment by mkaring** [comment]
I found the issue. I made a mistake when handing issue #75
I'll fix that asap.

**Comment by mkaring** [comment]
@MulleDK19: Could you please verify if the version you can [download here][1] fixes your issue?

[1]: https://ci.appveyor.com/project/mkaring/confuserex/builds/28064847/artifacts

**Comment by MulleDK19** [comment]
Will do

**Comment by MulleDK19** [comment]
Yea, seems to have fixed it.

**Comment by mkaring** [comment]
As this is a pretty critical error, I'll release it as a 1.3.1 hotfix version.

**Comment by MulleDK19** [comment]
Cheers!
