### ISSUE TITLE
GUI buttons not working as expected

### ISSUE THREAD

**Issue by ElektroKill** [mkaring/ConfuserEx#99]
The GUI buttons on the first page do not update properly as shown in the video provided. I am using the 2.0 branch.

https://www.youtube.com/watch?v=2hG1w2jxWqI

**Comment by mkaring** [comment]
I am aware of the issue. The UI is going to get a major overhaul as part of the 2.0 version. It's on the list.

**Comment by ElektroKill** [comment]
I am pretty sure this same issue is present in the 1.3.1 version, is it possible for you to fix it there?

**Comment by mkaring** [comment]
The issue is fixed in the upcoming 1.4 release and in the 2.0 branch.
